import React,{useEffect,useMemo,useState} from 'react';
import {Activity,BarChart3,Database,RefreshCw,Search,Sigma,Waves} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import InteractiveSurface3D from './InteractiveSurface3D.jsx';

const FUNCTIONS=['CHAIN','SURF','SKEW','TERM','RVIV','GREEKS','OI'];
const MONEYNESS=[-.20,-.15,-.10,-.05,0,.05,.10,.15,.20];
const money=n=>Number.isFinite(Number(n))?`$${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—';
const num=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const pct=n=>Number.isFinite(Number(n))?`${Number(n).toFixed(1)}%`:'—';
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
const mid=c=>Number.isFinite(c?.mid)?c.mid:Number.isFinite(c?.bid)&&Number.isFinite(c?.ask)?(c.bid+c.ask)/2:Number.isFinite(c?.last)?c.last:null;
const nearest=(rows,target,side)=>rows.filter(c=>(!side||c.side===side)&&Number.isFinite(c.strike)).sort((a,b)=>Math.abs(a.strike-target)-Math.abs(b.strike-target))[0]||null;
const dailyReturns=c=>{const out=[];for(let i=1;i<c.length;i++){const a=c[i-1]?.close,b=c[i]?.close;if(a>0&&Number.isFinite(b))out.push({time:c[i].time,r:(b-a)/a})}return out};
const rollingVol=(candles,n=20)=>{const r=dailyReturns(candles),out=[];for(let i=n-1;i<r.length;i++){const slice=r.slice(i-n+1,i+1).map(x=>x.r),m=mean(slice),sd=Math.sqrt(slice.reduce((s,v)=>s+(v-m)**2,0)/slice.length);out.push({time:r[i].time,label:new Date(r[i].time*1000).toLocaleDateString(undefined,{month:'short',day:'numeric'}),rv:sd*Math.sqrt(252)*100})}return out};

function surfaceFrom(payload){const contracts=(payload?.contracts||[]).filter(c=>Number.isFinite(c.iv)&&c.iv>0),spot=payload?.underlyingPrice||1,dtes=[...new Set(contracts.map(c=>c.dte).filter(Number.isFinite))].sort((a,b)=>a-b);const rows=dtes.map(dte=>{const bucket=contracts.filter(c=>c.dte===dte);return MONEYNESS.map(m=>{const target=spot*(1+m),call=nearest(bucket,target,'call'),put=nearest(bucket,target,'put'),vals=[call?.iv,put?.iv].filter(Number.isFinite);return{dte,moneyness:m,strike:call?.strike??put?.strike??target,iv:vals.length?mean(vals):0}})});return{rows,dtes,spot}}
function atmTerm(payload){const contracts=payload?.contracts||[],spot=payload?.underlyingPrice||0;return[...new Set(contracts.map(c=>c.dte).filter(Number.isFinite))].sort((a,b)=>a-b).map(dte=>{const b=contracts.filter(c=>c.dte===dte),vals=[nearest(b,spot,'call')?.iv,nearest(b,spot,'put')?.iv].filter(Number.isFinite);return{dte,iv:vals.length?mean(vals)*100:null}}).filter(x=>Number.isFinite(x.iv))}
function groupedStrike(bucket){const map=new Map();for(const c of bucket){if(!Number.isFinite(c.strike))continue;const x=map.get(c.strike)||{strike:c.strike,callOI:0,putOI:0,callVol:0,putVol:0,ivs:[]};if(c.side==='call'){x.callOI+=c.openInterest||0;x.callVol+=c.volume||0}else{x.putOI+=c.openInterest||0;x.putVol+=c.volume||0}if(Number.isFinite(c.iv))x.ivs.push(c.iv);map.set(c.strike,x)}return[...map.values()].map(x=>({...x,iv:x.ivs.length?mean(x.ivs)*100:null})).sort((a,b)=>a.strike-b.strike)}

function Panel({title,sub,children}){return <section className="qaPanel"><div className="qaPanelHead"><div><b>{title}</b><span>{sub}</span></div></div>{children}</section>}

export default function AnalyticsTerminal(){
  const [fn,setFn]=useState('CHAIN'),[symbol,setSymbol]=useState('AAPL'),[query,setQuery]=useState('AAPL'),[payload,setPayload]=useState(null),[candles,setCandles]=useState([]),[dte,setDte]=useState(30),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async(next=symbol)=>{const clean=String(next||'AAPL').trim().toUpperCase();if(!clean)return;setLoading(true);setError('');try{const [oRes,cRes]=await Promise.all([fetch(`/api/options-chain?symbol=${encodeURIComponent(clean)}&dtes=7,14,30,60,90,180&strikeLimit=18`),fetch(`/api/market/candles?symbol=${encodeURIComponent(clean)}&resolution=D&countback=365`)]),o=await oRes.json(),c=await cRes.json();if(!oRes.ok)throw new Error(o.error||'Options data unavailable');if(!cRes.ok)throw new Error(c.error||'Historical data unavailable');setPayload(o);setCandles(c.candles||[]);setSymbol(clean);setQuery(clean);const ds=o.dteBuckets||[...new Set((o.contracts||[]).map(x=>x.dte))];setDte(ds.includes(30)?30:ds[0]??30)}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load('AAPL');try{const p=JSON.parse(sessionStorage.getItem('qnt.analytics.command')||'null');if(p){sessionStorage.removeItem('qnt.analytics.command');if(p.fn)setFn(p.fn);if(p.symbol)load(p.symbol)}}catch{}const h=e=>{const x=e.detail||{};if(x.fn)setFn(x.fn);if(x.symbol)load(x.symbol)};window.addEventListener('qnt:analytics-command',h);return()=>window.removeEventListener('qnt:analytics-command',h)},[]);
  const dtes=useMemo(()=>[...new Set((payload?.contracts||[]).map(c=>c.dte).filter(Number.isFinite))].sort((a,b)=>a-b),[payload]);
  const bucket=useMemo(()=>(payload?.contracts||[]).filter(c=>c.dte===dte),[payload,dte]);
  const spot=payload?.underlyingPrice||candles.at(-1)?.close||0;
  const strikes=useMemo(()=>groupedStrike(bucket),[bucket]);
  const near=useMemo(()=>[...bucket].sort((a,b)=>Math.abs(a.strike-spot)-Math.abs(b.strike-spot)).slice(0,24).sort((a,b)=>a.strike-b.strike||String(a.side).localeCompare(String(b.side))),[bucket,spot]);
  const term=useMemo(()=>atmTerm(payload),[payload]);
  const surface=useMemo(()=>surfaceFrom(payload),[payload]);
  const rv=useMemo(()=>rollingVol(candles,20),[candles]);
  const atmIv=term.find(x=>x.dte===dte)?.iv??term.sort((a,b)=>Math.abs(a.dte-dte)-Math.abs(b.dte-dte))[0]?.iv??null;
  const rv20=rv.at(-1)?.rv??null,rv60=(()=>{const r=dailyReturns(candles).slice(-60).map(x=>x.r);if(r.length<10)return null;const m=mean(r),sd=Math.sqrt(r.reduce((s,v)=>s+(v-m)**2,0)/r.length);return sd*Math.sqrt(252)*100})();
  const rvSeries=useMemo(()=>rv.slice(-100).map(x=>({...x,atm:atmIv})),[rv,atmIv]);
  const oiRows=useMemo(()=>strikes.sort((a,b)=>(b.callOI+b.putOI)-(a.callOI+a.putOI)).slice(0,14).sort((a,b)=>a.strike-b.strike),[strikes]);
  const totalCallOi=bucket.filter(c=>c.side==='call').reduce((s,c)=>s+(c.openInterest||0),0),totalPutOi=bucket.filter(c=>c.side==='put').reduce((s,c)=>s+(c.openInterest||0),0);

  return <div className="qaTerminal"><header className="qaHeader"><div><span>QNT / MARKET ANALYTICS</span><h1>{fn} <small>{symbol} · provider-derived research</small></h1></div><div className="qaSearch"><Search size={12}/><input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} onKeyDown={e=>e.key==='Enter'&&load(query)}/><button onClick={()=>load(query)}><RefreshCw size={11}/>{loading?'SYNC':'GO'}</button></div></header><nav className="qaFunctions">{FUNCTIONS.map(x=><button key={x} className={fn===x?'active':''} onClick={()=>setFn(x)}><kbd>{x}</kbd></button>)}<select value={dte} onChange={e=>setDte(Number(e.target.value))}>{dtes.map(x=><option key={x} value={x}>{x} DTE</option>)}</select></nav>{error&&<div className="qaError">{error} · unavailable values are not replaced with placeholders.</div>}

  <div className="qaMetrics"><div><span>SPOT</span><b>{money(spot)}</b></div><div><span>ATM IV</span><b>{pct(atmIv)}</b></div><div><span>RV20</span><b>{pct(rv20)}</b></div><div><span>IV − RV20</span><b>{Number.isFinite(atmIv)&&Number.isFinite(rv20)?`${(atmIv-rv20)>=0?'+':''}${(atmIv-rv20).toFixed(1)} vol`:'—'}</b></div><div><span>PUT/CALL OI</span><b>{totalCallOi?(totalPutOi/totalCallOi).toFixed(2):'—'}</b></div><div><span>CONTRACTS</span><b>{bucket.length}</b></div></div>

  {fn==='CHAIN'&&<Panel title={`${symbol} OPTION CHAIN`} sub={`${dte} DTE · nearest contracts around spot`}><div className="qaTable chain"><div className="head"><span>SIDE</span><span>STRIKE</span><span>BID</span><span>ASK</span><span>IV</span><span>DELTA</span><span>GAMMA</span><span>THETA</span><span>VEGA</span><span>VOL</span><span>OI</span></div>{near.map((c,i)=><div key={`${c.optionSymbol||i}-${c.side}`}><span className={c.side}>{String(c.side).toUpperCase()}</span><span>{money(c.strike)}</span><span>{money(c.bid)}</span><span>{money(c.ask)}</span><span>{Number.isFinite(c.iv)?`${(c.iv*100).toFixed(1)}%`:'—'}</span><span>{num(c.delta,3)}</span><span>{num(c.gamma,4)}</span><span>{num(c.theta,3)}</span><span>{num(c.vega,3)}</span><span>{(c.volume||0).toLocaleString()}</span><span>{(c.openInterest||0).toLocaleString()}</span></div>)}</div></Panel>}

  {fn==='SURF'&&<Panel title={`${symbol} 3D IMPLIED VOLATILITY SURFACE`} sub="DTE × moneyness × implied volatility"><div className="qaSurface"><InteractiveSurface3D surface={surface} moneynessLevels={MONEYNESS}/></div></Panel>}

  {fn==='SKEW'&&<Panel title={`${symbol} IV SMILE / SKEW`} sub={`${dte} DTE · blended call/put IV by strike`}><ResponsiveContainer width="100%" height={470}><LineChart data={strikes.filter(x=>Number.isFinite(x.iv))}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="strike" tick={{fontSize:8}} stroke="#515761"/><YAxis domain={['auto','auto']} tick={{fontSize:8}} stroke="#515761" tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Line dataKey="iv" type="monotone" dot={false} stroke="#a58cff" strokeWidth={1.5}/></LineChart></ResponsiveContainer></Panel>}

  {fn==='TERM'&&<Panel title={`${symbol} ATM IV TERM STRUCTURE`} sub="nearest-ATM blended IV across expirations"><ResponsiveContainer width="100%" height={470}><LineChart data={term}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="dte" tick={{fontSize:8}} stroke="#515761"/><YAxis domain={['auto','auto']} tick={{fontSize:8}} stroke="#515761" tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Line dataKey="iv" type="monotone" stroke="#a58cff" strokeWidth={1.5}/></LineChart></ResponsiveContainer></Panel>}

  {fn==='RVIV'&&<Panel title={`${symbol} IMPLIED VS REALIZED VOL`} sub="ATM IV compared with rolling 20-session realized volatility"><div className="qaRvTop"><div><span>ATM IV</span><b>{pct(atmIv)}</b></div><div><span>RV20</span><b>{pct(rv20)}</b></div><div><span>RV60</span><b>{pct(rv60)}</b></div><div><span>IV-RV20</span><b>{Number.isFinite(atmIv)&&Number.isFinite(rv20)?`${(atmIv-rv20).toFixed(1)} vol`:'—'}</b></div></div><ResponsiveContainer width="100%" height={410}><LineChart data={rvSeries}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="label" minTickGap={42} tick={{fontSize:8}} stroke="#515761"/><YAxis domain={['auto','auto']} tick={{fontSize:8}} stroke="#515761" tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Legend wrapperStyle={{fontSize:8}}/><Line name="RV20" dataKey="rv" dot={false} stroke="#a58cff" strokeWidth={1.4}/><Line name={`ATM IV (${dte}D)`} dataKey="atm" dot={false} stroke="#7b818b" strokeDasharray="4 4"/></LineChart></ResponsiveContainer></Panel>}

  {fn==='GREEKS'&&<Panel title={`${symbol} GREEKS MATRIX`} sub={`${dte} DTE · provider-returned contract Greeks`}><div className="qaTable greeks"><div className="head"><span>SIDE</span><span>STRIKE</span><span>IV</span><span>DELTA</span><span>GAMMA</span><span>THETA</span><span>VEGA</span><span>OI</span></div>{near.map((c,i)=><div key={`g-${c.optionSymbol||i}`}><span className={c.side}>{String(c.side).toUpperCase()}</span><span>{money(c.strike)}</span><span>{Number.isFinite(c.iv)?`${(c.iv*100).toFixed(1)}%`:'—'}</span><span>{num(c.delta,3)}</span><span>{num(c.gamma,4)}</span><span>{num(c.theta,3)}</span><span>{num(c.vega,3)}</span><span>{(c.openInterest||0).toLocaleString()}</span></div>)}</div><p className="qaFoot">These are contract-level Greeks returned by the provider. QNT does not label aggregated open interest as dealer positioning.</p></Panel>}

  {fn==='OI'&&<Panel title={`${symbol} OI / VOLUME CONCENTRATION`} sub={`${dte} DTE · top open-interest strikes`}><ResponsiveContainer width="100%" height={430}><BarChart data={oiRows}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="strike" tick={{fontSize:8}} stroke="#515761"/><YAxis tick={{fontSize:8}} stroke="#515761"/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Legend wrapperStyle={{fontSize:8}}/><Bar name="Call OI" dataKey="callOI" fill="#9e78ff"/><Bar name="Put OI" dataKey="putOI" fill="#5e6470"/></BarChart></ResponsiveContainer><div className="qaOiTable">{oiRows.map(r=><div key={r.strike}><b>{money(r.strike)}</b><span>Call OI {(r.callOI||0).toLocaleString()}</span><span>Put OI {(r.putOI||0).toLocaleString()}</span><span>Call vol {(r.callVol||0).toLocaleString()}</span><span>Put vol {(r.putVol||0).toLocaleString()}</span></div>)}</div><p className="qaFoot">This is open-interest and volume concentration from the returned chain, not trade-by-trade options flow.</p></Panel>}
  </div>
}
