import React, { useEffect, useMemo, useState } from 'react';
import {
  ArrowDown, ArrowUp, EyeOff, LineChart as LineIcon, RefreshCw, RotateCcw, Search,
} from 'lucide-react';
import {
  Area, AreaChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts';

const WATCH = ['QQQ', 'SPY', 'AAPL', 'NVDA', 'MSFT'];
const FUNCTIONS = ['LAUNCH', 'DES', 'CHART', 'CORR', 'OMON'];
const PANELS = ['market', 'chart', 'corr', 'options', 'system'];
const DEFAULT_LAYOUT = ['market', 'chart', 'corr', 'options', 'system'];
const money = n => Number.isFinite(Number(n)) ? `$${Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';
const pct = n => Number.isFinite(Number(n)) ? `${Number(n) >= 0 ? '+' : ''}${Number(n).toFixed(2)}%` : '—';
const fmtDate = t => t ? new Date(Number(t) * 1000).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: '2-digit' }) : '—';
const mean = a => a.length ? a.reduce((s, v) => s + v, 0) / a.length : 0;

function dailyReturns(candles = []) { const out = []; for (let i = 1; i < candles.length; i++) { const a = candles[i - 1]?.close, b = candles[i]?.close; if (a > 0 && Number.isFinite(b)) out.push({ time: candles[i].time, value: (b - a) / a }); } return out; }
function pearson(a, b) { if (a.length !== b.length || a.length < 3) return null; const ma = mean(a), mb = mean(b); let num = 0, da = 0, db = 0; for (let i = 0; i < a.length; i++) { const x = a[i] - ma, y = b[i] - mb; num += x * y; da += x * x; db += y * y; } const den = Math.sqrt(da * db); return den ? num / den : null; }
function correlation(a = [], b = []) { const bm = new Map(dailyReturns(b).map(x => [x.time, x.value])), pairs = dailyReturns(a).filter(x => bm.has(x.time)); return pearson(pairs.map(x => x.value), pairs.map(x => bm.get(x.time))); }
function realizedVol(candles = [], lookback = 20) { const r = dailyReturns(candles).slice(-lookback).map(x => x.value); if (r.length < 3) return null; const m = mean(r), sd = Math.sqrt(mean(r.map(x => (x - m) ** 2))); return sd * Math.sqrt(252) * 100; }
function periodReturn(candles = [], days = 20) { if (candles.length < 2) return null; const end = candles.at(-1)?.close, start = candles[Math.max(0, candles.length - 1 - days)]?.close; return start > 0 && Number.isFinite(end) ? (end / start - 1) * 100 : null; }
function maxDrawdown(candles = []) { let peak = -Infinity, dd = 0; for (const c of candles) { if (!Number.isFinite(c.close)) continue; peak = Math.max(peak, c.close); if (peak > 0) dd = Math.max(dd, (peak - c.close) / peak); } return dd * 100; }
function mid(c) { if (!c) return null; if (Number.isFinite(c.mid)) return c.mid; if (Number.isFinite(c.bid) && Number.isFinite(c.ask)) return (c.bid + c.ask) / 2; if (Number.isFinite(c.last)) return c.last; return null; }
function nearest(contracts = [], target, side) { const rows = contracts.filter(c => (!side || c.side === side) && Number.isFinite(c.strike)); return rows.sort((a, b) => Math.abs(a.strike - target) - Math.abs(b.strike - target))[0] || null; }
function optionSummary(payload) { const contracts = payload?.contracts || [], spot = payload?.underlyingPrice || 0, dtes = [...new Set(contracts.map(c => c.dte).filter(Number.isFinite))].sort((a, b) => a - b); return dtes.map(dte => { const bucket = contracts.filter(c => c.dte === dte), call = nearest(bucket, spot, 'call'), put = nearest(bucket, spot, 'put'), callMid = mid(call), putMid = mid(put), atm = [call?.iv, put?.iv].filter(Number.isFinite), puts = bucket.filter(c => c.side === 'put'), calls = bucket.filter(c => c.side === 'call'), putWing = nearest(puts, spot * .9, 'put'), callWing = nearest(calls, spot * 1.1, 'call'); return { dte, expiration: bucket.find(c => c.expiration)?.expiration, atmIv: atm.length ? mean(atm) * 100 : null, skew: Number.isFinite(putWing?.iv) && Number.isFinite(callWing?.iv) ? (putWing.iv - callWing.iv) * 100 : null, callOi: calls.reduce((s, c) => s + (c.openInterest || 0), 0), putOi: puts.reduce((s, c) => s + (c.openInterest || 0), 0), volume: bucket.reduce((s, c) => s + (c.volume || 0), 0), expectedMove: Number.isFinite(callMid) && Number.isFinite(putMid) ? callMid + putMid : null }; }); }

function MiniSpark({ candles = [] }) { const vals = candles.slice(-30).map(x => x.close).filter(Number.isFinite); if (vals.length < 2) return <div className="bdEmptyMini">NO SERIES</div>; const lo = Math.min(...vals), hi = Math.max(...vals), span = hi - lo || 1, pts = vals.map((v, i) => `${i / (vals.length - 1) * 100},${34 - (v - lo) / span * 30}`).join(' '); return <svg className="bdSpark" viewBox="0 0 100 38" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="1.2"/></svg>; }
function Panel({ title, sub, children, actions }) { return <section className="bdPanel"><div className="bdPanelHead"><div><b>{title}</b><span>{sub}</span></div>{actions}</div>{children}</section>; }

export default function BloombergDesk() {
  const savedSymbol = (() => { try { return localStorage.getItem('qnt.active.symbol') || 'QQQ'; } catch { return 'QQQ'; } })();
  const [fn, setFn] = useState('LAUNCH'), [symbol, setSymbol] = useState(savedSymbol), [query, setQuery] = useState(savedSymbol);
  const [quotes, setQuotes] = useState([]), [histories, setHistories] = useState({}), [detail, setDetail] = useState([]), [options, setOptions] = useState(null), [health, setHealth] = useState(null);
  const [loading, setLoading] = useState(false), [error, setError] = useState('');
  const [compare, setCompare] = useState(['QQQ', 'SPY', 'NVDA']);
  const [layout, setLayout] = useState(() => { try { const saved = JSON.parse(localStorage.getItem('qnt.launchpad.layout') || 'null'); const clean = Array.isArray(saved) ? saved.filter(x => PANELS.includes(x)) : []; return clean.length ? clean : DEFAULT_LAYOUT; } catch { return DEFAULT_LAYOUT; } });

  const loadBase = async () => { setLoading(true); setError(''); try { const [qRes, hRes, ...cRes] = await Promise.all([fetch(`/api/market/quotes?symbols=${WATCH.join(',')}`), fetch('/api/status'), ...WATCH.map(s => fetch(`/api/market/candles?symbol=${s}&resolution=D&countback=140`))]); const q = await qRes.json(), h = await hRes.json(); if (qRes.ok) setQuotes(q.quotes || []); setHealth(h); const next = {}; for (let i = 0; i < cRes.length; i++) { const d = await cRes[i].json(); if (cRes[i].ok) next[WATCH[i]] = d.candles || []; } setHistories(next); if (!qRes.ok) setError(q.error || 'Watchlist quote request failed'); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const loadDetail = async (next = symbol) => { const clean = String(next || 'QQQ').trim().toUpperCase(); if (!clean) return; setQuery(clean); setSymbol(clean); try { localStorage.setItem('qnt.active.symbol', clean); } catch {} try { const r = await fetch(`/api/market/candles?symbol=${encodeURIComponent(clean)}&resolution=D&countback=365`), d = await r.json(); if (!r.ok) throw new Error(d.error || 'History request failed'); setDetail(d.candles || []); } catch (e) { setError(e.message); } };
  const loadOptions = async () => { try { const r = await fetch(`/api/options-chain?symbol=${encodeURIComponent(symbol)}&dtes=7,14,30,60,90,180&strikeLimit=14`), d = await r.json(); if (!r.ok) throw new Error(d.error || 'Option chain unavailable'); setOptions(d); } catch (e) { setOptions(null); setError(e.message); } };
  const routeAnalytics = (nextFn, nextDte) => window.dispatchEvent(new CustomEvent('qnt:route', { detail: { section: 'Analytics', fn: nextFn, symbol, dte: nextDte } }));

  useEffect(() => {
    let pending = null;
    try { pending = JSON.parse(sessionStorage.getItem('qnt.desk.command') || 'null'); if (pending) sessionStorage.removeItem('qnt.desk.command'); } catch {}
    const firstSymbol = pending?.symbol || savedSymbol;
    if (pending?.fn) setFn(pending.fn);
    if (Array.isArray(pending?.symbols) && pending.symbols.length) setCompare(pending.symbols);
    loadBase();
    loadDetail(firstSymbol);
    const handler = e => { const d = e.detail || {}; if (d.fn) setFn(d.fn); if (d.symbol) loadDetail(d.symbol); if (Array.isArray(d.symbols) && d.symbols.length) setCompare(d.symbols); };
    window.addEventListener('qnt:desk-command', handler);
    return () => window.removeEventListener('qnt:desk-command', handler);
  }, []);
  useEffect(() => { if (['OMON', 'LAUNCH'].includes(fn)) loadOptions(); }, [fn, symbol]);
  useEffect(() => { try { localStorage.setItem('qnt.launchpad.layout', JSON.stringify(layout)); } catch {} }, [layout]);

  const quote = quotes.find(q => q.symbol === symbol), candles = detail.length ? detail : (histories[symbol] || []);
  const security = useMemo(() => { const vols = candles.slice(-20).map(c => c.volume).filter(Number.isFinite), high = Math.max(...candles.slice(-20).map(c => c.high ?? c.close).filter(Number.isFinite), 0), lowVals = candles.slice(-20).map(c => c.low ?? c.close).filter(Number.isFinite), low = lowVals.length ? Math.min(...lowVals) : null; return { r1: periodReturn(candles, 1), r5: periodReturn(candles, 5), r20: periodReturn(candles, 20), r60: periodReturn(candles, 60), rv20: realizedVol(candles, 20), rv60: realizedVol(candles, 60), dd: maxDrawdown(candles), high, low, avgVol: mean(vols), corrSpy: symbol === 'SPY' ? 1 : correlation(candles, histories.SPY || []) }; }, [candles, histories, symbol]);
  const corrMatrix = useMemo(() => WATCH.map(a => WATCH.map(b => a === b ? 1 : correlation(histories[a] || [], histories[b] || []))), [histories]);
  const normalized = useMemo(() => { const maps = compare.map(s => new Map((histories[s] || []).map(c => [c.time, c.close]))), times = [...new Set(compare.flatMap(s => (histories[s] || []).map(c => c.time)))].sort((a, b) => a - b), base = {}; for (const s of compare) { const first = (histories[s] || []).find(c => Number.isFinite(c.close))?.close; if (first) base[s] = first; } return times.map(time => { const row = { time, label: fmtDate(time) }; compare.forEach((s, i) => { const v = maps[i].get(time); if (Number.isFinite(v) && base[s]) row[s] = v / base[s] * 100; }); return row; }).slice(-100); }, [compare, histories]);
  const optionRows = useMemo(() => optionSummary(options), [options]);

  const movePanel = (id, dir) => setLayout(cur => { const i = cur.indexOf(id), j = i + dir; if (i < 0 || j < 0 || j >= cur.length) return cur; const n = [...cur]; [n[i], n[j]] = [n[j], n[i]]; return n; });
  const hidePanel = id => setLayout(cur => cur.filter(x => x !== id));
  const resetLayout = () => setLayout(DEFAULT_LAYOUT);
  const addPanel = id => setLayout(cur => cur.includes(id) ? cur : [...cur, id]);

  const launchContent = {
    market: <Panel title="WATCHLIST MONITOR" sub="provider-backed quotes + 30-session history"><div className="bdWatchRows">{WATCH.map(s => { const q = quotes.find(x => x.symbol === s), h = histories[s] || []; return <button key={s} onClick={() => { loadDetail(s); setFn('DES'); }}><b>{s}</b><span>{money(q?.last ?? h.at(-1)?.close)}</span><em className={(q?.changePct ?? 0) >= 0 ? 'up' : 'down'}>{pct(q?.changePct)}</em><MiniSpark candles={h}/></button>; })}</div></Panel>,
    chart: <Panel title="RELATIVE PERFORMANCE" sub="watchlist normalized to 100"><ResponsiveContainer width="100%" height={210}><LineChart data={normalized}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="label" minTickGap={45} tick={{ fontSize: 7 }} stroke="#515761"/><YAxis domain={['auto', 'auto']} tick={{ fontSize: 7 }} stroke="#515761"/><Tooltip contentStyle={{ background: '#07080b', border: '1px solid #34303f', fontSize: 9 }}/><Legend wrapperStyle={{ fontSize: 8 }}/>{compare.map(s => <Line key={s} dataKey={s} type="monotone" dot={false} strokeWidth={1.15}/>)}</LineChart></ResponsiveContainer></Panel>,
    corr: <Panel title="CORRELATION MATRIX" sub="aligned daily returns"><div className="bdCorrMini"><span/>{WATCH.map(s => <b key={s}>{s}</b>)}{WATCH.flatMap((a, ri) => [<b key={`r-${a}`}>{a}</b>, ...WATCH.map((b, ci) => <span key={`${a}-${b}`} data-heat={Math.abs(corrMatrix[ri]?.[ci] ?? 0) > .75 ? 'hot' : Math.abs(corrMatrix[ri]?.[ci] ?? 0) > .4 ? 'mid' : 'low'}>{Number.isFinite(corrMatrix[ri]?.[ci]) ? corrMatrix[ri][ci].toFixed(2) : '—'}</span>)])}</div></Panel>,
    options: <Panel title={`${symbol} OPTIONS SNAPSHOT`} sub="IV / skew / OI by expiration">{optionRows.length ? <div className="bdCompactTable"><div className="head"><span>DTE</span><span>ATM IV</span><span>SKEW</span><span>PUT/CALL OI</span><span>MOVE</span></div>{optionRows.slice(0, 5).map(r => <div key={r.dte} onClick={() => routeAnalytics('CHAIN', r.dte)} title={`Open ${symbol} ${r.dte}D chain`} style={{ cursor: 'pointer' }}><span>{r.dte}</span><span>{r.atmIv?.toFixed(1) ?? '—'}%</span><span>{r.skew?.toFixed(1) ?? '—'}v</span><span>{r.callOi ? (r.putOi / r.callOi).toFixed(2) : '—'}</span><span>{money(r.expectedMove)}</span></div>)}</div> : <div className="bdEmptyMini">OPTIONS DATA UNAVAILABLE</div>}</Panel>,
    system: <Panel title="SYSTEM / DATA HEALTH" sub="server-side credentials and cache"><div className="bdSystemMini"><div><span>SERVER</span><b>{health?.server?.ok ? 'ONLINE' : '—'}</b></div><div><span>MARKETDATA</span><b>{health?.marketData?.configured ? 'CONNECTED' : 'OFFLINE'}</b></div><div><span>OPENAI</span><b>{health?.openai?.configured ? 'CONNECTED' : 'OFFLINE'}</b></div><div><span>CACHE</span><b>{health?.server?.cacheEntries ?? 0}</b></div></div></Panel>,
  };

  const renderLaunch = () => <><div className="bdLaunchToolbar"><span>SAVED DESK · local layout</span><button onClick={resetLayout}><RotateCcw size={11}/> RESET</button>{PANELS.filter(x => !layout.includes(x)).map(x => <button key={x} onClick={() => addPanel(x)}>+ {x.toUpperCase()}</button>)}</div><div className="bdLaunchGrid">{layout.map((id, i) => <div className="bdLaunchItem" key={id}><div className="bdPanelControls"><button disabled={i === 0} onClick={() => movePanel(id, -1)}><ArrowUp size={10}/></button><button disabled={i === layout.length - 1} onClick={() => movePanel(id, 1)}><ArrowDown size={10}/></button><button onClick={() => hidePanel(id)}><EyeOff size={10}/></button></div>{launchContent[id]}</div>)}</div></>;

  return <div className="bdDesk">
    <header className="bdHeader"><div><span>QNT / FUNCTION TERMINAL</span><h1>{fn} <small>{fn === 'DES' ? `${symbol} SECURITY` : fn === 'OMON' ? `${symbol} OPTIONS` : fn}</small></h1></div><div className="bdHeaderActions"><div className="bdSymbolSearch"><Search size={12}/><input value={query} onChange={e => setQuery(e.target.value.toUpperCase())} onKeyDown={e => e.key === 'Enter' && loadDetail(query)}/><button onClick={() => loadDetail(query)}>GO</button></div><button onClick={() => { loadBase(); loadDetail(symbol); if (['OMON', 'LAUNCH'].includes(fn)) loadOptions(); }}><RefreshCw size={11}/>{loading ? 'SYNCING' : 'SYNC'}</button></div></header>
    <nav className="bdFunctions">{FUNCTIONS.map(x => <button key={x} className={fn === x ? 'active' : ''} onClick={() => setFn(x)}><kbd>{x}</kbd></button>)}</nav>
    {error && <div className="bdError">{error}</div>}
    {fn === 'LAUNCH' && renderLaunch()}
    {fn === 'DES' && <div className="bdToolGrid"><Panel title={`${symbol} SECURITY MASTER`} sub="price, returns, volatility, drawdown and relationship stats"><div className="bdMetricGrid"><div><span>LAST</span><b>{money(quote?.last ?? candles.at(-1)?.close)}</b></div><div><span>1D</span><b>{pct(security.r1)}</b></div><div><span>5D</span><b>{pct(security.r5)}</b></div><div><span>20D</span><b>{pct(security.r20)}</b></div><div><span>60D</span><b>{pct(security.r60)}</b></div><div><span>20D RV</span><b>{Number.isFinite(security.rv20) ? `${security.rv20.toFixed(1)}%` : '—'}</b></div><div><span>60D RV</span><b>{Number.isFinite(security.rv60) ? `${security.rv60.toFixed(1)}%` : '—'}</b></div><div><span>MAX DD*</span><b>{security.dd.toFixed(1)}%</b></div><div><span>20D RANGE</span><b>{security.low ? `${money(security.low)}–${money(security.high)}` : '—'}</b></div><div><span>AVG 20D VOL</span><b>{security.avgVol ? Math.round(security.avgVol).toLocaleString() : '—'}</b></div><div><span>CORR SPY</span><b>{Number.isFinite(security.corrSpy) ? security.corrSpy.toFixed(3) : '—'}</b></div><div><span>DATA POINTS</span><b>{candles.length}</b></div></div><div className="bdCorrNotes"><p>*Max drawdown is calculated over the loaded historical sample.</p><div><button onClick={() => { setFn('OMON'); loadOptions(); }}>OMON</button><button onClick={() => routeAnalytics('RVIV', 30)}>RVIV</button><button onClick={() => routeAnalytics('SURF', 30)}>SURF</button></div></div></Panel><Panel title={`${symbol} · 1Y HISTORY`} sub="daily close"><ResponsiveContainer width="100%" height={350}><AreaChart data={candles.map(c => ({ ...c, label: fmtDate(c.time) }))}><defs><linearGradient id="bdA" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9e7aff" stopOpacity=".32"/><stop offset="100%" stopColor="#9e7aff" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="label" minTickGap={50} tick={{ fontSize: 7 }} stroke="#515761"/><YAxis domain={['auto', 'auto']} tick={{ fontSize: 7 }} stroke="#515761"/><Tooltip contentStyle={{ background: '#07080b', border: '1px solid #34303f', fontSize: 9 }}/><Area dataKey="close" type="monotone" stroke="#a58cff" fill="url(#bdA)" strokeWidth={1.25}/></AreaChart></ResponsiveContainer></Panel></div>}
    {fn === 'CHART' && <div className="bdToolGrid one"><Panel title="MULTI-ASSET CHART WORKSTATION" sub="normalized relative performance · daily provider history" actions={<div className="bdCompareSelect">{WATCH.map(s => <label key={s}><input type="checkbox" checked={compare.includes(s)} onChange={() => setCompare(cur => cur.includes(s) ? cur.filter(x => x !== s) : [...cur, s].slice(-4))}/>{s}</label>)}</div>}><ResponsiveContainer width="100%" height={520}><LineChart data={normalized}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="label" minTickGap={50} tick={{ fontSize: 7 }} stroke="#515761"/><YAxis domain={['auto', 'auto']} tick={{ fontSize: 7 }} stroke="#515761"/><Tooltip contentStyle={{ background: '#07080b', border: '1px solid #34303f', fontSize: 9 }}/><Legend wrapperStyle={{ fontSize: 9 }}/>{compare.map(s => <Line key={s} dataKey={s} type="monotone" dot={false} strokeWidth={1.5}/>)}</LineChart></ResponsiveContainer><div className="bdChartStats">{compare.map(s => <div key={s}><b>{s}</b><span>20D {pct(periodReturn(histories[s] || [], 20))}</span><span>RV20 {realizedVol(histories[s] || [], 20)?.toFixed(1) ?? '—'}%</span><span>DD {maxDrawdown(histories[s] || []).toFixed(1)}%</span></div>)}</div></Panel></div>}
    {fn === 'CORR' && <div className="bdToolGrid one"><Panel title="RETURN CORRELATION MATRIX" sub="daily close-to-close returns · aligned dates"><div className="bdCorrFull"><span/>{WATCH.map(s => <b key={s}>{s}</b>)}{WATCH.flatMap((a, ri) => [<b key={`row-${a}`}>{a}</b>, ...WATCH.map((b, ci) => { const v = corrMatrix[ri]?.[ci]; return <span key={`${a}-${b}`} data-heat={Math.abs(v ?? 0) > .75 ? 'hot' : Math.abs(v ?? 0) > .4 ? 'mid' : 'low'}>{Number.isFinite(v) ? v.toFixed(3) : '—'}</span>; })])}</div><div className="bdCorrNotes"><p>Correlation is computed from aligned daily percentage returns, not price levels.</p><button onClick={() => setFn('CHART')}><LineIcon size={11}/> OPEN RELATIVE CHART</button></div></Panel></div>}
    {fn === 'OMON' && <div className="bdToolGrid one"><Panel title={`${symbol} OPTIONS MONITOR`} sub={`${options?.source || 'provider chain'} · ${options?.updated ? new Date(options.updated).toLocaleString() : '—'}`}><div className="bdOptionTop"><div><span>SPOT</span><b>{money(options?.underlyingPrice)}</b></div><div><span>EXPIRATIONS</span><b>{optionRows.length}</b></div><div><span>CONTRACTS</span><b>{options?.contracts?.length ?? 0}</b></div><div><span>TOTAL OI</span><b>{(options?.contracts || []).reduce((s, c) => s + (c.openInterest || 0), 0).toLocaleString()}</b></div><div><span>DAY VOLUME</span><b>{(options?.contracts || []).reduce((s, c) => s + (c.volume || 0), 0).toLocaleString()}</b></div></div><div className="bdOptionTable"><div className="head"><span>EXP</span><span>DTE</span><span>ATM IV</span><span>10% SKEW</span><span>CALL OI</span><span>PUT OI</span><span>P/C OI</span><span>VOLUME</span><span>ATM MOVE*</span></div>{optionRows.map(r => <div key={r.dte} onClick={() => routeAnalytics('CHAIN', r.dte)} title={`Open ${symbol} ${r.dte}D chain`} style={{ cursor: 'pointer' }}><span>{fmtDate(r.expiration)}</span><span>{r.dte}</span><span>{r.atmIv?.toFixed(2) ?? '—'}%</span><span>{r.skew?.toFixed(2) ?? '—'}v</span><span>{r.callOi.toLocaleString()}</span><span>{r.putOi.toLocaleString()}</span><span>{r.callOi ? (r.putOi / r.callOi).toFixed(2) : '—'}</span><span>{r.volume.toLocaleString()}</span><span>{money(r.expectedMove)}</span></div>)}</div><div className="bdCorrNotes"><p>*ATM move is the near-ATM call + put midpoint when both quotes exist. Click any expiration to drill into its chain.</p><div><button onClick={() => routeAnalytics('CHAIN', 30)}>CHAIN</button><button onClick={() => routeAnalytics('SURF', 30)}>SURF</button><button onClick={() => routeAnalytics('SKEW', 30)}>SKEW</button><button onClick={() => routeAnalytics('TERM', 30)}>TERM</button><button onClick={() => routeAnalytics('OI', 30)}>OI</button></div></div></Panel></div>}
  </div>;
}
