import React,{useEffect,useMemo,useRef,useState}from'react';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
function rotatePoint(p,yaw,pitch){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x1=p.x*cy-p.z*sy,z1=p.x*sy+p.z*cy,y1=p.y*cp-z1*sp,z2=p.y*sp+z1*cp;return{x:x1,y:y1,z:z2}}
function plasma(t){const stops=[[55,20,95],[106,35,160],[189,54,161],[246,104,91],[253,185,65],[247,239,123]],x=clamp(t,0,1)*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),f=x-i,a=stops[i],b=stops[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
function smoothSurfaceRows(rows){
  const raw=Array.isArray(rows)?rows.filter(r=>Array.isArray(r)&&r.length>1):[];if(raw.length<2)return raw;
  const cols=Math.min(...raw.map(r=>r.length));if(cols<2)return raw;
  const tx=Math.min(28,Math.max(raw.length,raw.length*5)),tz=Math.min(36,Math.max(cols,cols*4));
  const valueAt=(key,gx,gz,positive=false)=>{const x0=Math.floor(gx),x1=Math.min(raw.length-1,x0+1),z0=Math.floor(gz),z1=Math.min(cols-1,z0+1),fx=gx-x0,fz=gz-z0,corners=[Number(raw[x0]?.[z0]?.[key]),Number(raw[x1]?.[z0]?.[key]),Number(raw[x0]?.[z1]?.[key]),Number(raw[x1]?.[z1]?.[key])],valid=corners.filter(v=>Number.isFinite(v)&&(!positive||v>0));if(valid.length<4)return valid[0]??null;return lerp(lerp(corners[0],corners[1],fx),lerp(corners[2],corners[3],fx),fz)};
  return Array.from({length:tx},(_,xi)=>Array.from({length:tz},(_,zi)=>{const gx=xi/(tx-1)*(raw.length-1),gz=zi/(tz-1)*(cols-1);return{iv:valueAt('iv',gx,gz,true),dte:valueAt('dte',gx,gz),strike:valueAt('strike',gx,gz),moneyness:valueAt('moneyness',gx,gz)}}));
}

export default function InteractiveSurface3D({surface,moneynessLevels}){
  const canvasRef=useRef(null),projectedRef=useRef([]),drawRef=useRef(null),frameRef=useRef(0),inertiaRef=useRef(0),hoverFrameRef=useRef(0),dragRef=useRef(null),viewRef=useRef({yaw:-.72,pitch:.58,zoom:1}),velocityRef=useRef({yaw:0,pitch:0});
  const[hover,setHover]=useState(null);
  const mesh=useMemo(()=>{const rows=smoothSurfaceRows(surface?.rows||[]),vals=rows.flat().map(p=>Number(p.iv)).filter(v=>Number.isFinite(v)&&v>0),min=vals.length?Math.min(...vals):.15,max=vals.length?Math.max(...vals):.45,span=max-min||1,points=rows.map((row,xi)=>row.map((p,zi)=>({x:(xi-(rows.length-1)/2)*(14/Math.max(1,rows.length-1)),y:Number.isFinite(p.iv)&&p.iv>0?-((p.iv-min)/span)*2.6:0,z:(zi-(row.length-1)/2)*(10/Math.max(1,row.length-1)),iv:Number(p.iv),dte:p.dte,strike:p.strike,moneyness:p.moneyness})));return{points,min,max}},[surface]);
  const scheduleDraw=()=>{if(frameRef.current)return;frameRef.current=requestAnimationFrame(()=>{frameRef.current=0;drawRef.current?.()})};
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;const draw=()=>{const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const{yaw,pitch,zoom}=viewRef.current;ctx.setTransform(canvas.width/w,0,0,canvas.height/h,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#08090a';ctx.fillRect(0,0,w,h);const project=p=>{const r=rotatePoint(p,yaw,pitch),depth=8+r.z,scale=(148*zoom)/Math.max(3.9,depth);return{x:w/2+r.x*scale,y:h/2+r.y*scale+14,z:r.z}};const gridBottom=h*.84;ctx.lineWidth=.6;ctx.strokeStyle='rgba(117,119,132,.10)';for(let i=0;i<9;i++){const y=h*.13+i*(gridBottom-h*.13)/8;ctx.beginPath();ctx.moveTo(w*.055,y);ctx.lineTo(w*.95,y);ctx.stroke()}for(let i=0;i<11;i++){const x=w*.055+i*(w*.895)/10;ctx.beginPath();ctx.moveTo(x,h*.13);ctx.lineTo(x,gridBottom);ctx.stroke()}const faces=[],projected=[];for(let x=0;x<mesh.points.length;x++){projected[x]=[];for(let z=0;z<(mesh.points[x]?.length||0);z++){const q=project(mesh.points[x][z]);projected[x][z]={...q,...mesh.points[x][z]}}}for(let x=0;x<mesh.points.length-1;x++)for(let z=0;z<(mesh.points[x]?.length||0)-1;z++){const raw=[mesh.points[x][z],mesh.points[x+1][z],mesh.points[x+1][z+1],mesh.points[x][z+1]];if(raw.some(p=>!Number.isFinite(p.iv)||p.iv<=0))continue;const pts=raw.map(project);faces.push({pts,depth:pts.reduce((s,p)=>s+p.z,0)/4,iv:raw.reduce((s,p)=>s+p.iv,0)/4})}faces.sort((a,b)=>a.depth-b.depth);for(const face of faces){const t=clamp((face.iv-mesh.min)/(mesh.max-mesh.min||1),0,1);ctx.beginPath();ctx.moveTo(face.pts[0].x,face.pts[0].y);for(let i=1;i<4;i++)ctx.lineTo(face.pts[i].x,face.pts[i].y);ctx.closePath();ctx.globalAlpha=.94;ctx.fillStyle=plasma(t);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=.34;ctx.stroke()}projectedRef.current=projected.flat().filter(p=>Number.isFinite(p.iv)&&p.iv>0);ctx.fillStyle='#8a8f99';ctx.font='9px ui-monospace,monospace';ctx.fillText('IV ↑',12,18);ctx.fillText('DTE →',w-55,h-13);ctx.fillText('MONEYNESS',12,h-13);if(surface?.dtes?.length){ctx.fillStyle='#5d626b';ctx.fillText(`${surface.dtes[0]}d`,w*.61,h-29);ctx.fillText(`${surface.dtes.at(-1)}d`,w*.82,h-51)}if(moneynessLevels?.length){ctx.fillText(`${Math.round(moneynessLevels[0]*100)}%`,w*.08,h-40);ctx.fillText(`${Math.round(moneynessLevels.at(-1)*100)}%`,w*.25,h-76)}};drawRef.current=draw;const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));scheduleDraw()};const ro=new ResizeObserver(resize);ro.observe(canvas);resize();return()=>{ro.disconnect();drawRef.current=null;if(frameRef.current)cancelAnimationFrame(frameRef.current);if(inertiaRef.current)cancelAnimationFrame(inertiaRef.current);if(hoverFrameRef.current)cancelAnimationFrame(hoverFrameRef.current)}},[mesh,surface,moneynessLevels]);
  const startInertia=()=>{if(inertiaRef.current)cancelAnimationFrame(inertiaRef.current);const tick=()=>{const v=velocityRef.current;v.yaw*=.91;v.pitch*=.91;if(Math.abs(v.yaw)+Math.abs(v.pitch)<.00035){inertiaRef.current=0;return}viewRef.current.yaw+=v.yaw;viewRef.current.pitch=clamp(viewRef.current.pitch+v.pitch,-.18,1.15);scheduleDraw();inertiaRef.current=requestAnimationFrame(tick)};inertiaRef.current=requestAnimationFrame(tick)};
  const down=e=>{if(inertiaRef.current){cancelAnimationFrame(inertiaRef.current);inertiaRef.current=0}dragRef.current={x:e.clientX,y:e.clientY,t:performance.now()};velocityRef.current={yaw:0,pitch:0};canvasRef.current?.setPointerCapture?.(e.pointerId)};
  const move=e=>{const drag=dragRef.current;if(drag){const now=performance.now(),dt=Math.max(8,now-drag.t),dx=e.clientX-drag.x,dy=e.clientY-drag.y,dyaw=dx*.0072,dpitch=dy*.0072;viewRef.current.yaw+=dyaw;viewRef.current.pitch=clamp(viewRef.current.pitch+dpitch,-.18,1.15);velocityRef.current={yaw:dyaw*(16.67/dt),pitch:dpitch*(16.67/dt)};drag.x=e.clientX;drag.y=e.clientY;drag.t=now;scheduleDraw();return}if(hoverFrameRef.current)return;const target=e.currentTarget,clientX=e.clientX,clientY=e.clientY;hoverFrameRef.current=requestAnimationFrame(()=>{hoverFrameRef.current=0;const r=target.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;let best=null,dist=Infinity;for(const p of projectedRef.current){const d=Math.hypot(p.x-x,p.y-y);if(d<dist){dist=d;best=p}}setHover(dist<=12?{...best,x,y}:null)})};
  const up=()=>{if(!dragRef.current)return;dragRef.current=null;startInertia()};
  const wheel=e=>{e.preventDefault();viewRef.current.zoom=clamp(viewRef.current.zoom*Math.exp(-e.deltaY*.0012),.62,2.05);scheduleDraw()};
  return <div className="interactive3dWrap"><canvas ref={canvasRef} className="interactive3d" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onPointerLeave={()=>{up();setHover(null)}} onWheel={wheel}/><div className="interactive3dLegend"><span>LOW</span><i/><span>HIGH</span></div><div className="interactive3dHint">drag with inertia · wheel zoom · smoothed mesh</div>{hover&&<div className="interactive3dTooltip" style={{left:clamp(hover.x+12,8,500),top:clamp(hover.y-45,8,300)}}><b>{(hover.iv*100).toFixed(2)}% IV</b><span>{Number.isFinite(hover.dte)?hover.dte.toFixed(1):'—'} DTE · strike ${Number(hover.strike).toFixed(2)}</span><span>{hover.moneyness>=0?'+':''}{(hover.moneyness*100).toFixed(1)}% moneyness</span></div>}</div>;
}
