export const migratedJournalTrades = [
  {
    id:'hist-2026-07-28',createdAt:'2026-07-28T13:30:00.000Z',date:'2026-07-28',time:'09:30',instrument:'MNQ',direction:'short',session:'NY AM',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:390,rMultiple:null,result:'win',
    htfNarrative:'The session opened with a bearish trend and a bearish E&R (expansion and retracement) developing inside the active range. Price had already swept liquidity and the range was positioned for downside delivery. London lows were the main draw and were also functioning as a failure-swing objective. The bearish idea was not based on win rate or a generic directional call; it came from the range structure, the liquidity sweep, and the expectation that the retracement would resolve back toward the downside draw.',
    poi:'Top of the bearish retracement inside the range. The retracement was slightly aggressive but still fit the APD / HRL context. For the short entries, the important execution area was the 15-second CISD + OB structure near the top of the retracement, with stops positioned above the OB.',
    liquidityEvent:'At the open, liquidity had been swept and bearish E&R was active inside the range. London lows were the downside target and ultimately behaved as a failure swing. After that failure swing, the directional idea flipped long. Later at NYO, the long thesis incorrectly assumed the relevant lows had already been cleared; internal liquidity remained to the left together with a higher-timeframe draw and HR imbalance.',
    entryModel:'Primary short entry: 15-second CISD + OB + COS at the top of the retracement, with the stop above the OB. The first short delivered roughly +$170 toward London lows. After the London-low failure swing, the reversal long used the same core 15-second confirmation stack — CISD + OB + COS — with buyside as the draw. Later, after the NYO long loss, the bias was corrected back short and the same structure-based execution logic was used for the recovery shorts.',
    executionNotes:'The first short produced about +$170. After the failure swing at London lows, the long reversal continued higher and brought the day to roughly +$300, although price first reacted from an OB/liquidity area before continuing through it. Around NYO, a long lost about $50. I treated the market-open low as the LOD because the premarket lows I had been tracking around 08:20 had already been taken, but I missed remaining internal liquidity to the left, the higher-timeframe draw, and the HR imbalance. I also believed the HTF gap had already been satisfied. Once that context error was recognized, I shifted back to a short bias, recovered the day to roughly +$340, then took another short that brought the session to about +$390.',
    mistakes:'The main mistake was contextual rather than executional: I assumed downside liquidity had been fully cleared and treated the market-open low as the LOD without rechecking the internal liquidity and higher-timeframe draw to the left. The technical entry model itself was not the main problem. Before flipping directional bias, re-map all remaining internal liquidity, HTF imbalance, and unresolved draws instead of relying on the lows tracked earlier in premarket.',
    concepts:['bearish trend','E&R','expansion','retracement','liquidity sweep','London lows','failure swing','APD','HRL','15-second','CISD','OB','COS','buyside','internal liquidity','HTF draw','HR imbalance','NYO'],images:[],
    aiJournal:{
      refinedJournal:'The session opened with a bearish trend and bearish E&R developing inside the active range. Liquidity had already been swept, leaving the range positioned for downside delivery into London lows, which were also the failure-swing objective. I entered near the top of the retracement using a 15-second CISD + OB + COS sequence, with the stop above the OB. The retracement was slightly aggressive but remained valid within the APD / HRL context. That first short delivered roughly +$170 into the downside draw.\n\nAfter London lows failure-swung, I shifted bullish. The reversal used the same core 15-second CISD + OB + COS entry model, this time with buyside as the draw. Price initially reacted from an OB/liquidity area but continued higher, and the sequence brought the day to roughly +$300.\n\nAround NYO I took a long that lost about $50. I had treated the market-open low as the LOD because the premarket lows I had tracked around 08:20 had already been taken. The mistake was that internal liquidity still remained to the left together with a higher-timeframe draw and HR imbalance. I also believed the HTF gap had already been satisfied. This was mainly a context-mapping error rather than a failure of the execution model.\n\nOnce I recognized the remaining downside context, I shifted back to a short bias. The next short recovered the session to roughly +$340, and another short brought the day to about +$390. The strongest part of the session was the consistency of the 15-second CISD + OB + COS execution model when it aligned with range E&R, liquidity, and the active draw. The main lesson is to re-map unresolved internal and HTF liquidity before declaring a low or high as the completed session extreme.',
      thinkDeeper:['When a London-low failure swing causes a directional flip, what objective evidence confirms that the downside draw is actually complete rather than temporarily interrupted?','How often does the 15-second CISD + OB + COS model perform differently when the entry occurs at the top of an E&R retracement versus after a failure swing reversal?','Before labeling a market-open low as LOD, which unresolved internal-liquidity and HTF-imbalance checks should be mandatory?'],
      improvement:'Before changing bias or declaring the session low/high complete, run one fixed context check: unresolved internal liquidity, HTF draw, and nearby HTF imbalance. Keep the 15-second CISD + OB + COS execution model separate from that directional-context decision.',
      patternInsights:['The 15-second CISD + OB + COS sequence was repeatedly used across both continuation and reversal entries.','The best short context combined a bearish trend, range E&R, a prior liquidity sweep, and a defined downside draw into London lows.','The NYO loss came from an incomplete liquidity map rather than from abandoning the established entry model.']
    }
  },
  {
    id:'hist-2026-07-13',createdAt:'2026-07-13T09:30:00.000Z',date:'2026-07-13',time:'09:30',instrument:'',direction:'short',session:'NY AM',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:0,rMultiple:null,result:'',
    htfNarrative:'At the 9:30 open the initial bias was bullish with an expectation that price would fill the NWOG, but price rejected from a wick reaction. The 9AM wick reacted after a bearish retracement and tapped another wick that had already caused a reaction after the previous candle formed CISD plus an order block and reacted from CE — this became the key POI and important PD array. After price took the 9AM high and failed to continue, lower timeframes were used. The expectation was for the 9:30 open highs to be taken, then for price to rebalance and take liquidity while fading the 9AM high.',
    poi:'9AM wick / CISD + OB at CE — key PD array after bearish retracement wick tap',
    liquidityEvent:'9:30 open highs taken; price failed to continue higher; liquidity sought while fading the 9AM high',
    entryModel:'5-second model: clean displacement, COS, inverse FVG, IOFED. Entry anticipated the OB candle that drove price into IOFED; stop placed beyond the IOFED wicks.',
    executionNotes:'Target: unrebalanced hourly wick / rejection block that had previously used an OB to drive price higher. Price nearly reached breakeven; event-driven volatility then pushed into the wick CE and first-presented OB with liquidity. PM session: price took the 9AM high, reacted from the wick that created OB + CISD near the 7AM highs, used CE, and delivered lower.\n\n[Historical import — outcome and P&L were not specified in the original notes. The pnl field is 0 solely because the data model requires a numeric value; it does not represent the actual trade result.]',
    mistakes:'Wait for the OB candle that drove price into IOFED to close before entering — the first PD array after IOFED is usually OB/CISD.',
    concepts:['NWOG','9AM high','wick reaction','CE','CISD','OB','COS','inverse FVG','IOFED','hourly wick','rejection block','MMBM'],images:[]
  },
  {
    id:'hist-2026-07-10',createdAt:'2026-07-10T13:30:00.000Z',date:'2026-07-10',time:'',instrument:'NQ',direction:'short',session:'NY AM',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:0,rMultiple:null,result:'',
    htfNarrative:'Bearish. Price consolidated from the prior-day lunch session into the close, failed during Asia, and closed below a 30-minute OB between 18:00 and 20:00. A pullback occurred around 21:00–22:00 before delivery continued lower into London. At the New York open price ran toward the Asia highs that had initiated the London sell delivery. The expected reaction area was the first-presented OB, refined internal liquidity, and the next pending PD array (inverse FVG).',
    poi:'First-presented OB; refined internal liquidity; pending inverse FVG',
    liquidityEvent:'NY open ran toward Asia highs that initiated London sell delivery; NQ showed internal liquidity sweep and SMT with NQ leading ES',
    entryModel:"NQ/ES SMT: price pulled back into CISD + OB while ES SMT'd a 15-second FVG that remained above the CISD/OB area, creating a BAG for NQ. The 5-second BAG lower-wick IOFED into an FVG, confirming the 15-second wick as a functioning rejection block. Stop placed beyond the BAG/rejection wick.",
    executionNotes:'Target: unswept 9:30 low. (Original note referenced buyside; corrected — the low was the intended target.)\n\n[Historical import — outcome and P&L were not specified in the original notes. The pnl field is 0 solely because the data model requires a numeric value; it does not represent the actual trade result.]',
    mistakes:'',concepts:['bearish delivery','Asia high','London delivery','first-presented OB','internal liquidity','SMT','NQ/ES','15-second FVG','BAG','5-second IOFED','CISD','rejection block','9:30 low'],images:[]
  },
  {
    id:'hist-2026-07-09',createdAt:'2026-07-09T13:30:00.000Z',date:'2026-07-09',time:'',instrument:'',direction:'long',session:'',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:0,rMultiple:null,result:'',
    htfNarrative:'Price established a 4-hour intermediate-term low (ITL) and reacted from a valid bullish order block, supporting a bullish higher-timeframe bias and MMBM continuation. Price was expected to seek nearby liquidity before continuing higher.',
    poi:'First-presented bullish OB (unmitigated, cleaner POI). Do not prioritize the final OB near the ITL when the earlier unmitigated OB remains available. Invalidation: price trading below the 4H ITL.',
    liquidityEvent:'',entryModel:'',executionNotes:'[Historical import — entry, stop, target, outcome, and P&L were not specified in the original notes. The pnl field is 0 solely because the data model requires a numeric value; it does not represent the actual trade result.]',mistakes:'',concepts:['4H ITL','bullish OB','first-presented OB','unmitigated OB','liquidity','MMBM'],images:[]
  },
  {
    id:'hist-2026-07-17-short',createdAt:'2026-07-17T13:30:00.000Z',date:'2026-07-17',time:'09:30',instrument:'',direction:'short',session:'NY AM',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:0,rMultiple:null,result:'',
    htfNarrative:"To the left were two candles. The first reached almost out of an OB to the left; there was probably a smaller-timeframe reaction, such as an imbalance or OB, that made it react down. The following candle reacted at 0.5 of it, making this the important PD array/RB. On Thursday, price hit the CE of it while taking internal and external liquidity. Because this happened Thursday, I expected Friday to give the low of the week, as it statistically happens. At 6:30, price IOFED'd a 4H bearish gap while London lows and an external liquidity point remained to complete the sell model.",
    poi:'The blue box that led the move up to IOFED the 4H bearish gap was a continuous sequence of up candles. Once price closed below that sequence, it became the OB/CISD area. The following candle reacted in the OB, and the wick from that reaction became the first RB. A candle was then used for liquidity, and the next candle reacted at the CE of the RB that had reacted in the OB, creating the next RB. After roughly two more candles displaced lower and failure-swung the London low before the New York open, the 9:30 move returned to the RB that had reacted in the prior RB—the chain created from the original OB reaction—and then delivered lower.',
    liquidityEvent:'Thursday took internal and external liquidity at CE. On Friday, London lows and an external liquidity point remained below. Before the New York open, price failure-swung the London low; after the 9:30 reaction, price delivered lower to take internal and external liquidity on the higher timeframe.',
    entryModel:'A FVG was left, and the candles that formed or closed it were also volume imbalances. Price reacted at the CE of the FVG. The wick from that reaction was used to drive price lower and created an OB, shown by the red line once price closed under it. The following candle reacted in that OB, and the next candle reacted in the wick created by the OB reaction; that final wick reaction was my entry. I also had CISD first at the top on the 5-second chart. On the 15-second chart, closing below the OB also closed below a set of up candles, making it CISD + OB. I need a COS/MSS/CISD for the entry.',
    executionNotes:'I placed my stop slightly above the final wick because of volatility. That wick was the next PD array and should have held. Because price had already over-expanded, I tried to squeeze the most out of the target, but I was trailed out and then entered longs.\n\n[Historical import — exact outcome, risk, and P&L were not supplied. The pnl field is 0 only because the data model requires a numeric value; it is not the trade result.]',
    mistakes:'',concepts:['4H bearish FVG','IOFED','CE','internal liquidity','external liquidity','London low','OB','CISD','RB','nested RB','FVG','volume imbalance','COS','MSS','displacement','failure swing'],images:[]
  },
  {
    id:'hist-2026-07-17-long',createdAt:'2026-07-17T13:47:00.000Z',date:'2026-07-17',time:'',instrument:'',direction:'long',session:'NY AM',grade:'',entryPrice:null,stopLoss:null,target:null,risk:null,pnl:0,rMultiple:null,result:'',
    htfNarrative:'This was a reversal reaction after a higher-timeframe PD array/FVG and external imbalance were hit.',
    poi:'Within the intraday range, there was an IFVG, then a FVG. An RB reacted in the FVG, and another wick reacted in the previous RB wick. Price then continued moving higher. The full reaction chain was IFVG -> FVG -> RB reaction in the FVG -> second wick reaction in the prior RB.',
    liquidityEvent:"After the MSS/COS and its reaction, price moved higher, then IOFED'd a gap.",
    entryModel:"After price reacted in the MSS/COS and moved up, it IOFED'd the gap. The IOFED reaction into that gap was my long entry.",
    executionNotes:'I initially left the stop around the marked red-box area. Once price showed that the gap reaction was an IOFED, I moved the stop to the IOFED area because there was no reason for price to move back through it if the reaction remained valid.\n\n[Historical import — exact target, outcome, risk, and P&L were not supplied. The pnl field is 0 only because the data model requires a numeric value; it is not the trade result.]',
    mistakes:'',concepts:['HTF PD array','FVG','external imbalance','IFVG','RB','nested wick reaction','MSS','COS','IOFED'],images:[]
  }
];

export function migratedNotes(trade){
  const blocks=[['HTF narrative',trade.htfNarrative],['POI / important PD array',trade.poi],['Liquidity event',trade.liquidityEvent],['Entry model',trade.entryModel],['Execution / management',trade.executionNotes],['Mistakes / lessons',trade.mistakes]].filter(([,value])=>String(value||'').trim());
  return blocks.map(([label,value])=>`${label}:\n${value}`).join('\n\n');
}
