import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowUpRight,ImagePlus,Loader2,Plus,Search,Sparkles,Trash2,Upload,Download,X}from'lucide-react';
import{migratedJournalTrades,migratedNotes}from'./journalSeed.js';

const DB='QNTJournalDB',STORE='trades',SEEDED='qnt.journal.migrated.v3';
const emptyTrade=()=>{const d=new Date();return{id:null,createdAt:null,date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5),instrument:'MNQ',direction:'',session:'NY AM',result:'',pnl:'',risk:'',rMultiple:'',concepts:'',notes:'',images:[],aiJournal:null}};
const resultOf=t=>['win','loss','be'].includes(t?.result)?t.result:Number(t?.pnl)>0?'win':Number(t?.pnl)<0?'loss':'be';
const asNum=v=>v===''||v==null?null:Number.isFinite(Number(v))?Number(v):null;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function all(db){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function put(db,item){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function del(db,id){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function compressImage(file){const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)}),img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src}),scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return{name:file.name,type:'image/jpeg',dataUrl:canvas.toDataURL('image/jpeg',.72)}}
function money(v){if(v===''||v==null)return'—';const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}$${Math.abs(n).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—'}

export default function JournalWorkspace(){
  const dbRef=useRef(null),[trades,setTrades]=useState([]),[draft,setDraft]=useState(emptyTrade),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[status,setStatus]=useState(''),fileRef=useRef(null),importRef=useRef(null);
  const refresh=async()=>{if(!dbRef.current)return;const rows=await all(dbRef.current);rows.sort((a,b)=>{const dateCmp=String(b.date||'').localeCompare(String(a.date||''));if(dateCmp)return dateCmp;if(Number.isFinite(Number(a.sequence))&&Number.isFinite(Number(b.sequence)))return Number(b.sequence)-Number(a.sequence);return new Date(`${b.date||'1970-01-01'}T${b.time||'00:00'}`)-new Date(`${a.date||'1970-01-01'}T${a.time||'00:00'}`)});setTrades(rows)};
  useEffect(()=>{let live=true;(async()=>{const db=await openDb();if(!live)return;dbRef.current=db;if(!localStorage.getItem(SEEDED)){await del(db,'hist-2026-07-28');for(const source of migratedJournalTrades){await put(db,{...source,notes:migratedNotes(source),concepts:(source.concepts||[]).join(', '),source:source.source||'migrated SIC journal'})}localStorage.setItem(SEEDED,'1')}await refresh()})().catch(e=>setStatus(e.message));return()=>{live=false;dbRef.current?.close?.()}},[]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return trades.filter(t=>!q||[t.date,t.instrument,t.direction,t.session,t.notes,t.concepts,t.aiJournal?.refinedJournal].join(' ').toLowerCase().includes(q))},[trades,query]);
  const choose=t=>{setSelected(t.id);setDraft({...emptyTrade(),...t,concepts:Array.isArray(t.concepts)?t.concepts.join(', '):(t.concepts||''),images:t.images||[]})};
  const reset=()=>{setSelected(null);setDraft(emptyTrade());setStatus('')};
  const change=(key,value)=>setDraft(x=>({...x,[key]:value}));
  const save=async()=>{if(!dbRef.current)return;const item={...draft,id:draft.id||uid(),createdAt:draft.createdAt||new Date().toISOString(),instrument:String(draft.instrument||'').trim().toUpperCase(),pnl:asNum(draft.pnl),risk:asNum(draft.risk),rMultiple:asNum(draft.rMultiple),concepts:String(draft.concepts||'').split(',').map(x=>x.trim()).filter(Boolean),images:draft.images||[]};await put(dbRef.current,item);setStatus('Saved');setSelected(item.id);setDraft({...item,concepts:item.concepts.join(', ')});await refresh()};
  const remove=async id=>{if(!dbRef.current||!confirm('Delete this journal entry?'))return;await del(dbRef.current,id);if(selected===id)reset();await refresh()};
  const addImages=async files=>{const next=[];for(const file of [...files].slice(0,Math.max(0,3-(draft.images?.length||0))))try{next.push(await compressImage(file))}catch{}setDraft(x=>({...x,images:[...(x.images||[]),...next].slice(0,3)}))};
  const memory=trades.filter(t=>t.id!==draft.id).slice(0,10).map(t=>({date:t.date,time:t.time,instrument:t.instrument,direction:t.direction,session:t.session,result:resultOf(t),pnl:t.pnl,risk:t.risk,rMultiple:t.rMultiple,notes:t.notes,concepts:Array.isArray(t.concepts)?t.concepts:[],refinedJournal:t.aiJournal?.refinedJournal||'',researchQuestions:t.aiJournal?.thinkDeeper||[],improvement:t.aiJournal?.improvement||''}));
  const refine=async mode=>{if(loading)return;if(mode==='notes'&&!String(draft.notes||'').trim()){setStatus('Add rough notes first');return}if(mode==='charts'&&!(draft.images||[]).length){setStatus('Upload at least one chart first');return}setLoading(true);setStatus(mode==='charts'?'Reading charts…':'Refining notes…');try{const res=await fetch('/api/journal/refine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,trade:{...draft,concepts:String(draft.concepts||'').split(',').map(x=>x.trim()).filter(Boolean)},memory,images:(draft.images||[]).slice(0,3)})}),data=await res.json();if(!res.ok)throw new Error(data.error||'Refine request failed');setDraft(x=>({...x,aiJournal:data}));setStatus('Refined')}catch(e){setStatus(e.message)}finally{setLoading(false)}};
  const exportJson=()=>{const blob=new Blob([JSON.stringify({app:'QNT Journal',version:1,exportedAt:new Date().toISOString(),trades},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`qnt-journal-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
  const importJson=async file=>{if(!file||!dbRef.current)return;try{const raw=JSON.parse(await file.text()),rows=Array.isArray(raw)?raw:raw.trades;if(!Array.isArray(rows))throw new Error('Invalid journal backup');for(const t of rows){const item={...t,id:t.id||uid(),notes:t.notes||migratedNotes(t),concepts:Array.isArray(t.concepts)?t.concepts:String(t.concepts||'').split(',').map(x=>x.trim()).filter(Boolean),images:t.images||[]};await put(dbRef.current,item)}await refresh();setStatus(`Imported ${rows.length} trades`)}catch(e){setStatus(e.message)}};
  return <div className="q4Journal">
    <section className="q4JournalEditor">
      <div className="q4PaneTitle"><div><span>TRADE INPUT</span><h2>{draft.id?'Edit trade':'New trade'}</h2></div><button onClick={reset}><Plus size={14}/> New</button></div>
      <div className="q4FormGrid six"><label>Date<input type="date" value={draft.date||''} onChange={e=>change('date',e.target.value)}/></label><label>Time<input type="time" value={draft.time||''} onChange={e=>change('time',e.target.value)}/></label><label>Instrument<input value={draft.instrument||''} onChange={e=>change('instrument',e.target.value)} placeholder="MNQ"/></label><label>Direction<select value={draft.direction||''} onChange={e=>change('direction',e.target.value)}><option value="">—</option><option value="long">Long</option><option value="short">Short</option></select></label><label>Session<select value={draft.session||''} onChange={e=>change('session',e.target.value)}><option value="">—</option><option>Pre-market</option><option>Asia</option><option>London</option><option>NY AM</option><option>NY PM</option></select></label><label>Result<select value={draft.result||''} onChange={e=>change('result',e.target.value)}><option value="">Auto</option><option value="win">Win</option><option value="loss">Loss</option><option value="be">BE</option></select></label></div>
      <div className="q4FormGrid three"><label>P&amp;L<input type="number" value={draft.pnl??''} onChange={e=>change('pnl',e.target.value)} placeholder="0"/></label><label>Risk<input type="number" value={draft.risk??''} onChange={e=>change('risk',e.target.value)} placeholder="optional"/></label><label>R multiple<input type="number" step="0.01" value={draft.rMultiple??''} onChange={e=>change('rMultiple',e.target.value)} placeholder="optional"/></label></div>
      <label className="q4BigLabel">Rough journal<textarea value={draft.notes||''} onChange={e=>change('notes',e.target.value)} placeholder="Write it how you saw it. Keep your ICT terms, reaction chain, management, mistakes, and your own wording. The refiner should organize it, not rewrite your model."/></label>
      <label className="q4BigLabel compact">Concepts<input value={draft.concepts||''} onChange={e=>change('concepts',e.target.value)} placeholder="IOFED, CISD, OB, RB, FVG…"/></label>
      <div className="q4Images"><div><span>CHARTS</span><small>up to 3 · HTF, range, entry</small></div><button onClick={()=>fileRef.current?.click()}><ImagePlus size={14}/> Add charts</button><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>{addImages(e.target.files);e.target.value=''}}/></div>
      {!!draft.images?.length&&<div className="q4ImageStrip">{draft.images.map((img,i)=><div key={`${img.name}-${i}`}><img src={img.dataUrl} alt="trade chart"/><button onClick={()=>setDraft(x=>({...x,images:x.images.filter((_,j)=>j!==i)}))}><X size={12}/></button></div>)}</div>}
      <div className="q4EditorActions"><button className="primary" onClick={save}>Save trade</button><button onClick={()=>refine('notes')} disabled={loading}><Sparkles size={14}/> Refine notes</button><button onClick={()=>refine('charts')} disabled={loading}><ImagePlus size={14}/> Read charts</button><span>{loading&&<Loader2 className="spin" size={13}/>} {status}</span></div>
    </section>

    <section className="q4TradeList">
      <div className="q4PaneTitle"><div><span>RECORDED</span><h2>{trades.length} trades</h2></div><div className="q4MiniActions"><button onClick={()=>importRef.current?.click()} title="Import old SIC/QNT JSON"><Upload size={13}/></button><button onClick={exportJson} title="Export JSON"><Download size={13}/></button><input ref={importRef} hidden type="file" accept="application/json" onChange={e=>{importJson(e.target.files?.[0]);e.target.value=''}}/></div></div>
      <div className="q4JournalSearch"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search journal"/></div>
      <div className="q4TradeRows">{filtered.map(t=><button className={`q4TradeRow ${selected===t.id?'active':''}`} key={t.id} onClick={()=>choose(t)}><div><b>{t.instrument||'—'} <span>{String(t.direction||'').toUpperCase()}</span></b><small>{t.date}{t.time?` · ${t.time}`:''} · {t.session||'—'}</small></div><div><strong className={resultOf(t)}>{resultOf(t).toUpperCase()}</strong><em>{money(t.pnl)}</em></div><ArrowUpRight size={13}/><span className="q4Delete" role="button" tabIndex={0} onClick={e=>{e.stopPropagation();remove(t.id)}}><Trash2 size={12}/></span></button>)}{!filtered.length&&<div className="q4Empty">No matching trades.</div>}</div>
    </section>

    <aside className="q4Refine">
      <div className="q4PaneTitle"><div><span>REFINE BOT</span><h2>Journal editor</h2></div><Sparkles size={15}/></div>
      {draft.aiJournal?.refinedJournal?<div className="q4RefineBody"><section><span>REFINED NARRATIVE</span><textarea value={draft.aiJournal.refinedJournal} onChange={e=>setDraft(x=>({...x,aiJournal:{...x.aiJournal,refinedJournal:e.target.value}}))}/></section>{draft.aiJournal.thinkDeeper?.length>0&&<section><span>RESEARCH QUESTIONS</span>{draft.aiJournal.thinkDeeper.map((q,i)=><p key={i}>{q}</p>)}</section>}{draft.aiJournal.improvement&&<section><span>ONE IMPROVEMENT</span><p>{draft.aiJournal.improvement}</p></section>}{draft.aiJournal.patternInsights?.length>0&&<section><span>SUPPORTED PATTERNS</span>{draft.aiJournal.patternInsights.map((p,i)=><p key={i}>{p}</p>)}</section>}<button className="primary" onClick={save}>Save refined trade</button></div>:<div className="q4RefineEmpty"><Sparkles size={22}/><b>Refine this trade</b><p>Write rough notes or upload marked charts. The bot keeps your wording and ICT terms, organizes the note, and avoids narrating extra structure you did not say.</p><small>Uses up to 10 prior journal entries as memory. It does not generate live trade calls.</small></div>}
    </aside>
  </div>;
}
