import React from'react';
import ReactDOM from'react-dom/client';
import QntRedesign from'./QntRedesign.jsx';
import'./styles.css';
import'./volatility.css';
import'./montecarlo.css';
import'./montecarlo-validation.css';
import'./model-stats-strip.css';
import'./risk-v2.css';
import'./prop-v2.css';
import'./terminal-home.css';
import'./bloomberg-desk.css';
import'./analytics-terminal.css';
import'./terminal-workbench.css';
import'./terminal-workbench-extra.css';
import'./terminal-cohesion.css';
import'./research-studio.css';
import'./research-stats.css';
import'./research-validation.css';
import'./strategy-validation.css';
import'./product-shell.css';
import'./terminal-shell.css';
import'./terminal-market.css';
import'./data-terminal.css';
import'./functional.css';
import'./responsive-overrides.css';
import'./modern-ui.css';
import'./ui-v3.css';
import'./qnt-v4.css';
import'./navigation-fixes.css';
import'./research-layout-fixes.css';

ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><QntRedesign/></React.StrictMode>);
