import React, { useMemo, useRef, useState, useEffect } from 'react';
import { Play, RefreshCw, Settings2, X } from 'lucide-react';
import { personalModel } from './personalDataset';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const mean=a=>a.reduce((s,v)=>s+v,0)/(a.length||1);
const quantile=(a,p)=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y);return s[Math.min(s.length-1,Math.max(0,Math.floor((s.length-1)*p)))]};
const money=n=>`${Number(n)<0?'-':''}$${Math.abs(Number(n)||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const pct=n=>`${Number(n||0).toFixed(1)}%`;
const winsConservative=personalModel.winR.map(r=>1.1*Math.log1p(Math.max(0,r)));
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function normal01(random){const u1=Math.max(1e-12,random()),u2=Math.max(1e-12,random());return Math.sqrt(-2*Math.log(u1))*Math.cos(2*Math.PI*u2)}
function gammaSample(random,shape){if(shape<1)return gammaSample(random,shape+1)*Math.pow(Math.max(random(),1e-12),1/shape);const d=shape-1/3,c=1/Math.sqrt(9*d);for(let i=0;i<64;i++){const x=normal01(random),v0=1+c*x;if(v0<=0)continue;const v=v0**3,u=random();if(u<1-.0331*x**4||Math.log(Math.max(u,1e-12))<.5*x*x+d*(1-v+Math.log(v)))return d*v}return shape}
function sampleProbabilities(random){const w=gammaSample(random,personalModel.evalWins+.5),l=gammaSample(random,personalModel.evalLosses+.5),b=gammaSample(random,personalModel.evalBreakevens+.5),sum=w+l+b||1;return{win:w/sum,loss:l/sum,be:b/sum}}
function drawR(random,wins,p){const u=random();if(u<p.win)return wins[Math.floor(random()*wins.length)]||0;if(u<p.win+p.loss)return personalModel.lossR[Math.floor(random()*personalModel.lossR.length)]||0;return 0}

function simulate(cfg,seed){
  const random=rng(seed),paths=Array.from({length:cfg.simulations},()=>new Float32Array(cfg.maxDays+1)),meta=[];const reasons={};let pass=0,fail=0,timeout=0,payouts=0;const pnl=[],passDays=[],failDays=[];
  for(let i=0;i<cfg.simulations;i++){
    const probs=sampleProbabilities(random);let equity=cfg.start,peak=cfg.start,status='active',reason='Time limit reached',endStep=cfg.maxDays,maxDayProfit=0,totalPositive=0;paths[i][0]=equity;const log=[];
    for(let day=1;day<=cfg.maxDays;day++){
      const r=drawR(random,winsConservative,probs),delta=r*cfg.risk;equity+=delta;peak=Math.max(peak,equity);maxDayProfit=Math.max(maxDayProfit,delta);if(delta>0)totalPositive+=delta;paths[i][day]=equity;const trailingFloor=cfg.trailingDrawdown>0?Math.max(cfg.staticFloor,peak-cfg.trailingDrawdown):cfg.staticFloor;log.push({day,r,delta,equity,trailingFloor});
      if(cfg.dailyLossLimit>0&&delta<=-cfg.dailyLossLimit){status='fail';reason='Daily loss limit breached';endStep=day;break}
      if(equity<=trailingFloor){status='fail';reason=cfg.trailingDrawdown>0&&trailingFloor>cfg.staticFloor?'Trailing drawdown breached':'Static drawdown breached';endStep=day;break}
      const netProfit=Math.max(0,equity-cfg.start),consistencyShare=netProfit>0?maxDayProfit/netProfit*100:100,consistencyOk=cfg.consistencyPct<=0||consistencyShare<=cfg.consistencyPct;
      if(equity>=cfg.target&&day>=cfg.minDays&&consistencyOk){status='pass';reason='Profit target reached with active rules satisfied';endStep=day;break}
    }
    for(let day=endStep+1;day<=cfg.maxDays;day++)paths[i][day]=equity;
    const net=equity-cfg.start,consistencyShare=net>0?maxDayProfit/net*100:100,consistencyOk=cfg.consistencyPct<=0||consistencyShare<=cfg.consistencyPct;
    const payoutEligible=status!=='fail'&&equity>=cfg.payoutThreshold&&endStep>=cfg.minDays&&consistencyOk;
    const expectedPayout=payoutEligible?Math.max(0,equity-cfg.start)*cfg.payoutSplit/100:0;
    if(status==='pass'){pass++;passDays.push(endStep)}else if(status==='fail'){fail++;failDays.push(endStep);reasons[reason]=(reasons[reason]||0)+1}else timeout++;
    if(payoutEligible)payouts++;pnl.push(net);meta.push({status,reason,endStep,finalEquity:equity,netPnl:net,payoutEligible,expectedPayout,consistencyShare,log,sampledWinRate:probs.win*100});
  }
  const failureReason=Object.entries(reasons).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';
  return {paths,meta,passPct:pass/cfg.simulations*100,failPct:fail/cfg.simulations*100,timeoutPct:timeout/cfg.simulations*100,payoutPct:payouts/cfg.simulations*100,meanPnl:mean(pnl),p5:quantile(pnl,.05),p50:quantile(pnl,.5),p95:quantile(pnl,.95),avgPassDays:mean(passDays),avgFailDays:mean(failDays),expectedPayout:mean(meta.map(x=>x.expectedPayout)),failureReason};
}

function Metric({label,value,sub,tone=''}){return <div className="qpfMetric"><span>{label}</span><b className={tone}>{value}</b>{sub&&<small>{sub}</small>}</div>}

function PathCanvas({result,cfg,onSelect}){
  const base=useRef(null),overlay=useRef(null),scale=useRef(null),[hover,setHover]=useState(null);
  useEffect(()=>{const c=base.current,o=overlay.current;if(!c||!o)return;const rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);for(const x of[c,o]){x.width=Math.round(rect.width*dpr);x.height=Math.round(rect.height*dpr)}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height,pad={l:54,r:10,t:12,b:24};ctx.fillStyle='#050607';ctx.fillRect(0,0,w,h);const all=result.meta.map(m=>m.finalEquity),lo=Math.min(cfg.staticFloor,...all),hi=Math.max(cfg.target,...all),span=hi-lo||1,xOf=s=>pad.l+(s/cfg.maxDays)*(w-pad.l-pad.r),yOf=v=>pad.t+(hi+span*.08-v)/(span*1.16)*(h-pad.t-pad.b);ctx.font='8px ui-monospace,monospace';for(let k=0;k<5;k++){const v=lo+span*k/4,y=yOf(v);ctx.strokeStyle='rgba(110,116,126,.14)';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#596069';ctx.fillText(`$${Math.round(v/1000)}k`,5,y+3)}const stride=Math.max(1,Math.ceil(result.paths.length/700)),indices=[];for(let i=0;i<result.paths.length;i+=stride){indices.push(i);const p=result.paths[i],m=result.meta[i];ctx.strokeStyle=m.status==='pass'?'rgba(42,212,161,.18)':m.status==='fail'?'rgba(239,102,112,.17)':'rgba(227,189,72,.14)';ctx.lineWidth=.55;ctx.beginPath();for(let s=0;s<=m.endStep;s++){const x=xOf(s),y=yOf(p[s]);if(s===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}for(const [v,color,label] of[[cfg.target,'#2ad4a1','Target'],[cfg.staticFloor,'#ef6670','Static floor']]){const y=yOf(v);ctx.setLineDash([5,4]);ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.fillText(label,w-70,y-4)}scale.current={w,h,pad,xOf,yOf,indices}},[result,cfg]);
  useEffect(()=>{const c=overlay.current,s=scale.current;if(!c||!s)return;const dpr=Math.min(devicePixelRatio||1,2),ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,s.w,s.h);if(hover==null)return;const p=result.paths[hover],m=result.meta[hover];ctx.strokeStyle=m.status==='pass'?'#2ad4a1':m.status==='fail'?'#ef6670':'#e3bd48';ctx.lineWidth=2;ctx.beginPath();for(let d=0;d<=m.endStep;d++){const x=s.xOf(d),y=s.yOf(p[d]);if(d===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()},[hover,result]);
  const move=e=>{const s=scale.current;if(!s)return;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,day=clamp(Math.round((x-s.pad.l)/(r.width-s.pad.l-s.pad.r)*cfg.maxDays),0,cfg.maxDays);let best=null,dist=Infinity;for(const i of s.indices){const m=result.meta[i];if(day>m.endStep)continue;const d=Math.abs(s.yOf(result.paths[i][day])-y);if(d<dist){dist=d;best=i}}setHover(dist<=7?best:null)};
  return <div className="qpfCanvasWrap"><canvas ref={base}/><canvas ref={overlay} onPointerMove={move} onPointerLeave={()=>setHover(null)} onClick={()=>hover!=null&&onSelect(hover)}/>{hover!=null&&<div className="qpfHover"><span>PATH #{hover+1}</span><b>{result.meta[hover].status.toUpperCase()}</b><small>{result.meta[hover].reason} · click for log</small></div>}</div>;
}

export default function PropFirmV2(){
  const defaults={simulations:4000,start:50000,risk:150,target:53000,staticFloor:48000,trailingDrawdown:0,dailyLossLimit:0,minDays:5,maxDays:39,payoutThreshold:52500,payoutSplit:90,consistencyPct:0};
  const [draft,setDraft]=useState(defaults),[active,setActive]=useState(defaults),[seed,setSeed]=useState(9817),[settings,setSettings]=useState(true),[selected,setSelected]=useState(null),[phase,setPhase]=useState('Challenge');
  const result=useMemo(()=>simulate(active,seed),[active,seed]);const set=(k,v)=>setDraft(d=>({...d,[k]:Number(v)}));
  const run=newSeed=>{const safe={...draft,simulations:clamp(Math.round(draft.simulations||4000),100,10000),maxDays:clamp(Math.round(draft.maxDays||39),5,500),minDays:clamp(Math.round(draft.minDays||0),0,500),payoutSplit:clamp(draft.payoutSplit||0,0,100),consistencyPct:clamp(draft.consistencyPct||0,0,100)};setActive(safe);setDraft(safe);setSelected(null);if(newSeed)setSeed(s=>(s+104729)>>>0)};
  const switchPhase=next=>{setPhase(next);const cfg=next==='Challenge'?defaults:{...defaults,target:52500,maxDays:60,payoutThreshold:52500};setDraft(cfg);setActive(cfg);setSelected(null)};
  return <div className="qpfPage"><header className="qpfHead"><div><span>PROP RESEARCH</span><h1>Rule-driven account simulator</h1><p>Each simulation step represents one modeled trading day. Pass/fail/timeout and payout logic use the configured rules below.</p></div><div className="qpfActions"><span>SEED {seed}</span><button onClick={()=>setSettings(v=>!v)}><Settings2 size={12}/> Rules</button><button onClick={()=>run(true)}><RefreshCw size={12}/> New seed</button><button className="run" onClick={()=>run(false)}><Play size={12}/> Run</button></div></header><div className="qpfPhase"><button className={phase==='Challenge'?'active':''} onClick={()=>switchPhase('Challenge')}>Challenge</button><button className={phase==='Funded'?'active':''} onClick={()=>switchPhase('Funded')}>Funded</button></div>{settings&&<div className="qpfSettings">{[['simulations','Simulations'],['start','Start'],['risk','Risk / day'],['target','Profit target'],['staticFloor','Static floor'],['trailingDrawdown','Trailing DD'],['dailyLossLimit','Daily loss'],['minDays','Min days'],['maxDays','Max days'],['payoutThreshold','Payout threshold'],['payoutSplit','Payout split %'],['consistencyPct','Consistency max-day %']].map(([k,l])=><label key={k}>{l}<input value={draft[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div>}
    <div className="qpfMetrics"><Metric label="PASS" value={pct(result.passPct)} tone="good"/><Metric label="FAIL" value={pct(result.failPct)} tone="bad"/><Metric label="TIMEOUT" value={pct(result.timeoutPct)} tone="warn"/><Metric label="PAYOUT ELIGIBLE" value={pct(result.payoutPct)} tone="good"/><Metric label="MEAN P&L" value={money(result.meanPnl)}/><Metric label="EXPECTED PAYOUT" value={money(result.expectedPayout)} tone="good"/><Metric label="AVG DAYS PASS / FAIL" value={`${result.avgPassDays?result.avgPassDays.toFixed(1):'—'} / ${result.avgFailDays?result.avgFailDays.toFixed(1):'—'}`}/><Metric label="MOST COMMON FAIL" value={result.failureReason} /></div>
    <section className="qpfChart"><div className="qpfPanelHead"><b>{phase} equity paths</b><span>{active.simulations.toLocaleString()} simulations · click a path for its full rule log</span></div><PathCanvas result={result} cfg={active} onSelect={setSelected}/></section>
    <div className="qpfPercentiles"><Metric label="5TH PCT NET" value={money(result.p5)} tone={result.p5<0?'bad':''}/><Metric label="MEDIAN NET" value={money(result.p50)}/><Metric label="95TH PCT NET" value={money(result.p95)} tone="good"/><Metric label="MODEL" value={`${(personalModel.winProbability*100).toFixed(1)}% observed WR`} sub="posterior WR sampled per path"/></div>
    {selected!=null&&<aside className="qpfDrawer"><div className="qpfDrawerHead"><div><b>Path #{selected+1} · {result.meta[selected].status.toUpperCase()}</b><span>{result.meta[selected].reason} · final {money(result.meta[selected].finalEquity)} · sampled WR {result.meta[selected].sampledWinRate.toFixed(1)}%</span></div><button onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="qpfRuleState"><span>Payout eligible <b>{result.meta[selected].payoutEligible?'YES':'NO'}</b></span><span>Modeled payout <b>{money(result.meta[selected].expectedPayout)}</b></span><span>Consistency share <b>{result.meta[selected].consistencyShare.toFixed(1)}%</b></span></div><div className="qpfLogHead"><span>DAY</span><span>R*</span><span>P&L</span><span>EQUITY</span><span>ACTIVE FLOOR</span></div><div className="qpfLog">{result.meta[selected].log.map(x=><div key={x.day}><span>{x.day}</span><span>{x.r>=0?'+':''}{x.r.toFixed(2)}</span><span className={x.delta>=0?'good':'bad'}>{x.delta>=0?'+':''}{money(x.delta)}</span><span>{money(x.equity)}</span><span>{money(x.trailingFloor)}</span></div>)}</div></aside>}
    <p className="qpfFoot">This is a generic research simulator, not a verified preset for any specific prop company. Rules must be entered from a verified source. Current R* uses QNT's normalized payoff model, not stop-defined true R.</p>
  </div>;
}
