import React,{useEffect,useMemo,useState}from'react';
import{Activity,BarChart3,BookOpen,ChevronRight,Command,Database,FlaskConical,Home,Search,Server,Sparkles}from'lucide-react';
import App from'./App.jsx';
import TerminalWorkbench from'./TerminalWorkbench.jsx';
import BloombergDesk from'./BloombergDesk.jsx';
import AnalyticsTerminal from'./AnalyticsTerminal.jsx';
import DataTerminal from'./DataTerminal.jsx';
import JournalWorkspace from'./JournalWorkspace.jsx';
import{personalModel}from'./personalDataset.js';

const MARKET_WORKBENCH=['TOP','HMAP','DIST','ROLL','BETA','VOLC','VCA','QQL','SCEN','EXP'];
const MARKET_DESK=['LAUNCH','DES','CHART','CORR','OMON'];
const MARKET_ANALYTICS=['CHAIN','SURF','SKEW','TERM','RVIV','GREEKS','OI'];
const COMMANDS=[
  ['HOME','Overview','QNT workspace overview'],['JOURNAL','Journal','Trade input, recorded trades and refine bot'],['WORK','Research Studio','Python research + QNT agent'],['VALIDATE','Validation','Holdouts, bootstrap, stability and robustness'],['VERDICT','Verdict','Strategy evidence review'],['REGIME','Regimes','Regime research pipeline'],['MC','Monte Carlo','Stopped-path risk simulation'],['PROP','Prop Simulator','Rule-driven challenge simulation'],['VOL','Volatility Lab','Volatility research'],
  ['TOP','Market Monitor','Cross-market monitor'],['HMAP','Heatmap','Cross-sectional heatmap'],['DIST','Distribution','Return distribution'],['ROLL','Rolling Corr','Rolling correlation'],['BETA','Beta','Regression / beta lab'],['VOLC','Vol Cone','Realized-volatility cone'],['VCA','VCA','Volatility / correlation analysis'],['QQL','QNT Query','Deterministic data query'],['SCEN','Scenario','Strategy stress lab'],['EXP','Experiments','Saved experiment registry'],['LAUNCH','Desk','Multi-panel workstation'],['DES','Security','Security analytics'],['CHART','Chart','Multi-asset chart workstation'],['CORR','Correlation','Correlation matrix'],['OMON','Options Monitor','Expiration/options monitor'],['CHAIN','Option Chain','Contract-level chain'],['SURF','IV Surface','Interactive IV surface'],['SKEW','Skew','Volatility smile'],['TERM','Term','IV term structure'],['RVIV','RV / IV','Implied vs realized'],['GREEKS','Greeks','Options Greeks matrix'],['OI','Open Interest','OI concentration'],['DATA','Data','Dataset workspace'],['API','System','Provider and model health']
];
const researchMap={WORK:'Workspace',VALIDATE:'Validation',VERDICT:'Verdict',REGIME:'Regimes',MC:'Risk & Monte Carlo',PROP:'Prop Firm',VOL:'Volatility'};
const emit=(name,detail)=>window.dispatchEvent(new CustomEvent(name,{detail}));
const saveSession=(key,value)=>{try{sessionStorage.setItem(key,JSON.stringify(value))}catch{}};

function Overview({go,runMarket}){
  const[health,setHealth]=useState(null),[quotes,setQuotes]=useState([]),[error,setError]=useState('');
  useEffect(()=>{let live=true;(async()=>{try{const[s,q]=await Promise.all([fetch('/api/status'),fetch('/api/market/quotes?symbols=QQQ,SPY,AAPL,NVDA,MSFT')]),sd=await s.json(),qd=await q.json();if(!live)return;setHealth(sd);if(q.ok)setQuotes(qd.quotes||[])}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[]);
  const model=[['Eval ideas',personalModel.evalPositionIdeas],['Observed WR',`${(personalModel.winProbability*100).toFixed(1)}%`],['Loss rate',`${(personalModel.lossProbability*100).toFixed(1)}%`],['Practice winners',personalModel.practiceWinners]];
  return <div className="q4Overview">
    <header className="q4Hero"><div><span>QNT / PERSONAL RESEARCH</span><h1>Your quant workspace.</h1><p>Market research, strategy validation, Python modeling and journaling in one place.</p></div><button onClick={()=>go('Research','Workspace')}><Sparkles size={14}/> Open Research Studio</button></header>
    <div className="q4QuickGrid">
      <button onClick={()=>go('Research','Workspace')}><FlaskConical/><span>Research</span><b>Python + Agent</b><small>Build models, test ideas, generate artifacts.</small><ChevronRight/></button>
      <button onClick={()=>go('Research','Validation')}><Activity/><span>Validation</span><b>Test the strategy</b><small>Holdouts, bootstrap, decay, dependence, tails.</small><ChevronRight/></button>
      <button onClick={()=>go('Journal')}><BookOpen/><span>Journal</span><b>Record + refine</b><small>Your migrated trades, new entries and refine bot.</small><ChevronRight/></button>
      <button onClick={()=>runMarket('TOP')}><BarChart3/><span>Markets</span><b>Open terminal</b><small>Monitor, desk, options and quantitative analytics.</small><ChevronRight/></button>
    </div>
    <div className="q4OverviewGrid">
      <section><div className="q4SectionHead"><div><span>MODEL</span><b>Current research sample</b></div><button onClick={()=>go('Research','Validation')}>Open validation</button></div><div className="q4ModelStrip">{model.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><p className="q4Caveat">{personalModel.curationNote}</p></section>
      <section><div className="q4SectionHead"><div><span>WATCH</span><b>Delayed provider snapshot</b></div><button onClick={()=>runMarket('TOP')}>Open monitor</button></div><div className="q4QuoteList">{quotes.map(q=><button key={q.symbol} onClick={()=>runMarket('DES',q.symbol)}><b>{q.symbol}</b><span>{Number.isFinite(q.last)?`$${q.last.toLocaleString(undefined,{maximumFractionDigits:2})}`:'—'}</span><em className={(q.changePct??0)>=0?'up':'down'}>{Number.isFinite(q.changePct)?`${q.changePct>=0?'+':''}${q.changePct.toFixed(2)}%`:'—'}</em></button>)}{!quotes.length&&<div className="q4Muted">{error||'Loading market snapshot…'}</div>}</div></section>
      <section><div className="q4SectionHead"><div><span>SYSTEM</span><b>Connections</b></div><button onClick={()=>go('System')}>Details</button></div><div className="q4HealthRows"><div><i className={health?.server?.ok?'ok':''}/><span>QNT server</span><b>{health?.server?.ok?'Online':'—'}</b></div><div><i className={health?.marketData?.configured?'ok':''}/><span>MarketData</span><b>{health?.marketData?.configured?'Connected':'Not configured'}</b></div><div><i className={health?.openai?.configured?'ok':''}/><span>Research Agent</span><b>{health?.openai?.configured?'Connected':'Not configured'}</b></div></div></section>
    </div>
  </div>
}

function SystemPage(){const[health,setHealth]=useState(null),[error,setError]=useState('');const load=async()=>{try{const r=await fetch('/api/status'),d=await r.json();if(!r.ok)throw new Error(d.error||'Status failed');setHealth(d);setError('')}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);const rows=[['QNT server',health?.server?.ok,health?.server?.now,`${health?.server?.cacheEntries??0} cache entries`],['MarketData.app',health?.marketData?.configured,health?.marketData?.lastSuccess,health?.marketData?.lastError||health?.marketData?.mode],['OpenAI',health?.openai?.configured,health?.openai?.lastSuccess,health?.openai?.lastModel||health?.openai?.models?.fast]];return <div className="q4SimplePage"><header><span>SYSTEM</span><h1>Connections</h1><p>Provider health, cache state and model routing.</p><button onClick={load}>Refresh</button></header>{error&&<div className="q4Error">{error}</div>}<div className="q4SystemCards">{rows.map(([name,ok,last,detail])=><article key={name}><div><i className={ok?'ok':''}/><b>{name}</b><em>{ok?'CONNECTED':'OFFLINE'}</em></div><span>{last?new Date(last).toLocaleString():'No successful request yet'}</span><p>{detail||'—'}</p></article>)}</div></div>}

function CommandPalette({open,onClose,run}){const[q,setQ]=useState('');useEffect(()=>{if(open)setQ('')},[open]);const visible=useMemo(()=>{const s=q.trim().toUpperCase();return COMMANDS.filter(x=>!s||`${x[0]} ${x[1]} ${x[2]}`.toUpperCase().includes(s)).slice(0,18)},[q]);if(!open)return null;return <div className="q4CommandBackdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="q4Command"><div className="q4CommandSearch"><Search size={16}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Enter'){e.preventDefault();run(q||visible[0]?.[0])}}} placeholder="Type a function or command…"/><kbd>ESC</kbd></div><div className="q4CommandRows">{visible.map(x=><button key={x[0]} onClick={()=>run(x[0])}><kbd>{x[0]}</kbd><div><b>{x[1]}</b><span>{x[2]}</span></div><ChevronRight size={14}/></button>)}</div><div className="q4CommandHint">Try DES QQQ · CHAIN AAPL 30 · VALIDATE · JOURNAL</div></div></div>}

export default function QntRedesign(){
  const[section,setSection]=useState('Overview'),[marketPane,setMarketPane]=useState('Workbench'),[commandOpen,setCommandOpen]=useState(false);
  const go=(next,tab)=>{if(section==='Research'&&next!=='Research')emit('qnt:navigate',{type:'research',tab:'Workspace'});setSection(next);if(next==='Research'&&tab)setTimeout(()=>emit('qnt:navigate',{type:'research',tab}),0)};
  const runMarket=(fn='TOP',symbol,dte)=>{let pane='Workbench',event='qnt:workbench-command',key='qnt.workbench.command',detail={fn};if(MARKET_DESK.includes(fn)){pane='Desk';event='qnt:desk-command';key='qnt.desk.command';detail={fn,symbol}}else if(MARKET_ANALYTICS.includes(fn)){pane='Analytics';event='qnt:analytics-command';key='qnt.analytics.command';detail={fn,symbol,dte}}setSection('Markets');setMarketPane(pane);saveSession(key,detail);setTimeout(()=>emit(event,detail),0)};
  const runCommand=raw=>{const parts=String(raw||'').trim().toUpperCase().split(/\s+/).filter(Boolean),fn=parts[0];if(!fn)return;if(fn==='HOME')go('Overview');else if(fn==='JOURNAL')go('Journal');else if(fn==='DATA')go('Data');else if(fn==='API')go('System');else if(researchMap[fn])go('Research',researchMap[fn]);else if(MARKET_WORKBENCH.includes(fn))runMarket(fn);else if(MARKET_DESK.includes(fn)){const symbol=parts.find((x,i)=>i>0&&/^[A-Z][A-Z0-9.\-]{0,11}$/.test(x));runMarket(fn,symbol)}else if(MARKET_ANALYTICS.includes(fn)){const symbol=parts.find((x,i)=>i>0&&/^[A-Z][A-Z0-9.\-]{0,11}$/.test(x)),dte=parts.map(Number).find(x=>Number.isInteger(x)&&x>=0&&x<=730);runMarket(fn,symbol,dte)}setCommandOpen(false)};
  useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommandOpen(true)}if(e.key==='Escape')setCommandOpen(false)},route=e=>{const d=e.detail||{};if(d.section==='Research')go('Research',d.tab||'Workspace');else if(d.section==='Data')go('Data');else if(d.section==='API')go('System');else if(d.section==='Analytics')runMarket(d.fn||'CHAIN',d.symbol,d.dte);else if(d.section==='Workbench')runMarket(d.fn||'TOP');else if(d.section==='Desk'||d.section==='Terminal')runMarket(d.fn||'LAUNCH',d.symbol)};window.addEventListener('keydown',key);window.addEventListener('qnt:route',route);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('qnt:route',route)}},[section]);
  const nav=[['Overview',Home],['Markets',BarChart3],['Research',FlaskConical],['Journal',BookOpen],['Data',Database],['System',Server]];
  return <div className="q4App"><aside className="q4Sidebar"><div className="q4Brand"><span>Q</span><div><b>QNT</b><small>research system</small></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={section===name?'active':''} onClick={()=>go(name)}><Icon size={16}/><span>{name}</span></button>)}</nav><div className="q4SideFoot"><button onClick={()=>setCommandOpen(true)}><Command size={15}/><span>Commands</span><kbd>⌘K</kbd></button><div><i/><span>Local workspace</span></div></div></aside>
    <main className="q4Main"><header className="q4Top"><div className="q4Breadcrumb"><b>QNT</b><ChevronRight size={12}/><span>{section}</span>{section==='Markets'&&<><ChevronRight size={12}/><em>{marketPane}</em></>}</div><button className="q4GlobalSearch" onClick={()=>setCommandOpen(true)}><Search size={14}/><span>Search tools, functions, symbols…</span><kbd>⌘ K</kbd></button><div className="q4TopStatus"><i/><span>Research online</span></div></header>
      <div className="q4Content">{section==='Overview'&&<Overview go={go} runMarket={runMarket}/>} {section==='Markets'&&<div className="q4MarketPage"><div className="q4Subnav"><button className={marketPane==='Workbench'?'active':''} onClick={()=>runMarket('TOP')}>Monitor</button><button className={marketPane==='Desk'?'active':''} onClick={()=>runMarket('LAUNCH')}>Desk</button><button className={marketPane==='Analytics'?'active':''} onClick={()=>runMarket('CHAIN','QQQ')}>Options</button><span>Use ⌘K for every function</span></div><div className="q4ToolFrame">{marketPane==='Workbench'&&<TerminalWorkbench/>}{marketPane==='Desk'&&<BloombergDesk/>}{marketPane==='Analytics'&&<AnalyticsTerminal/>}</div></div>} {section==='Research'&&<div className="q4ToolFrame research"><App/></div>} {section==='Journal'&&<JournalWorkspace/>} {section==='Data'&&<div className="q4ToolFrame data"><DataTerminal/></div>} {section==='System'&&<SystemPage/>}</div>
    </main><CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} run={runCommand}/></div>
}
