import React,{useEffect,useMemo,useRef,useState}from'react';
import{Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis,ZAxis}from'recharts';
import{BarChart3,Box,ChevronDown,FileCode2,FileText,Globe2,LoaderCircle,MessageSquareText,Play,Plus,Send,TerminalSquare,Trash2,Zap}from'lucide-react';
import{personalModel}from'./personalDataset.js';
import ResearchSurface3D from'./ResearchSurface3D.jsx';
import ResearchStats,{calculateTradeStats}from'./ResearchStats.jsx';

const starterFiles=()=>({
  'README.md':`# QNT Research Workspace\n\nUse this workspace to write research code, ask QNT to edit or explain it, run Python analysis, and generate interactive artifacts.\n\nQuick prompts\n- /surface — 3D expectancy sensitivity\n- /bootstrap — bootstrap uncertainty\n- /stress — tail and loss stress\n- /distribution — payoff distribution\n- /factor — provider-backed factor study\n\nImportant\n- The current strategy sample is selectively curated.\n- Normalized payoff units are not true stop-defined R.\n- Direct NQ/MNQ regime claims stay locked until verified futures bars are joined.`,
  'edge_surface.py':`# QNT expectancy sensitivity\nimport numpy as np\n\nwin_rate = ${personalModel.winProbability.toFixed(6)}\nwr_shift = np.linspace(-0.15, 0.15, 13)\npayoff_scale = np.linspace(0.55, 1.45, 13)\n\n# Ask QNT to calculate the expectancy grid and return a 3D surface.`,
  'bootstrap_validation.py':`# QNT bootstrap validation\nimport numpy as np\n\neval_r = np.array(${JSON.stringify(personalModel.evalR)})\nB = 5000\n\n# Estimate expectancy uncertainty and P(expectancy > 0).`,
  'payoff_distribution.py':`# QNT payoff distribution\nimport numpy as np\n\neval_r = np.array(${JSON.stringify(personalModel.evalR)})\nwinner_library = np.array(${JSON.stringify(personalModel.winR)})\nloss_library = np.array(${JSON.stringify(personalModel.lossR)})\n\n# Inspect skew, tails and concentration.`,
  'market_factor_lab.py':`# Provider-backed factor research\nSYMBOLS = ["QQQ", "SPY", "AAPL", "NVDA", "MSFT"]\nLOOKBACK = 252\n\n# Use only market data QNT can verify.\n# Do not substitute ETF data as direct NQ/MNQ futures context.`,
  'regime_join.py':`# Regime join blueprint\n# Trade: timestamp, outcome, symbol, direction\n# Futures: timestamp, OHLCV\n# Features: session, trend, realized vol, opening range, volume context\n# Publish regime results only after a verified timestamp join.`
});

const SKILLS=[
  {code:'/surface',label:'3D surface',prompt:'Use Python Code Interpreter. Build a 13x13 3D sensitivity surface for my current curated model. X = win-rate shift, Y = conservative winner payoff scale, Z = modeled expectancy in R. Return a surface3d QNT artifact and explain the fragile regions.'},
  {code:'/bootstrap',label:'Bootstrap',prompt:'Use Python to bootstrap my curated eval outcomes at least 5000 times. Show expectancy uncertainty, 5/50/95 percentiles and P(expectancy > 0). Return a compact artifact.'},
  {code:'/stress',label:'Stress',prompt:'Stress-test the current payoff model in Python. Compare baseline, remove largest winner, remove top 3 winners, increase losses 25%, and lower win probability by 5 percentage points. Return a table artifact.'},
  {code:'/distribution',label:'Distribution',prompt:'Use Python to analyze the eval payoff distribution and conservative payoff libraries. Return a distribution artifact and compact tail metrics.'},
  {code:'/factor',label:'Factor study',prompt:'Design a provider-backed factor study using only data QNT actually has. Return a table of factor, formula, lookback, source and limitation.'}
];

const WORKSPACE_DATA_KEY='qnt.workspace.data.v1';
const welcomeMessage=text=>({role:'assistant',text:text||'Workspace ready. Ask me to edit, run, research, explain, or inspect your personal quant stats.',mode:'fast'});
const chatId=()=>`CHAT-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const chatTitle=messages=>{const first=(messages||[]).find(m=>m.role==='user'&&String(m.text||'').trim());return first?String(first.text).trim().replace(/\s+/g,' ').slice(0,38):'New research'};
function defaultWorkspaceData(){const id=chatId(),now=new Date().toISOString();return{version:1,files:starterFiles(),activeFile:'edge_surface.py',prompt:'',currentChat:{id,createdAt:now,updatedAt:now,messages:[welcomeMessage()]},chats:[],artifacts:[],selectedArtifact:null,proposal:null,webEnabled:false,deepMode:false,runtimeMode:'fast',centerMode:'code'}}
function loadWorkspaceData(){
  const base=defaultWorkspaceData();
  try{
    const saved=JSON.parse(localStorage.getItem(WORKSPACE_DATA_KEY)||'null');
    if(saved&&typeof saved==='object')return{...base,...saved,files:{...starterFiles(),...(saved.files||{})},artifacts:Array.isArray(saved.artifacts)?saved.artifacts:[],chats:Array.isArray(saved.chats)?saved.chats:[],currentChat:saved.currentChat?.id&&Array.isArray(saved.currentChat?.messages)?saved.currentChat:base.currentChat};
    const legacyFiles=JSON.parse(localStorage.getItem('qnt.workspace.files')||'{}'),legacyArtifacts=JSON.parse(localStorage.getItem('qnt.research.artifacts')||'[]');
    return{...base,files:{...starterFiles(),...(legacyFiles||{})},artifacts:Array.isArray(legacyArtifacts)?legacyArtifacts:[]};
  }catch{return base}
}

function inlineParts(text){return String(text).split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map((part,i)=>part.startsWith('**')&&part.endsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith('`')&&part.endsWith('`')?<code key={i}>{part.slice(1,-1)}</code>:<React.Fragment key={i}>{part}</React.Fragment>)}
function RichText({text}){const lines=String(text||'').replace(/\\\((.*?)\\\)/g,'$1').replace(/\\\[(.*?)\\\]/g,'$1').split('\n');return <div className="qwsRich">{lines.map((line,i)=>{const s=line.trim();if(!s)return <div className="qwsGap" key={i}/>;if(/^#{1,3}\s/.test(s))return <h4 key={i}>{inlineParts(s.replace(/^#{1,3}\s/,''))}</h4>;if(/^[-*]\s+/.test(s))return <div className="qwsBullet" key={i}><span>•</span><p>{inlineParts(s.replace(/^[-*]\s+/,''))}</p></div>;return <p key={i}>{inlineParts(s)}</p>})}</div>}
function parseAgentText(text){let code=null;const artifacts=[];let display=String(text||'');display=display.replace(/<qnt_code>([\s\S]*?)<\/qnt_code>/gi,(_,raw)=>{code=raw.replace(/^\n|\n$/g,'');return''});display=display.replace(/<qnt_artifact>([\s\S]*?)<\/qnt_artifact>/gi,(_,raw)=>{try{const a=JSON.parse(raw);if(a&&typeof a==='object')artifacts.push(a)}catch{}return''});return{display:display.trim(),code,artifacts}}
function streamDisplay(text){return String(text||'').replace(/<qnt_(?:artifact|code)>[\s\S]*$/i,'').trimEnd()}
function normalizeArtifact(raw){const kind=String(raw?.kind||'').toLowerCase(),allowed=['surface3d','line','bar','scatter','table','metrics'];if(!allowed.includes(kind))return null;const base={...raw,kind,id:`ART-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,createdAt:new Date().toISOString(),source:raw.source||'QNT · Python'};if(kind==='surface3d'){const x=Array.isArray(raw.x)?raw.x.slice(0,20):[],y=Array.isArray(raw.y)?raw.y.slice(0,20):[],z=Array.isArray(raw.z)?raw.z.slice(0,20).map(r=>Array.isArray(r)?r.slice(0,20):[]):[];if(x.length<2||y.length<2||!z.length)return null;return{...base,x,y,z}}if(kind==='table')return{...base,columns:(raw.columns||[]).slice(0,12),rows:(raw.rows||[]).slice(0,60)};if(kind==='metrics')return{...base,items:(raw.items||[]).slice(0,16)};return{...base,data:(raw.data||[]).slice(0,250),series:(raw.series||[]).slice(0,8)}}
function ArtifactView({artifact}){if(!artifact)return <div className="qwsEmptyOutput"><Box size={22}/><b>No output yet</b><span>Run Python or ask QNT to create a chart, table, distribution or 3D model.</span></div>;if(artifact.kind==='surface3d')return <ResearchSurface3D artifact={artifact}/>;if(artifact.kind==='metrics')return <div className="qwsMetricOutput">{artifact.items.map((x,i)=><div key={i}><span>{x.label}</span><b>{x.value}</b><small>{x.sub||''}</small></div>)}</div>;if(artifact.kind==='table')return <div className="qwsTableOutput"><div>{artifact.columns.map(c=><b key={c}>{c}</b>)}</div>{artifact.rows.map((r,i)=><div key={i}>{artifact.columns.map((c,j)=><span key={`${i}-${j}`}>{Array.isArray(r)?String(r[j]??'—'):String(r?.[c]??'—')}</span>)}</div>)}</div>;const data=artifact.data||[],series=artifact.series?.length?artifact.series:[{key:'value',label:'Value'}],xKey=artifact.xKey||'x';if(artifact.kind==='scatter')return <ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#202225"/><XAxis type="number" dataKey={artifact.xKey||'x'} tick={{fontSize:9}} stroke="#60646b"/><YAxis type="number" dataKey={artifact.yKey||'y'} tick={{fontSize:9}} stroke="#60646b"/><ZAxis range={[35,35]}/><Tooltip contentStyle={{background:'#111214',border:'1px solid #303238',fontSize:10}}/><Scatter data={data}/></ScatterChart></ResponsiveContainer>;if(artifact.kind==='bar')return <ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid stroke="#202225" vertical={false}/><XAxis dataKey={xKey} tick={{fontSize:9}} stroke="#60646b"/><YAxis tick={{fontSize:9}} stroke="#60646b"/><Tooltip contentStyle={{background:'#111214',border:'1px solid #303238',fontSize:10}}/>{series.map(s=><Bar key={s.key} dataKey={s.key} name={s.label||s.key}/>)}</BarChart></ResponsiveContainer>;return <ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#202225" vertical={false}/><XAxis dataKey={xKey} tick={{fontSize:9}} stroke="#60646b"/><YAxis tick={{fontSize:9}} stroke="#60646b"/><Tooltip contentStyle={{background:'#111214',border:'1px solid #303238',fontSize:10}}/>{series.map(s=><Line key={s.key} dataKey={s.key} name={s.label||s.key} dot={false} strokeWidth={1.4}/>)}</LineChart></ResponsiveContainer>}
function autoPythonIntent(text){return /(?:^\/(?:surface|bootstrap|stress|distribution)|\b(?:run|use|execute)\s+python\b|\b(?:build|generate|create)\b[^\n]{0,40}\b(?:3d|surface|bootstrap|simulation|regression|distribution|chart)\b)/i.test(String(text||''))}
function FileIcon({name}){return name.endsWith('.md')?<FileText size={13}/>:<FileCode2 size={13}/>}
function ActivityRow({icon:Icon,label,detail,state='done'}){return <div className={`qwsActivity ${state}`}><Icon size={13}/><div><b>{label}</b>{detail&&<span>{detail}</span>}</div><em>{state==='active'?<LoaderCircle size={12}/>:state==='done'?'✓':'·'}</em></div>}

export default function ResearchStudio(){
  const[seed]=useState(loadWorkspaceData);
  const[files,setFiles]=useState(seed.files),[activeFile,setActiveFile]=useState(seed.activeFile||'edge_surface.py'),[prompt,setPrompt]=useState(seed.prompt||''),[messages,setMessages]=useState(seed.currentChat?.messages?.length?seed.currentChat.messages:[welcomeMessage()]);
  const[currentChatId,setCurrentChatId]=useState(seed.currentChat?.id||chatId()),[currentChatCreatedAt,setCurrentChatCreatedAt]=useState(seed.currentChat?.createdAt||new Date().toISOString()),[savedChats,setSavedChats]=useState(seed.chats||[]);
  const[artifacts,setArtifacts]=useState(seed.artifacts||[]),[selectedArtifact,setSelectedArtifact]=useState(seed.selectedArtifact||null),[loading,setLoading]=useState(false),[proposal,setProposal]=useState(seed.proposal||null),[webEnabled,setWebEnabled]=useState(Boolean(seed.webEnabled)),[deepMode,setDeepMode]=useState(Boolean(seed.deepMode)),[runtimeMode,setRuntimeMode]=useState(seed.runtimeMode||'fast'),[firstTokenMs,setFirstTokenMs]=useState(null),[centerMode,setCenterMode]=useState(seed.centerMode||'code'),[runState,setRunState]=useState(null),[skillsOpen,setSkillsOpen]=useState(false);
  const editorRef=useRef(null),gutterRef=useRef(null),chatRef=useRef(null),saveTimerRef=useRef(null);
  const code=files[activeFile]??'',lines=useMemo(()=>String(code).split('\n'),[code]),quickStats=useMemo(()=>calculateTradeStats(personalModel.evalR,false),[]);
  const currentChat=useMemo(()=>({id:currentChatId,title:chatTitle(messages),messages,createdAt:currentChatCreatedAt,updatedAt:new Date().toISOString()}),[currentChatId,currentChatCreatedAt,messages]);
  useEffect(()=>{clearTimeout(saveTimerRef.current);saveTimerRef.current=setTimeout(()=>{try{localStorage.setItem(WORKSPACE_DATA_KEY,JSON.stringify({version:1,files,activeFile,prompt,currentChat,chats:savedChats,artifacts,selectedArtifact,proposal,webEnabled,deepMode,runtimeMode,centerMode,savedAt:new Date().toISOString()}));localStorage.removeItem('qnt.workspace.files');localStorage.removeItem('qnt.research.artifacts')}catch{}},180);return()=>clearTimeout(saveTimerRef.current)},[files,activeFile,prompt,currentChat,savedChats,artifacts,selectedArtifact,proposal,webEnabled,deepMode,runtimeMode,centerMode]);
  useEffect(()=>{chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'})},[messages,loading,runState,proposal]);
  const setCode=v=>setFiles(x=>({...x,[activeFile]:v}));
  const addFile=()=>{let i=1,name=`research_${i}.py`;while(files[name]){i++;name=`research_${i}.py`}setFiles(x=>({...x,[name]:'# New QNT research\n'}));setActiveFile(name);setCenterMode('code')};
  const hasUserMessages=list=>(list||[]).some(m=>m.role==='user'&&String(m.text||'').trim());
  const archiveCurrent=cur=>hasUserMessages(messages)?[currentChat,...cur.filter(c=>c.id!==currentChatId)]:cur.filter(c=>c.id!==currentChatId);
  const startNewChat=()=>{if(loading)return;setSavedChats(archiveCurrent);const id=chatId(),now=new Date().toISOString();setCurrentChatId(id);setCurrentChatCreatedAt(now);setMessages([welcomeMessage('New research thread. Ask me to edit, run, research, explain, or inspect your personal quant stats.')]);setPrompt('');setProposal(null);setRunState(null);setRuntimeMode('fast');setFirstTokenMs(null)};
  const openSavedChat=id=>{if(loading||id===currentChatId)return;const target=savedChats.find(c=>c.id===id);if(!target)return;setSavedChats(cur=>{const withoutTarget=cur.filter(c=>c.id!==id&&c.id!==currentChatId);return hasUserMessages(messages)?[currentChat,...withoutTarget]:withoutTarget});setCurrentChatId(target.id);setCurrentChatCreatedAt(target.createdAt||new Date().toISOString());setMessages(Array.isArray(target.messages)&&target.messages.length?target.messages:[welcomeMessage()]);setPrompt('');setProposal(null);setRunState(null);setFirstTokenMs(null)};
  const deleteSavedChat=id=>{if(loading)return;if(!window.confirm('Delete this workspace chat? This cannot be undone.'))return;setSavedChats(cur=>cur.filter(c=>c.id!==id))};
  const deleteCurrentChat=()=>{if(loading)return;if(!window.confirm('Delete this workspace chat? This cannot be undone.'))return;const id=chatId(),now=new Date().toISOString();setCurrentChatId(id);setCurrentChatCreatedAt(now);setMessages([welcomeMessage('New research thread. Ask me to edit, run, research, explain, or inspect your personal quant stats.')]);setPrompt('');setProposal(null);setRunState(null);setFirstTokenMs(null)};
  const ingestArtifacts=raw=>{const next=raw.map(normalizeArtifact).filter(Boolean);if(!next.length)return[];setArtifacts(cur=>[...next,...cur].slice(0,12));setSelectedArtifact(next[0].id);setCenterMode('output');return next};
  const send=async(override=null,forcePython=false)=>{
    const text=String(override??prompt).trim();if(!text||loading)return;
    const prior=messages,streamId=`qnt-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,started=performance.now();let rawText='',sawFirst=false;
    const usePython=Boolean(forcePython||deepMode||autoPythonIntent(text)),requestedMode=deepMode?'deep':(usePython||webEnabled?'research':'fast');
    setRuntimeMode(requestedMode);setFirstTokenMs(null);setRunState({usePython,web:webEnabled,phase:'routing'});setMessages([...prior,{role:'user',text},{role:'assistant',text:'',mode:requestedMode,streamId}]);setPrompt('');setProposal(null);setLoading(true);
    try{
      const researchContext=[`Curated eval ideas: ${personalModel.evalPositionIdeas}.`,`Current raw sample expectancy: ${quickStats?.mean?.toFixed(4)??'n/a'} normalized R per trade.`,`Current sample profit factor: ${quickStats?.pf===Infinity?'infinite':quickStats?.pf?.toFixed(4)??'n/a'}.`,`Current sample standard deviation: ${quickStats?.sd?.toFixed(4)??'n/a'} normalized R.`,`Current sample expected shortfall at the worst 10% tail: ${quickStats?.es10?.toFixed(4)??'n/a'} normalized R.`,personalModel.curationNote,'Normalized payoff units are not stop-defined true R. Sequence statistics require verified chronological trade order.','Direct NQ/MNQ regime claims require verified futures bars joined to trade timestamps.'].join('\n');
      const modelSummary={evalIdeas:personalModel.evalPositionIdeas,wins:personalModel.evalWins,losses:personalModel.evalLosses,breakevens:personalModel.evalBreakevens,winProbability:personalModel.winProbability,lossProbability:personalModel.lossProbability,breakevenProbability:personalModel.breakevenProbability,expectancy:quickStats?.mean,profitFactor:quickStats?.pf,payoffRatio:quickStats?.payoff,standardDeviation:quickStats?.sd,downsideDeviation:quickStats?.downside,skewness:quickStats?.skew,excessKurtosis:quickStats?.kurt,expectedShortfall10:quickStats?.es10,top5ProfitShare:quickStats?.top5};
      const screenContext={module:'Research Workspace',activeFile,workspace:'QNT research',webResearch:webEnabled,artifactCount:artifacts.length,personalModel:usePython?{...modelSummary,evalR:personalModel.evalR,winR:personalModel.winR,lossR:personalModel.lossR}:modelSummary};
      const reqMessage=usePython?`${text}\n\nUse Python Code Interpreter when calculation is required and return a QNT artifact when a visualization materially helps.`:text;
      const res=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:reqMessage,history:prior,activeFile,code,researchContext,screenContext,allowWeb:webEnabled,usePython,mode:requestedMode})});
      if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.error||'Research request failed')}
      setRunState(s=>({...s,phase:'working'}));
      const contentType=res.headers.get('content-type')||'';
      if(contentType.includes('application/x-ndjson')&&res.body){
        const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';
        const applyEvent=event=>{if(event.type==='meta'){setRuntimeMode(event.mode||requestedMode);setMessages(prev=>prev.map(m=>m.streamId===streamId?{...m,mode:event.mode||requestedMode,model:event.model}:m));return}if(event.type==='delta'&&typeof event.delta==='string'){if(!sawFirst){sawFirst=true;setFirstTokenMs(Math.round(performance.now()-started));setRunState(s=>({...s,phase:'answering'}))}rawText+=event.delta;const visible=streamDisplay(rawText);setMessages(prev=>prev.map(m=>m.streamId===streamId?{...m,text:visible}:m));return}if(event.type==='error')throw new Error(event.error||'Research stream failed')};
        while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let nl;while((nl=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,nl).trim();buffer=buffer.slice(nl+1);if(!line)continue;try{applyEvent(JSON.parse(line))}catch(e){if(e instanceof SyntaxError)continue;throw e}}}
        buffer+=decoder.decode();if(buffer.trim()){try{applyEvent(JSON.parse(buffer.trim()))}catch(e){if(!(e instanceof SyntaxError))throw e}}
      }else{const data=await res.json();rawText=data.text||'';setRuntimeMode(data.mode||requestedMode)}
      const parsed=parseAgentText(rawText),created=ingestArtifacts(parsed.artifacts);setMessages(prev=>prev.map(m=>m.streamId===streamId?{role:'assistant',text:parsed.display||'Research run completed.',mode:requestedMode}:m));if(parsed.code)setProposal({file:activeFile,code:parsed.code});setRunState({usePython,web:webEnabled,phase:'done',edited:Boolean(parsed.code),artifactCount:created.length});
    }catch(e){setMessages(prev=>prev.map(m=>m.streamId===streamId?{role:'assistant',text:`Research error: ${e.message}`,mode:requestedMode}:m));setRunState({usePython,web:webEnabled,phase:'error'})}finally{setLoading(false)}
  };
  const runActive=()=>send(`Execute the active file "${activeFile}" with Python. Validate assumptions, compute the result, and return the best matching QNT artifact. Do not invent unavailable data.`,true);
  const applyProposal=()=>{if(!proposal)return;setFiles(x=>({...x,[proposal.file]:proposal.code}));setActiveFile(proposal.file);setCenterMode('code');setMessages(x=>[...x,{role:'assistant',text:`Applied the proposed replacement to ${proposal.file}.`,mode:'fast'}]);setProposal(null);setRunState(s=>s?{...s,edited:true}:s)};
  useEffect(()=>{const h=e=>{if(e.detail?.prompt)send(e.detail.prompt)};window.addEventListener('qnt:copilot-prompt',h);return()=>window.removeEventListener('qnt:copilot-prompt',h)},[messages,files,activeFile,loading,webEnabled,deepMode,artifacts]);
  const selected=artifacts.find(a=>a.id===selectedArtifact)||artifacts[0]||null;
  const title=centerMode==='stats'?'Personal quantitative statistics':activeFile==='README.md'?'QNT Research Workspace':activeFile.replace(/\.[^.]+$/,'').replaceAll('_',' ');
  return <div className="qwsStudio">
    <aside className="qwsExplorer">
      <div className="qwsExplorerHead"><span>WORKSPACE</span><button onClick={addFile} title="New file"><Plus size={13}/></button></div>
      <div className="qwsTree">{Object.keys(files).map(name=><button key={name} className={activeFile===name&&centerMode==='code'?'active':''} onClick={()=>{setActiveFile(name);setCenterMode('code')}}><FileIcon name={name}/><span>{name}</span>{activeFile===name&&loading?<LoaderCircle className="spin" size={11}/>:null}</button>)}</div>
      <div className="qwsChatHistory"><div className="qwsChatHistoryHead"><span>CHATS</span><button onClick={startNewChat} disabled={loading} title="New chat"><Plus size={12}/></button></div><div className="qwsChatRow active"><button className="qwsChatOpen" title={chatTitle(messages)}><MessageSquareText size={12}/><span>{chatTitle(messages)}</span><small>open</small></button><button className="qwsChatDelete" onClick={deleteCurrentChat} disabled={loading} title="Delete chat"><Trash2 size={11}/></button></div>{savedChats.map(chat=><div className="qwsChatRow" key={chat.id}><button className="qwsChatOpen" onClick={()=>openSavedChat(chat.id)} disabled={loading} title={chat.title||chatTitle(chat.messages)}><MessageSquareText size={12}/><span>{chat.title||chatTitle(chat.messages)}</span><small>{Math.max(0,(chat.messages?.length||1)-1)} msgs</small></button><button className="qwsChatDelete" onClick={()=>deleteSavedChat(chat.id)} disabled={loading} title="Delete chat"><Trash2 size={11}/></button></div>)}</div>
      <button className={`qwsPersonalStatsLink ${centerMode==='stats'?'active':''}`} onClick={()=>setCenterMode('stats')}><BarChart3 size={13}/><span>personal_stats</span><small>quant</small></button>
      <div className="qwsExplorerFoot"><span>MODEL CONTEXT</span><div><b>{quickStats?`${quickStats.mean>=0?'+':''}${quickStats.mean.toFixed(2)}R`:'—'}</b><small>sample EV</small></div><div><b>{quickStats?.pf===Infinity?'∞':quickStats?.pf?.toFixed(2)||'—'}</b><small>profit factor</small></div><p>{personalModel.evalPositionIdeas} observations · selective sample</p><p className="qwsDataPoint">1 workspace data point · autosaved</p></div>
    </aside>

    <section className="qwsEditorPane">
      <div className="qwsTabs"><button className={centerMode==='code'?'active':''} onClick={()=>setCenterMode('code')}><FileIcon name={activeFile}/><span>{activeFile}</span><em>×</em></button><button className={centerMode==='stats'?'active':''} onClick={()=>setCenterMode('stats')}><BarChart3 size={12}/><span>Personal Stats</span></button>{selected&&<button className={centerMode==='output'?'active':''} onClick={()=>setCenterMode('output')}><Box size={12}/><span>{selected.title||'Research output'}</span></button>}<div className="qwsEditorActions"><button onClick={runActive} disabled={loading}><Play size={12}/> Run</button></div></div>
      {centerMode==='code'&&<div className="qwsCodeShell"><div className="qwsGutter" ref={gutterRef}>{lines.map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea ref={editorRef} value={code} onChange={e=>setCode(e.target.value)} onScroll={e=>{if(gutterRef.current)gutterRef.current.scrollTop=e.currentTarget.scrollTop}} spellCheck="false" className="qwsCode"/></div>}
      {centerMode==='stats'&&<ResearchStats/>}
      {centerMode==='output'&&<div className="qwsOutput"><div className="qwsOutputHead"><div><span>OUTPUT</span><b>{selected?.title||'Research artifact'}</b><small>{selected?.source||'QNT Python'}</small></div><div className="qwsArtifactPicker">{artifacts.slice(0,5).map(a=><button className={selected?.id===a.id?'active':''} key={a.id} onClick={()=>setSelectedArtifact(a.id)}>{a.kind}</button>)}</div></div><div className="qwsOutputCanvas"><ArtifactView artifact={selected}/></div>{selected?.note&&<div className="qwsOutputNote">{selected.note}</div>}</div>}
    </section>

    <aside className="qwsAgentPane">
      <div className="qwsAgentHead"><div><b>{title}</b><span>{runtimeMode.toUpperCase()}{firstTokenMs!=null?` · ${firstTokenMs}ms`:''} · SAVED</span></div><button onClick={startNewChat} disabled={loading} title="New chat"><Plus size={13}/></button></div>
      <div className="qwsConversation" ref={chatRef}>{messages.map((m,i)=>m.role==='user'?<div className="qwsUserMessage" key={m.streamId||i}>{m.text}</div>:<div className="qwsAssistantMessage" key={m.streamId||i}><RichText text={m.text||''}/></div>)}
        {runState&&<div className="qwsActivityStack">
          {runState.web&&<ActivityRow icon={Globe2} label="Web research" detail="Current external research enabled" state={runState.phase==='routing'?'active':'done'}/>} 
          {runState.usePython&&<ActivityRow icon={TerminalSquare} label="Python analysis" detail="Code Interpreter research runtime" state={['routing','working'].includes(runState.phase)?'active':'done'}/>} 
          <ActivityRow icon={Zap} label={runState.phase==='error'?'Research request failed':'Research agent'} detail={runState.phase==='done'?'Response complete':runState.phase==='answering'?'Streaming answer':runState.phase==='working'?'Running enabled tools':'Routing request'} state={runState.phase==='error'?'error':runState.phase==='done'?'done':'active'}/>
          {runState.artifactCount>0&&<ActivityRow icon={Box} label="Artifact created" detail={`${runState.artifactCount} output${runState.artifactCount===1?'':'s'} ready`} state="done"/>}
        </div>}
        {proposal&&<div className="qwsEditCard"><div><FileCode2 size={13}/><span><b>Editing</b><small>{proposal.file}</small></span></div><button onClick={applyProposal}>Apply change</button></div>}
      </div>
      <div className="qwsComposer">
        <div className="qwsSkillMenu"><button onClick={()=>setSkillsOpen(v=>!v)}>Tools <ChevronDown size={11}/></button>{skillsOpen&&<div>{SKILLS.map(s=><button key={s.code} onClick={()=>{setSkillsOpen(false);send(s.prompt,true)}}><kbd>{s.code}</kbd><span>{s.label}</span></button>)}</div>}</div>
        <textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask QNT to edit, run, research, explain, or analyze your stats…"/>
        <div className="qwsComposerBar"><div><button className="active"><Zap size={11}/> Auto</button><button className={webEnabled?'active':''} onClick={()=>setWebEnabled(v=>!v)}><Globe2 size={11}/> Web</button><button className={deepMode?'active':''} onClick={()=>setDeepMode(v=>!v)}>Deep</button></div><button className="qwsSend" onClick={()=>send()} disabled={loading||!prompt.trim()}>{loading?<LoaderCircle className="spin" size={14}/>:<Send size={14}/>}</button></div>
      </div>
    </aside>
  </div>;
}
