import React,{useEffect,useMemo,useRef,useState}from'react';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
function rotate(p,yaw,pitch){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp,z2=p.y*sp+z*cp;return{x,y,z:z2}}
function plasma(t){const s=[[55,20,95],[106,35,160],[189,54,161],[246,104,91],[253,185,65],[247,239,123]],x=clamp(t,0,1)*(s.length-1),i=Math.min(s.length-2,Math.floor(x)),f=x-i,a=s[i],b=s[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
const fmt=v=>Number.isFinite(Number(v))?Math.abs(Number(v))>=100?Number(v).toFixed(0):Math.abs(Number(v))>=10?Number(v).toFixed(1):Number(v).toFixed(2):String(v??'—');
function smoothGrid(artifact){
  const xs=Array.isArray(artifact?.x)?artifact.x.slice(0,20).map(Number):[],ys=Array.isArray(artifact?.y)?artifact.y.slice(0,20).map(Number):[],grid=Array.isArray(artifact?.z)?artifact.z.slice(0,20).map(r=>Array.isArray(r)?r.slice(0,20).map(Number):[]):[];
  if(xs.length<2||ys.length<2)return{points:[],min:0,max:1};
  const tx=Math.min(34,Math.max(xs.length,Math.round(xs.length*2.4))),ty=Math.min(34,Math.max(ys.length,Math.round(ys.length*2.4))),values=[];
  const sample=(u,v)=>{const gx=u*(xs.length-1),gy=v*(ys.length-1),x0=Math.floor(gx),x1=Math.min(xs.length-1,x0+1),y0=Math.floor(gy),y1=Math.min(ys.length-1,y0+1),fx=gx-x0,fy=gy-y0,a=Number(grid?.[y0]?.[x0]),b=Number(grid?.[y0]?.[x1]),c=Number(grid?.[y1]?.[x0]),d=Number(grid?.[y1]?.[x1]);if([a,b,c,d].every(Number.isFinite))return lerp(lerp(a,b,fx),lerp(c,d,fx),fy);const valid=[a,b,c,d].filter(Number.isFinite);return valid.length?valid[0]:null};
  for(let yi=0;yi<ty;yi++)for(let xi=0;xi<tx;xi++){const value=sample(xi/(tx-1),yi/(ty-1));if(Number.isFinite(value))values.push(value)}
  const min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1,span=max-min||1;
  const points=Array.from({length:tx},(_,xi)=>Array.from({length:ty},(_,yi)=>{const u=xi/(tx-1),v=yi/(ty-1),value=sample(u,v),xPos=(xi-(tx-1)/2)*(15/Math.max(1,tx-1)),zPos=(yi-(ty-1)/2)*(10/Math.max(1,ty-1)),xIndex=u*(xs.length-1),yIndex=v*(ys.length-1),x0=Math.floor(xIndex),x1=Math.min(xs.length-1,x0+1),y0=Math.floor(yIndex),y1=Math.min(ys.length-1,y0+1);return{x:xPos,y:Number.isFinite(value)?-((value-min)/span)*2.55:0,z:zPos,value:Number.isFinite(value)?value:null,xValue:lerp(xs[x0],xs[x1],xIndex-x0),yValue:lerp(ys[y0],ys[y1],yIndex-y0)}}));
  return{points,min,max};
}

export default function ResearchSurface3D({artifact}){
  const canvasRef=useRef(null),projectedRef=useRef([]),drawRef=useRef(null),frameRef=useRef(0),inertiaRef=useRef(0),hoverFrameRef=useRef(0),dragRef=useRef(null),viewRef=useRef({yaw:-.7,pitch:.56,zoom:1}),velocityRef=useRef({yaw:0,pitch:0});
  const[hover,setHover]=useState(null),mesh=useMemo(()=>smoothGrid(artifact),[artifact]);
  const scheduleDraw=()=>{if(frameRef.current)return;frameRef.current=requestAnimationFrame(()=>{frameRef.current=0;drawRef.current?.()})};
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;const draw=()=>{const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const{yaw,pitch,zoom}=viewRef.current;ctx.setTransform(canvas.width/w,0,0,canvas.height/h,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#08090a';ctx.fillRect(0,0,w,h);const project=p=>{const r=rotate(p,yaw,pitch),depth=8+r.z,scale=(148*zoom)/Math.max(3.9,depth);return{x:w/2+r.x*scale,y:h/2+r.y*scale+10,z:r.z}};ctx.strokeStyle='rgba(115,120,130,.10)';ctx.lineWidth=.6;for(let i=0;i<9;i++){const y=h*.13+i*(h*.68)/8;ctx.beginPath();ctx.moveTo(w*.055,y);ctx.lineTo(w*.95,y);ctx.stroke()}for(let i=0;i<11;i++){const x=w*.055+i*(w*.895)/10;ctx.beginPath();ctx.moveTo(x,h*.13);ctx.lineTo(x,h*.81);ctx.stroke()}const projected=[],faces=[];for(let xi=0;xi<mesh.points.length;xi++){projected[xi]=[];for(let yi=0;yi<(mesh.points[xi]?.length||0);yi++){const q=project(mesh.points[xi][yi]);projected[xi][yi]={...q,...mesh.points[xi][yi]}}}for(let x=0;x<mesh.points.length-1;x++)for(let y=0;y<(mesh.points[x]?.length||0)-1;y++){const raw=[mesh.points[x][y],mesh.points[x+1][y],mesh.points[x+1][y+1],mesh.points[x][y+1]];if(raw.some(p=>!Number.isFinite(p.value)))continue;const pts=raw.map(project);faces.push({pts,depth:pts.reduce((s,p)=>s+p.z,0)/4,value:raw.reduce((s,p)=>s+p.value,0)/4})}faces.sort((a,b)=>a.depth-b.depth);for(const face of faces){const t=clamp((face.value-mesh.min)/(mesh.max-mesh.min||1),0,1);ctx.beginPath();ctx.moveTo(face.pts[0].x,face.pts[0].y);for(let i=1;i<4;i++)ctx.lineTo(face.pts[i].x,face.pts[i].y);ctx.closePath();ctx.fillStyle=plasma(t);ctx.globalAlpha=.94;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=.34;ctx.stroke()}projectedRef.current=projected.flat().filter(p=>Number.isFinite(p.value));ctx.fillStyle='#8b9099';ctx.font='9px ui-monospace,monospace';ctx.fillText(`${artifact?.zLabel||'VALUE'} ↑`,12,18);ctx.fillText(`${artifact?.xLabel||'X'} →`,Math.max(12,w-110),h-13);ctx.fillText(artifact?.yLabel||'Y',12,h-13)};drawRef.current=draw;const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));scheduleDraw()};const ro=new ResizeObserver(resize);ro.observe(canvas);resize();return()=>{ro.disconnect();drawRef.current=null;if(frameRef.current)cancelAnimationFrame(frameRef.current);if(inertiaRef.current)cancelAnimationFrame(inertiaRef.current);if(hoverFrameRef.current)cancelAnimationFrame(hoverFrameRef.current)}},[mesh,artifact]);
  const startInertia=()=>{if(inertiaRef.current)cancelAnimationFrame(inertiaRef.current);const tick=()=>{const v=velocityRef.current;v.yaw*=.91;v.pitch*=.91;if(Math.abs(v.yaw)+Math.abs(v.pitch)<.00035){inertiaRef.current=0;return}viewRef.current.yaw+=v.yaw;viewRef.current.pitch=clamp(viewRef.current.pitch+v.pitch,-.18,1.15);scheduleDraw();inertiaRef.current=requestAnimationFrame(tick)};inertiaRef.current=requestAnimationFrame(tick)};
  const down=e=>{if(inertiaRef.current){cancelAnimationFrame(inertiaRef.current);inertiaRef.current=0}dragRef.current={x:e.clientX,y:e.clientY,t:performance.now()};velocityRef.current={yaw:0,pitch:0};canvasRef.current?.setPointerCapture?.(e.pointerId)};
  const move=e=>{const drag=dragRef.current;if(drag){const now=performance.now(),dt=Math.max(8,now-drag.t),dx=e.clientX-drag.x,dy=e.clientY-drag.y,dyaw=dx*.0072,dpitch=dy*.0072;viewRef.current.yaw+=dyaw;viewRef.current.pitch=clamp(viewRef.current.pitch+dpitch,-.18,1.15);velocityRef.current={yaw:dyaw*(16.67/dt),pitch:dpitch*(16.67/dt)};drag.x=e.clientX;drag.y=e.clientY;drag.t=now;scheduleDraw();return}if(hoverFrameRef.current)return;const target=e.currentTarget,clientX=e.clientX,clientY=e.clientY;hoverFrameRef.current=requestAnimationFrame(()=>{hoverFrameRef.current=0;const r=target.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;let best=null,dist=Infinity;for(const p of projectedRef.current){const dd=Math.hypot(p.x-x,p.y-y);if(dd<dist){dist=dd;best=p}}setHover(dist<=12?{...best,x,y}:null)})};
  const up=()=>{if(!dragRef.current)return;dragRef.current=null;startInertia()};
  const wheel=e=>{e.preventDefault();viewRef.current.zoom=clamp(viewRef.current.zoom*Math.exp(-e.deltaY*.0012),.62,2.05);scheduleDraw()};
  return <div className="qrsSurfaceWrap"><canvas ref={canvasRef} className="qrsSurfaceCanvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onPointerLeave={()=>{up();setHover(null)}} onWheel={wheel}/><div className="qrsSurfaceLegend"><span>LOW</span><i/><span>HIGH</span></div><div className="qrsSurfaceHint">drag with inertia · wheel zoom · smoothed mesh</div>{hover&&<div className="qrsSurfaceTip" style={{left:clamp(hover.x+12,8,520),top:clamp(hover.y-48,8,340)}}><b>{artifact?.zLabel||'Value'} {fmt(hover.value)}</b><span>{artifact?.xLabel||'X'} {fmt(hover.xValue)}</span><span>{artifact?.yLabel||'Y'} {fmt(hover.yValue)}</span></div>}</div>;
}
