import React,{useEffect,useMemo,useRef,useState}from'react';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function rotate(p,yaw,pitch){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp,z2=p.y*sp+z*cp;return{x,y,z:z2}}
function plasma(t){const s=[[55,20,95],[106,35,160],[189,54,161],[246,104,91],[253,185,65],[247,239,123]],x=clamp(t,0,1)*(s.length-1),i=Math.min(s.length-2,Math.floor(x)),f=x-i,a=s[i],b=s[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
const fmt=v=>Number.isFinite(Number(v))?Math.abs(Number(v))>=100?Number(v).toFixed(0):Math.abs(Number(v))>=10?Number(v).toFixed(1):Number(v).toFixed(2):String(v??'—');

export default function ResearchSurface3D({artifact}){
  const canvasRef=useRef(null),dragRef=useRef(null),projectedRef=useRef([]);const[yaw,setYaw]=useState(-.7),[pitch,setPitch]=useState(.56),[zoom,setZoom]=useState(1),[hover,setHover]=useState(null);
  const mesh=useMemo(()=>{const xs=Array.isArray(artifact?.x)?artifact.x.slice(0,20):[],ys=Array.isArray(artifact?.y)?artifact.y.slice(0,20):[],grid=Array.isArray(artifact?.z)?artifact.z.slice(0,20):[],vals=grid.flat().map(Number).filter(Number.isFinite),min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):1,span=max-min||1,points=xs.map((x,xi)=>ys.map((y,yi)=>{const value=Number(grid?.[yi]?.[xi]);return{x:(xi-(xs.length-1)/2)*1.18,y:-((Number.isFinite(value)?value:min)-min)/span*2.45,z:(yi-(ys.length-1)/2)*.78,value:Number.isFinite(value)?value:null,xValue:x,yValue:y}}));return{points,min,max}},[artifact]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d'),dpr=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#050507';ctx.fillRect(0,0,w,h);const project=p=>{const r=rotate(p,yaw,pitch),depth=8+r.z,scale=(145*zoom)/Math.max(3.8,depth);return{x:w/2+r.x*scale,y:h/2+r.y*scale+12,z:r.z}};ctx.strokeStyle='rgba(117,119,132,.13)';ctx.lineWidth=.7;for(let i=0;i<10;i++){const y=h*.12+i*(h*.7)/9;ctx.beginPath();ctx.moveTo(w*.05,y);ctx.lineTo(w*.95,y);ctx.stroke()}for(let i=0;i<12;i++){const x=w*.05+i*(w*.9)/11;ctx.beginPath();ctx.moveTo(x,h*.12);ctx.lineTo(x,h*.82);ctx.stroke()}const projected=[],faces=[];for(let xi=0;xi<mesh.points.length;xi++){projected[xi]=[];for(let yi=0;yi<(mesh.points[xi]?.length||0);yi++){const q=project(mesh.points[xi][yi]);projected[xi][yi]={...q,...mesh.points[xi][yi]}}}for(let x=0;x<mesh.points.length-1;x++)for(let y=0;y<(mesh.points[x]?.length||0)-1;y++){const raw=[mesh.points[x][y],mesh.points[x+1][y],mesh.points[x+1][y+1],mesh.points[x][y+1]];if(raw.some(p=>!Number.isFinite(p.value)))continue;const pts=raw.map(project);faces.push({pts,depth:pts.reduce((s,p)=>s+p.z,0)/4,value:raw.reduce((s,p)=>s+p.value,0)/4})}faces.sort((a,b)=>a.depth-b.depth);for(const face of faces){const t=clamp((face.value-mesh.min)/(mesh.max-mesh.min||1),0,1);ctx.beginPath();ctx.moveTo(face.pts[0].x,face.pts[0].y);for(let i=1;i<4;i++)ctx.lineTo(face.pts[i].x,face.pts[i].y);ctx.closePath();ctx.fillStyle=plasma(t);ctx.globalAlpha=.9;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='rgba(255,255,255,.17)';ctx.stroke()}for(const p of projected.flat()){if(!Number.isFinite(p.value))continue;ctx.fillStyle='rgba(255,255,255,.48)';ctx.beginPath();ctx.arc(p.x,p.y,1.05,0,Math.PI*2);ctx.fill()}projectedRef.current=projected.flat().filter(p=>Number.isFinite(p.value));ctx.fillStyle='#8b9099';ctx.font='9px ui-monospace,monospace';ctx.fillText(`${artifact?.zLabel||'VALUE'} ↑`,12,18);ctx.fillText(`${artifact?.xLabel||'X'} →`,Math.max(12,w-110),h-13);ctx.fillText(artifact?.yLabel||'Y',12,h-13)},[artifact,mesh,yaw,pitch,zoom]);
  const down=e=>{dragRef.current={x:e.clientX,y:e.clientY,yaw,pitch};canvasRef.current?.setPointerCapture?.(e.pointerId)};
  const move=e=>{if(dragRef.current){const d=dragRef.current;setYaw(d.yaw+(e.clientX-d.x)*.008);setPitch(clamp(d.pitch+(e.clientY-d.y)*.008,-.15,1.15));return}const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=null,dist=Infinity;for(const p of projectedRef.current){const dd=Math.hypot(p.x-x,p.y-y);if(dd<dist){dist=dd;best=p}}setHover(dist<=14?{...best,x,y}:null)};
  const up=()=>{dragRef.current=null};
  return <div className="qrsSurfaceWrap"><canvas ref={canvasRef} className="qrsSurfaceCanvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onPointerLeave={()=>{up();setHover(null)}} onWheel={e=>{e.preventDefault();setZoom(v=>clamp(v*(e.deltaY>0 ? .92 : 1.08),.62,2.05))}}/><div className="qrsSurfaceLegend"><span>LOW</span><i/><span>HIGH</span></div><div className="qrsSurfaceHint">drag rotate · wheel zoom · hover mesh</div>{hover&&<div className="qrsSurfaceTip" style={{left:clamp(hover.x+12,8,520),top:clamp(hover.y-48,8,340)}}><b>{artifact?.zLabel||'Value'} {fmt(hover.value)}</b><span>{artifact?.xLabel||'X'} {fmt(hover.xValue)}</span><span>{artifact?.yLabel||'Y'} {fmt(hover.yValue)}</span></div>}</div>;
}
