import React,{useEffect,useMemo,useState}from'react';
import{Area,AreaChart,Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis,ZAxis}from'recharts';
import{Box,Braces,Database,FileCode2,Folder,Globe2,MessageSquareText,Play,Plus,Search,Sparkles,Table2,WandSparkles,Zap}from'lucide-react';
import{personalModel}from'./personalDataset.js';
import ResearchSurface3D from'./ResearchSurface3D.jsx';

const mean=a=>a.reduce((s,v)=>s+v,0)/(a.length||1);
const sd=a=>{const m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)**2)))};
const fmt=n=>Number.isFinite(Number(n))?Number(n).toFixed(2):'—';
const fmtPct=n=>Number.isFinite(Number(n))?`${Number(n).toFixed(1)}%`:'—';
const starterFiles=()=>({
  'edge_surface.py':`# QNT Python research cell\n# Ask Copilot to run this with Python and return an interactive 3D artifact.\n\nimport numpy as np\n\nwin_rate = ${personalModel.winProbability.toFixed(6)}\navg_win = None  # QNT fills this from the conservative payoff library\navg_loss = None\n\nwr_shift = np.linspace(-0.15, 0.15, 13)\npayoff_scale = np.linspace(0.55, 1.45, 13)\n\n# z = modeled expectancy across probability/payoff assumptions\n# Copilot should calculate the grid in Python and emit a surface3d artifact.`,
  'bootstrap_validation.py':`# QNT bootstrap validation\n# Use Python to resample the curated eval outcomes and estimate uncertainty.\n\nimport numpy as np\n\neval_r = np.array(${JSON.stringify(personalModel.evalR)})\nB = 5000\n# Report expectancy distribution, 5/50/95 percentiles, P(expectancy > 0),\n# and a compact histogram artifact.`,
  'payoff_distribution.py':`# QNT payoff distribution\nimport numpy as np\n\neval_r = np.array(${JSON.stringify(personalModel.evalR)})\nwinner_library = np.array(${JSON.stringify(personalModel.winR)})\nloss_library = np.array(${JSON.stringify(personalModel.lossR)})\n\n# Compare eval outcomes with conservative transformed payoff libraries.\n# Return a histogram + summary metrics artifact.`,
  'market_factor_lab.py':`# QNT market-factor research draft\n# MarketData-backed equity/ETF data can support returns, realized vol,\n# drawdown, beta, correlation, relative strength and volume studies.\n# Direct NQ/MNQ regime claims remain disabled until verified futures bars are joined.\n\nSYMBOLS = ["QQQ", "SPY", "AAPL", "NVDA", "MSFT"]\nLOOKBACK = 252\n`,
  'regime_join.py':`# QNT regime join blueprint\n# Required trade fields: timestamp, pnl/outcome, symbol, direction.\n# Required verified futures context: timestamp, open, high, low, close, volume.\n# Derived features: session, minute-of-day, trend, RV, opening range, volume z-score.\n# Do not publish regime WR/EV until the timestamp join is complete.`,
  'trade_log.csv':`source,status,count\neval,curated position ideas,${personalModel.evalPositionIdeas}\neval,winning ideas,${personalModel.evalWins}\neval,losing ideas,${personalModel.evalLosses}\neval,breakeven ideas,${personalModel.evalBreakevens}\npractice,vetted winner payoff library,${personalModel.practiceWinners}`,
  'notes.md':`# QNT research notes\n\n- Curated model: ${personalModel.evalPositionIdeas} eval ideas.\n- Observed win rate: ${(personalModel.winProbability*100).toFixed(1)}%.\n- The sample is selectively curated; treat uncertainty seriously.\n- Normalized payoff units are not stop-defined true R.\n- Use Python artifacts for sensitivity, bootstrap, distributions and model diagnostics.\n- Regime results require verified futures context before publication.`
});

const SKILLS=[
  {code:'/surface',title:'3D sensitivity',desc:'Python expectancy surface across win-rate and payoff assumptions',prompt:'Use Python code interpreter. Build a 13x13 3D sensitivity surface for my current curated model. X axis = win-rate shift in percentage points, Y axis = conservative winner payoff scale, Z axis = modeled expectancy in R. Return a surface3d QNT artifact and explain the fragile regions.'},
  {code:'/bootstrap',title:'Bootstrap validation',desc:'Resample the eval sample and quantify uncertainty',prompt:'Use Python to bootstrap my curated eval outcomes at least 5000 times. Show expectancy uncertainty, 5/50/95 percentiles and P(expectancy > 0). Return a bar or line artifact plus a metrics artifact. Do not treat the result as a guarantee.'},
  {code:'/stress',title:'Tail stress',desc:'Remove large winners and worsen losses to test fragility',prompt:'Stress-test the current payoff model in Python. Compare baseline, remove largest winner, remove top 3 winners, increase losses 25%, and lower win probability by 5 percentage points. Return a table artifact and concise findings.'},
  {code:'/distribution',title:'Payoff distribution',desc:'Inspect skew, tails and concentration',prompt:'Use Python to analyze the eval payoff distribution and the conservative winner/loss libraries. Return a histogram/bar artifact and metrics for mean, median, standard deviation, skew direction, largest winner share and downside tail.'},
  {code:'/factor',title:'Factor study',desc:'Design measurable market factors from current provider data',prompt:'Design a provider-backed factor study using only data QNT actually has: stock/ETF OHLCV plus options-chain fields when available. Create a table artifact listing factor, formula, lookback, required source and limitation. Keep NQ/MNQ regime claims disabled without verified futures data.'},
  {code:'/report',title:'Research memo',desc:'Turn current evidence into a decision-ready memo',prompt:'Create a compact research memo for the current model: evidence, uncertainty, sensitivity, missing data, next experiments and invalid claims to avoid. Use the workspace context and current artifacts.'},
];

function inlineParts(text){return String(text).split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map((part,i)=>part.startsWith('**')&&part.endsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith('`')&&part.endsWith('`')?<code key={i}>{part.slice(1,-1)}</code>:<React.Fragment key={i}>{part}</React.Fragment>)}
function RichText({text}){const lines=String(text||'').replace(/\\\((.*?)\\\)/g,'$1').replace(/\\\[(.*?)\\\]/g,'$1').split('\n');return <div className="qrsRich">{lines.map((line,i)=>{const s=line.trim();if(!s)return <div className="qrsGap" key={i}/>;if(/^#{1,3}\s/.test(s))return <h4 key={i}>{inlineParts(s.replace(/^#{1,3}\s/,''))}</h4>;if(/^[-*]\s+/.test(s))return <div className="qrsBullet" key={i}><span>•</span><p>{inlineParts(s.replace(/^[-*]\s+/,''))}</p></div>;return <p key={i}>{inlineParts(s)}</p>})}</div>}
function parseAgentText(text){let code=null;const artifacts=[];let display=String(text||'');display=display.replace(/<qnt_code>([\s\S]*?)<\/qnt_code>/gi,(_,raw)=>{code=raw.replace(/^\n|\n$/g,'');return''});display=display.replace(/<qnt_artifact>([\s\S]*?)<\/qnt_artifact>/gi,(_,raw)=>{try{const a=JSON.parse(raw);if(a&&typeof a==='object')artifacts.push(a)}catch{}return''});return{display:display.trim(),code,artifacts}}
function streamDisplay(text){return String(text||'').replace(/<qnt_(?:artifact|code)>[\s\S]*$/i,'').trimEnd()}
function normalizeArtifact(raw){const kind=String(raw?.kind||'').toLowerCase(),allowed=['surface3d','line','bar','scatter','table','metrics'];if(!allowed.includes(kind))return null;const base={...raw,kind,id:`ART-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,createdAt:new Date().toISOString(),source:raw.source||'QNT Copilot · Python'};if(kind==='surface3d'){const x=Array.isArray(raw.x)?raw.x.slice(0,20):[],y=Array.isArray(raw.y)?raw.y.slice(0,20):[],z=Array.isArray(raw.z)?raw.z.slice(0,20).map(r=>Array.isArray(r)?r.slice(0,20):[]):[];if(x.length<2||y.length<2||!z.length)return null;return{...base,x,y,z}}if(kind==='table'){return{...base,columns:(raw.columns||[]).slice(0,12),rows:(raw.rows||[]).slice(0,60)}}if(kind==='metrics'){return{...base,items:(raw.items||[]).slice(0,16)}}return{...base,data:(raw.data||[]).slice(0,250),series:(raw.series||[]).slice(0,8)}}
function ArtifactView({artifact}){if(!artifact)return <div className="qrsArtifactEmpty"><Box size={24}/><b>No artifact selected</b><span>Ask Copilot for a Python surface, bootstrap, distribution, table or chart.</span></div>;if(artifact.kind==='surface3d')return <ResearchSurface3D artifact={artifact}/>;if(artifact.kind==='metrics')return <div className="qrsArtifactMetrics">{artifact.items.map((x,i)=><div key={i}><span>{x.label}</span><b>{x.value}</b><small>{x.sub||''}</small></div>)}</div>;if(artifact.kind==='table')return <div className="qrsArtifactTable"><div className="head">{artifact.columns.map(c=><span key={c}>{c}</span>)}</div>{artifact.rows.map((r,i)=><div key={i}>{artifact.columns.map((c,j)=><span key={`${i}-${j}`}>{Array.isArray(r)?String(r[j]??'—'):String(r?.[c]??'—')}</span>)}</div>)}</div>;const data=artifact.data||[],series=artifact.series?.length?artifact.series:[{key:'value',label:'Value'}],xKey=artifact.xKey||'x';if(artifact.kind==='scatter')return <ResponsiveContainer width="100%" height={420}><ScatterChart><CartesianGrid stroke="#171a20"/><XAxis type="number" dataKey={artifact.xKey||'x'} tick={{fontSize:8}} stroke="#555b64"/><YAxis type="number" dataKey={artifact.yKey||'y'} tick={{fontSize:8}} stroke="#555b64"/><ZAxis range={[35,35]}/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><Scatter data={data}/></ScatterChart></ResponsiveContainer>;if(artifact.kind==='bar')return <ResponsiveContainer width="100%" height={420}><BarChart data={data}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey={xKey} tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/>{series.map(s=><Bar key={s.key} dataKey={s.key} name={s.label||s.key}/>)}</BarChart></ResponsiveContainer>;return <ResponsiveContainer width="100%" height={420}><LineChart data={data}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey={xKey} tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/>{series.map(s=><Line key={s.key} dataKey={s.key} name={s.label||s.key} dot={false} strokeWidth={1.4}/>)}</LineChart></ResponsiveContainer>}
function autoPythonIntent(text){return /(?:^\/(?:surface|bootstrap|stress|distribution)|\b(?:run|use|execute)\s+python\b|\b(?:build|generate|create)\b[^\n]{0,40}\b(?:3d|surface|bootstrap|simulation|regression|distribution|chart)\b)/i.test(String(text||''))}

export default function ResearchStudio(){
  const[files,setFiles]=useState(starterFiles),[activeFile,setActiveFile]=useState('edge_surface.py'),[prompt,setPrompt]=useState(''),[messages,setMessages]=useState([{role:'assistant',text:'Research Studio ready. Fast answers stream by default; Python, web, and deeper models are routed only when the task needs them.',mode:'fast'}]);
  const[artifacts,setArtifacts]=useState(()=>{try{return JSON.parse(localStorage.getItem('qnt.research.artifacts')||'[]')}catch{return[]}}),[selectedArtifact,setSelectedArtifact]=useState(null),[loading,setLoading]=useState(false),[proposal,setProposal]=useState(null),[webEnabled,setWebEnabled]=useState(false),[deepMode,setDeepMode]=useState(false),[runtimeMode,setRuntimeMode]=useState('fast'),[firstTokenMs,setFirstTokenMs]=useState(null),[centerMode,setCenterMode]=useState('artifact');
  const stats=useMemo(()=>{const r=personalModel.evalR,w=r.filter(x=>x>0),l=r.filter(x=>x<0);return{ev:mean(r),pf:Math.abs(w.reduce((a,b)=>a+b,0)/(l.reduce((a,b)=>a+b,0)||-1)),sh:sd(r)?mean(r)/sd(r):0}},[]);
  const equity=useMemo(()=>{let e=100000;return personalModel.evalR.map((r,i)=>{e+=r*500;return{i:i+1,equity:e}})},[]);
  useEffect(()=>{try{localStorage.setItem('qnt.research.artifacts',JSON.stringify(artifacts.slice(0,12)))}catch{}},[artifacts]);
  const setCode=v=>setFiles(x=>({...x,[activeFile]:v}));
  const addFile=()=>{let i=1,name=`research_${i}.py`;while(files[name]){i++;name=`research_${i}.py`}setFiles(x=>({...x,[name]:'# QNT Python research\n'}));setActiveFile(name);setCenterMode('code')};
  const ingestArtifacts=raw=>{const next=raw.map(normalizeArtifact).filter(Boolean);if(!next.length)return;setArtifacts(cur=>[...next,...cur].slice(0,12));setSelectedArtifact(next[0].id);setCenterMode('artifact')};
  const send=async(override=null,forcePython=false)=>{
    const text=String(override??prompt).trim();if(!text||loading)return;
    const prior=messages,streamId=`qnt-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,started=performance.now();let rawText='',sawFirst=false;
    const usePython=Boolean(forcePython||deepMode||autoPythonIntent(text)),requestedMode=deepMode?'deep':(usePython||webEnabled?'research':'fast');
    setRuntimeMode(requestedMode);setFirstTokenMs(null);setMessages([...prior,{role:'user',text},{role:'assistant',text:'',mode:requestedMode,streamId}]);setPrompt('');setProposal(null);setLoading(true);
    try{
      const researchContext=[`Curated eval ideas: ${personalModel.evalPositionIdeas}.`,`Observed probabilities: win ${(personalModel.winProbability*100).toFixed(1)}%, loss ${(personalModel.lossProbability*100).toFixed(1)}%, breakeven ${(personalModel.breakevenProbability*100).toFixed(1)}%.`,`Winner payoff library count: ${personalModel.winR.length}; loss library count: ${personalModel.lossR.length}.`,personalModel.curationNote,'Normalized payoff units are not stop-defined true R.','Direct NQ/MNQ regime claims require verified futures bars joined to trade timestamps.'].join('\n');
      const modelSummary={evalIdeas:personalModel.evalPositionIdeas,wins:personalModel.evalWins,losses:personalModel.evalLosses,breakevens:personalModel.evalBreakevens,winProbability:personalModel.winProbability,lossProbability:personalModel.lossProbability,breakevenProbability:personalModel.breakevenProbability};
      const screenContext={module:'Research Studio',activeFile,editorType:activeFile.split('.').pop(),workspace:'NQ edge research',runtime:'QNT routed OpenAI Responses runtime',webResearch:webEnabled,artifactCount:artifacts.length,personalModel:usePython?{...modelSummary,evalR:personalModel.evalR,winR:personalModel.winR,lossR:personalModel.lossR}:modelSummary};
      const reqMessage=usePython?`${text}\n\nUse Python Code Interpreter when calculation is required and return a QNT artifact when a visualization materially helps.`:text;
      const res=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:reqMessage,history:prior,activeFile,code:files[activeFile],researchContext,screenContext,allowWeb:webEnabled,usePython,mode:requestedMode})});
      if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.error||'Copilot request failed')}
      const contentType=res.headers.get('content-type')||'';
      if(contentType.includes('application/x-ndjson')&&res.body){
        const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';
        const applyEvent=event=>{if(event.type==='meta'){setRuntimeMode(event.mode||requestedMode);setMessages(prev=>prev.map(m=>m.streamId===streamId?{...m,mode:event.mode||requestedMode,model:event.model}:m));return}if(event.type==='delta'&&typeof event.delta==='string'){if(!sawFirst){sawFirst=true;setFirstTokenMs(Math.round(performance.now()-started))}rawText+=event.delta;const visible=streamDisplay(rawText);setMessages(prev=>prev.map(m=>m.streamId===streamId?{...m,text:visible}:m));return}if(event.type==='error')throw new Error(event.error||'Copilot stream failed')};
        while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let nl;while((nl=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,nl).trim();buffer=buffer.slice(nl+1);if(!line)continue;try{applyEvent(JSON.parse(line))}catch(e){if(e instanceof SyntaxError)continue;throw e}}}
        buffer+=decoder.decode();if(buffer.trim()){try{applyEvent(JSON.parse(buffer.trim()))}catch(e){if(!(e instanceof SyntaxError))throw e}}
      }else{
        const data=await res.json();rawText=data.text||'';setRuntimeMode(data.mode||requestedMode);
      }
      const parsed=parseAgentText(rawText);setMessages(prev=>prev.map(m=>m.streamId===streamId?{role:'assistant',text:parsed.display||'Research run completed.',mode:runtimeMode}:m));if(parsed.code)setProposal({file:activeFile,code:parsed.code});ingestArtifacts(parsed.artifacts);
    }catch(e){setMessages(prev=>prev.map(m=>m.streamId===streamId?{role:'assistant',text:`Copilot error: ${e.message}`,mode:requestedMode}:m))}finally{setLoading(false)}
  };
  const runActive=()=>send(`Execute the logic in the active research file "${activeFile}" with Python Code Interpreter. Validate assumptions, compute the result, and return the best matching QNT artifact. Do not invent unavailable data.`,true);
  const applyProposal=()=>{if(!proposal)return;setFiles(x=>({...x,[proposal.file]:proposal.code}));setActiveFile(proposal.file);setCenterMode('code');setMessages(x=>[...x,{role:'assistant',text:`Applied the proposed replacement to ${proposal.file}.`,mode:'fast'}]);setProposal(null)};
  useEffect(()=>{const h=e=>{if(e.detail?.prompt)send(e.detail.prompt)};window.addEventListener('qnt:copilot-prompt',h);return()=>window.removeEventListener('qnt:copilot-prompt',h)},[messages,files,activeFile,loading,webEnabled,deepMode,artifacts]);
  const selected=artifacts.find(a=>a.id===selectedArtifact)||artifacts[0]||null;
  return <div className="qrsStudio">
    <aside className="qrsFiles"><div className="qrsPaneHead"><span>RESEARCH</span><button onClick={addFile}><Plus size={13}/></button></div><div className="qrsProject"><Folder size={13}/><b>NQ edge research</b></div><div className="qrsSectionLabel">FILES</div><div className="qrsFileList">{Object.keys(files).map(name=><button key={name} className={activeFile===name?'active':''} onClick={()=>{setActiveFile(name);setCenterMode('code')}}><FileCode2 size={12}/><span>{name}</span><small>{name.split('.').pop()}</small></button>)}</div><div className="qrsSectionLabel">AI SKILLS</div><div className="qrsSkills">{SKILLS.map(s=><button key={s.code} onClick={()=>send(s.prompt,true)}><kbd>{s.code}</kbd><b>{s.title}</b><span>{s.desc}</span></button>)}</div><div className="qrsSources"><div><Database size={12}/> CONTEXT</div><p><b>Personal model</b><span>{personalModel.evalPositionIdeas} ideas</span></p><p><b>Python</b><span>on demand</span></p><p><b>Web research</b><span>{webEnabled?'enabled':'off'}</span></p></div></aside>
    <section className="qrsCenter"><div className="qrsModeTabs"><button className={centerMode==='artifact'?'active':''} onClick={()=>setCenterMode('artifact')}><Box size={12}/>ARTIFACTS</button><button className={centerMode==='code'?'active':''} onClick={()=>setCenterMode('code')}><Braces size={12}/>CODE</button><button className={centerMode==='summary'?'active':''} onClick={()=>setCenterMode('summary')}><Table2 size={12}/>MODEL</button><div className="qrsRun"><span>{loading?`${runtimeMode.toUpperCase()} · STREAMING`:'RESEARCH RUNTIME READY'}</span><button onClick={runActive} disabled={loading}><Play size={12}/> Run with Python</button></div></div>
      {centerMode==='code'&&<><div className="qrsCodeHead"><span>personal / research / {activeFile}</span><small>editable Python research draft</small></div><textarea className="qrsCode" value={files[activeFile]} onChange={e=>setCode(e.target.value)} spellCheck="false"/></>}
      {centerMode==='artifact'&&<div className="qrsArtifactArea"><div className="qrsArtifactHead"><div><span>ARTIFACT</span><b>{selected?.title||'Python research output'}</b><small>{selected?.source||'ask Copilot to generate one'}</small></div>{selected?.createdAt&&<time>{new Date(selected.createdAt).toLocaleTimeString()}</time>}</div><div className="qrsArtifactCanvas"><ArtifactView artifact={selected}/></div>{selected?.note&&<div className="qrsArtifactNote">{selected.note}</div>}<div className="qrsArtifactStrip">{artifacts.map(a=><button key={a.id} className={(selected?.id===a.id)?'active':''} onClick={()=>setSelectedArtifact(a.id)}><span>{a.kind}</span><b>{a.title||'Untitled artifact'}</b><small>{new Date(a.createdAt).toLocaleTimeString()}</small></button>)}</div></div>}
      {centerMode==='summary'&&<div className="qrsSummary"><div className="qrsMetricGrid"><div><span>OBSERVED WIN</span><b>{fmtPct(personalModel.winProbability*100)}</b></div><div><span>EVAL IDEAS</span><b>{personalModel.evalPositionIdeas}</b></div><div><span>RAW EXPECTANCY*</span><b>{fmt(stats.ev)}R</b></div><div><span>RAW PF*</span><b>{fmt(stats.pf)}</b></div><div><span>TRADE MEAN/σ*</span><b>{fmt(stats.sh)}</b></div><div><span>ARTIFACTS</span><b>{artifacts.length}</b></div></div><div className="qrsEquity"><ResponsiveContainer width="100%" height={300}><AreaChart data={equity}><CartesianGrid stroke="#171a1e" vertical={false}/><XAxis dataKey="i" stroke="#4d5259" tick={{fontSize:8}}/><YAxis stroke="#4d5259" tick={{fontSize:8}}/><Tooltip contentStyle={{background:'#080a0c',border:'1px solid #2b3036',fontSize:9}}/><Area dataKey="equity" dot={false} stroke="#a58cff" fill="#15111d"/></AreaChart></ResponsiveContainer></div><p>*Raw normalized payoff scale; not stop-defined true R. Use Python skills to stress-test uncertainty before relying on these summaries.</p></div>}
    </section>
    <aside className="qrsCopilot"><div className="qrsCopilotHead"><div><MessageSquareText size={14}/><b>QNT Research Agent</b></div><button onClick={()=>setMessages([{role:'assistant',text:'New research thread. Fast streaming is ready; Python and deeper research run on demand.',mode:'fast'}])}><Plus size={12}/> New</button></div><div className="qrsToolBar"><button className="active"><Zap size={11}/>AUTO</button><button className={webEnabled?'active':''} onClick={()=>setWebEnabled(v=>!v)}><Globe2 size={11}/>WEB</button><button className={deepMode?'active':''} onClick={()=>setDeepMode(v=>!v)}>DEEP</button><span>{runtimeMode.toUpperCase()}{firstTokenMs!=null?` · ${firstTokenMs}ms first token`:''}</span></div><div className="qrsChat">{messages.map((m,i)=>m.role==='user'?<div className="qrsUser" key={m.streamId||i}>{m.text}</div>:<div className="qrsAgent" key={m.streamId||i}><div><span/><b>QNT</b><small>{String(m.mode||'fast').toUpperCase()}</small></div><RichText text={m.text||''}/></div>)}{loading&&<div className="qrsWorking"><Search size={12}/><span>{runtimeMode==='fast'?'Streaming response…':'Running research tools and streaming output…'}</span><b>live</b></div>}{proposal&&<div className="qrsProposal"><div><FileCode2 size={12}/><b>Code update ready</b><span>{proposal.file}</span></div><button onClick={applyProposal}>Apply</button></div>}</div><div className="qrsComposer"><div className="qrsPromptTools"><button onClick={()=>send(SKILLS[0].prompt,true)}><WandSparkles size={11}/>3D</button><button onClick={()=>send(SKILLS[1].prompt,true)}>BOOTSTRAP</button><button onClick={()=>send(SKILLS[2].prompt,true)}>STRESS</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask QNT. Normal questions use FAST; Python/web route to RESEARCH; toggle DEEP for the hardest audits…"/><div><span>AUTO routing · streamed output · on-demand tools</span><button onClick={()=>send()} disabled={loading}>{loading?'Running…':'Send ↗'}</button></div></div></aside>
  </div>;
}
