import React,{useMemo,useState}from'react';
import{AlertTriangle,BarChart3,CheckCircle2,FlaskConical,GitBranch,LockKeyhole,RefreshCw,ShieldCheck,TestTube2}from'lucide-react';
import{Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{personalModel}from'./personalDataset.js';

const FUNCTIONS=['OVERVIEW','HOLDOUT','BOOT','STABILITY','DECAY','DEPEND','INFLUENCE','TAIL','PRECISION','STRESS','OVERFIT'];
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
const median=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const quantile=(a,q)=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[Math.min(i+1,x.length-1)]-x[i])*f};
const fmt=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const pct=(n,d=1)=>Number.isFinite(Number(n))?`${Number(n).toFixed(d)}%`:'—';
const signed=(n,d=2)=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(d)}R`:'—';
function rng(seed){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function maxDrawdownR(a=[]){let eq=0,peak=0,dd=0;for(const r of a){eq+=r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return dd}
function longestLossStreak(a=[]){let cur=0,best=0;for(const r of a){if(r<0){cur++;best=Math.max(best,cur)}else cur=0}return best}
function stats(a=[]){const wins=a.filter(x=>x>0),losses=a.filter(x=>x<0),sumWin=wins.reduce((s,v)=>s+v,0),sumLoss=Math.abs(losses.reduce((s,v)=>s+v,0));return{n:a.length,expectancy:mean(a),median:median(a),winRate:a.length?wins.length/a.length*100:null,lossRate:a.length?losses.length/a.length*100:null,pf:sumLoss?sumWin/sumLoss:null,maxDd:maxDrawdownR(a),lossStreak:longestLossStreak(a)}}
function bootstrap(a,reps=5000,seed=1701){const rand=rng(seed),ev=[],wr=[];for(let b=0;b<reps;b++){let sum=0,wins=0;for(let i=0;i<a.length;i++){const v=a[Math.floor(rand()*a.length)]??0;sum+=v;if(v>0)wins++}ev.push(sum/a.length);wr.push(wins/a.length*100)}return{ev,wr,p5:quantile(ev,.05),p50:quantile(ev,.5),p95:quantile(ev,.95),pPos:ev.filter(x=>x>0).length/reps*100,wr5:quantile(wr,.05),wr95:quantile(wr,.95)}}
function blockBootstrap(a,block=3,reps=3000,seed=991){const rand=rng(seed),ev=[];for(let b=0;b<reps;b++){const sample=[];while(sample.length<a.length){const start=Math.floor(rand()*a.length);for(let j=0;j<block&&sample.length<a.length;j++)sample.push(a[(start+j)%a.length])}ev.push(mean(sample))}return{ev,p5:quantile(ev,.05),p50:quantile(ev,.5),p95:quantile(ev,.95),pPos:ev.filter(x=>x>0).length/reps*100}}
function hist(values,bins=24){if(!values.length)return[];const lo=Math.min(...values),hi=Math.max(...values),w=(hi-lo||1)/bins,out=Array.from({length:bins},(_,i)=>({x:lo+w*(i+.5),count:0}));for(const v of values){const i=Math.min(bins-1,Math.max(0,Math.floor((v-lo)/(w||1))));out[i].count++}return out}
function rolling(a,n){const out=[];for(let i=n-1;i<a.length;i++){const s=a.slice(i-n+1,i+1),m=stats(s);out.push({trade:i+1,expectancy:m.expectancy,winRate:m.winRate})}return out}
function walkForward(a,train=12,test=4){const folds=[];let end=train;while(end<a.length){const trainSlice=a.slice(0,end),testSlice=a.slice(end,Math.min(a.length,end+test));if(!testSlice.length)break;folds.push({fold:folds.length+1,trainN:trainSlice.length,testN:testSlice.length,trainEv:mean(trainSlice),testEv:mean(testSlice),trainWr:stats(trainSlice).winRate,testWr:stats(testSlice).winRate});end+=test}return folds}
function autocorr(a,lag=1){if(a.length<=lag)return null;const x=a.slice(lag),y=a.slice(0,-lag),mx=mean(x),my=mean(y);let num=0,dx=0,dy=0;for(let i=0;i<x.length;i++){num+=(x[i]-mx)*(y[i]-my);dx+=(x[i]-mx)**2;dy+=(y[i]-my)**2}const den=Math.sqrt(dx*dy);return den?num/den:null}
function transitions(a=[]){let afterWin=[],afterLoss=[];for(let i=1;i<a.length;i++){if(a[i-1]>0)afterWin.push(a[i]);if(a[i-1]<0)afterLoss.push(a[i])}return{afterWinEv:mean(afterWin),afterLossEv:mean(afterLoss),afterWinWr:stats(afterWin).winRate,afterLossWr:stats(afterLoss).winRate,nAfterWin:afterWin.length,nAfterLoss:afterLoss.length}}
function runsDiagnostic(a=[]){const s=a.filter(v=>v!==0).map(v=>v>0?1:0);if(s.length<3)return null;let runs=1,n1=s.reduce((x,v)=>x+v,0),n0=s.length-n1;for(let i=1;i<s.length;i++)if(s[i]!==s[i-1])runs++;if(!n1||!n0)return null;const mu=1+2*n1*n0/(n1+n0),variance=2*n1*n0*(2*n1*n0-n1-n0)/(((n1+n0)**2)*(n1+n0-1)),z=variance>0?(runs-mu)/Math.sqrt(variance):null;return{runs,n1,n0,expected:mu,z}}
function cumulative(a=[]){let sum=0;return a.map((v,i)=>{sum+=v;return{trade:i+1,cumulativeMean:sum/(i+1),value:v}})}
function linearSlope(a=[]){if(a.length<2)return null;const xs=a.map((_,i)=>i+1),mx=mean(xs),my=mean(a),cov=mean(a.map((v,i)=>(xs[i]-mx)*(v-my))),vx=mean(xs.map(x=>(x-mx)**2));return vx?cov/vx:null}
function tailStats(a=[]){if(!a.length)return{};const sorted=[...a].sort((x,y)=>x-y),k=Math.max(1,Math.ceil(a.length*.1)),worst=sorted.slice(0,k),q10=quantile(a,.1),q90=quantile(a,.9),losses=a.filter(x=>x<0),wins=a.filter(x=>x>0);return{q10,q90,cvar10:mean(worst),worst:sorted[0],best:sorted.at(-1),avgLoss:mean(losses),avgWin:mean(wins),tailRatio:Number.isFinite(q10)&&q10!==0?Math.abs(q90/q10):null,worstN:k}}
function wilson(wins,n,z=1.96){if(!n)return[0,0];const p=wins/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,m=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/d;return[Math.max(0,c-m),Math.min(1,c+m)]}
function projectedWilson(p,n,z=1.96){const wins=Math.round(p*n);return wilson(wins,n,z)}
function approxSampleForMargin(p,margin,z=1.96){return Math.ceil(z*z*p*(1-p)/(margin*margin))}
function stressRows(a,friction){const dropTop=(k)=>{const indexed=a.map((v,i)=>({v,i})),remove=new Set(indexed.filter(x=>x.v>0).sort((x,y)=>y.v-x.v).slice(0,k).map(x=>x.i));return a.filter((_,i)=>!remove.has(i))};const lossWorse=a.map(v=>v<0?v*1.25:v);const withFriction=x=>a.map(v=>v-x);return[
  ['Baseline',a,'Current curated sequence'],['Drop top winner',dropTop(1),'Tail-dependence test'],['Drop top 3 winners',dropTop(3),'Tail-dependence test'],['Drop top 5 winners',dropTop(5),'Extreme tail-dependence test'],['Losses +25%',lossWorse,'Loss-magnitude stress'],[`Friction ${friction.toFixed(2)}R`,withFriction(friction),'Generic per-trade friction in normalized units'],['Friction 0.10R',withFriction(.10),'Generic per-trade friction in normalized units'],['Friction 0.20R',withFriction(.20),'Generic per-trade friction in normalized units'],
].map(([name,series,note])=>({name,note,...stats(series)}))}
function Card({label,value,sub,tone=''}){return <div className="svCard"><span>{label}</span><b className={tone}>{value}</b><small>{sub||''}</small></div>}
function Panel({title,sub,children,actions}){return <section className="svPanel"><header><div><b>{title}</b><span>{sub}</span></div>{actions}</header>{children}</section>}

export default function StrategyValidationLab(){
  const[fn,setFn]=useState('OVERVIEW'),[friction,setFriction]=useState(.05);
  const r=personalModel.evalR||[],base=useMemo(()=>stats(r),[r]),boot=useMemo(()=>bootstrap(r),[r]),block=useMemo(()=>blockBootstrap(r),[r]),bootHist=useMemo(()=>hist(boot.ev),[boot]);
  const holdouts=useMemo(()=>[.5,.6,.7,.8].map(split=>{const cut=Math.max(1,Math.min(r.length-1,Math.round(r.length*split))),train=r.slice(0,cut),test=r.slice(cut);return{split:`${Math.round(split*100)}/${100-Math.round(split*100)}`,trainN:train.length,testN:test.length,trainEv:mean(train),testEv:mean(test),trainWr:stats(train).winRate,testWr:stats(test).winRate}}),[r]);
  const folds=useMemo(()=>walkForward(r),[r]),roll5=useMemo(()=>rolling(r,5),[r]),roll10=useMemo(()=>rolling(r,10),[r]);
  const influence=useMemo(()=>r.map((value,i)=>{const next=r.filter((_,j)=>j!==i),ev=mean(next);return{trade:i+1,value,leaveOutEv:ev,delta:ev-base.expectancy}}).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)),[r,base.expectancy]);
  const stress=useMemo(()=>stressRows(r,friction),[r,friction]),depend=useMemo(()=>transitions(r),[r]),runs=useMemo(()=>runsDiagnostic(r),[r]),tails=useMemo(()=>tailStats(r),[r]),cum=useMemo(()=>cumulative(r),[r]),slope=useMemo(()=>linearSlope(r),[r]);
  const experiments=useMemo(()=>{try{return JSON.parse(localStorage.getItem('qnt.experiments')||'[]')}catch{return[]}},[]);
  const openPython=(prompt)=>{window.dispatchEvent(new CustomEvent('qnt:navigate',{detail:{type:'research',tab:'Workspace'}}));window.setTimeout(()=>window.dispatchEvent(new CustomEvent('qnt:copilot-prompt',{detail:{prompt}})),40)};
  const stability=[...new Set([...roll5.map(x=>x.trade),...roll10.map(x=>x.trade)])].sort((a,b)=>a-b).map(trade=>({trade,e5:roll5.find(x=>x.trade===trade)?.expectancy,w5:roll5.find(x=>x.trade===trade)?.winRate,e10:roll10.find(x=>x.trade===trade)?.expectancy,w10:roll10.find(x=>x.trade===trade)?.winRate}));
  const chunks=useMemo(()=>{const size=Math.max(5,Math.floor(r.length/3)),out=[];for(let i=0;i<r.length;i+=size){const s=r.slice(i,Math.min(r.length,i+size));if(s.length)out.push({label:`T${i+1}–T${i+s.length}`,start:i+1,end:i+s.length,expectancy:mean(s),winRate:stats(s).winRate,n:s.length})}return out},[r]);
  const currentWilson=useMemo(()=>wilson(personalModel.evalWins,personalModel.evalPositionIdeas),[]),p=personalModel.winProbability;
  const precisionRows=useMemo(()=>[30,50,75,100,150,200].map(n=>{const [lo,hi]=projectedWilson(p,n);return{n,lo:lo*100,hi:hi*100,width:(hi-lo)*100}}),[p]);
  const n10=approxSampleForMargin(p,.10),n5=approxSampleForMargin(p,.05);

  return <div className="svPage"><div className="svTitle"><div><span>STRATEGY TESTING</span><h1>Validation Lab</h1><p>Out-of-sample discipline, resampling, stability, dependence, tail risk and robustness checks for the current research model.</p></div><button onClick={()=>openPython('Use Python to run a full robustness audit of my current curated strategy model. Include bootstrap uncertainty, block dependence, edge decay, tail stress, sequence stability, leave-one-out influence and a clear list of tests that cannot be validly computed yet. Return charts or tables as QNT artifacts where useful.')}><FlaskConical size={13}/> PYTHON AUDIT</button></div>
  <nav className="svNav">{FUNCTIONS.map(x=><button key={x} className={fn===x?'active':''} onClick={()=>setFn(x)}><kbd>{x}</kbd></button>)}</nav>
  <div className="svNotice"><AlertTriangle size={13}/><span>The model is selectively curated and uses normalized payoff units rather than true stop-defined R. These tests describe robustness of this sample; they do not create an unbiased forecast.</span></div>

  {fn==='OVERVIEW'&&<><div className="svCards"><Card label="EVAL IDEAS" value={base.n}/><Card label="RAW MEAN" value={signed(base.expectancy)} sub="ordered eval sample" tone={base.expectancy>0?'good':''}/><Card label="MEDIAN" value={signed(base.median)}/><Card label="WIN RATE" value={pct(base.winRate)} sub={`${personalModel.evalWins}W / ${personalModel.evalLosses}L / ${personalModel.evalBreakevens}BE`}/><Card label="PROFIT FACTOR*" value={fmt(base.pf)} sub="raw normalized payoff"/><Card label="MAX DD*" value={`${fmt(base.maxDd)}R`} sub="sequence drawdown"/><Card label="LOSS STREAK" value={base.lossStreak}/><Card label="BOOT 90% CI" value={`${signed(boot.p5)} → ${signed(boot.p95)}`} sub="iid resampling"/></div><div className="svGrid"><Panel title="ROBUSTNESS MAP" sub="what is testable with the current sample"><div className="svReadiness"><div className="ok"><CheckCircle2/><b>Sequence holdouts</b><span>available</span></div><div className="ok"><CheckCircle2/><b>Bootstrap / block bootstrap</b><span>available</span></div><div className="ok"><CheckCircle2/><b>Decay / dependence / tail tests</b><span>available</span></div><div className="warn"><AlertTriangle/><b>True OOS by date</b><span>timestamps not in public model payload</span></div><div className="blocked"><LockKeyhole/><b>Purged CV / CPCV</b><span>needs event timestamps + label horizons</span></div><div className="blocked"><LockKeyhole/><b>PBO / Deflated Sharpe</b><span>needs structured multi-trial backtest matrix</span></div></div></Panel><Panel title="BOOTSTRAP SNAPSHOT" sub="5,000 iid resamples of observed eval outcomes"><div className="svMiniStats"><div><span>P(E &gt; 0)</span><b>{pct(boot.pPos)}</b></div><div><span>P5</span><b>{signed(boot.p5)}</b></div><div><span>MEDIAN</span><b>{signed(boot.p50)}</b></div><div><span>P95</span><b>{signed(boot.p95)}</b></div></div><p className="svFoot">Resampling repeats the observed outcomes and inherits the sample-selection problem. It is uncertainty analysis, not proof of edge.</p></Panel></div></>}

  {fn==='HOLDOUT'&&<div className="svGrid one"><Panel title="SEQUENCE HOLDOUTS" sub="earlier observations as train, later observations as test · no parameter tuning"><div className="svTable hold"><div className="head"><span>SPLIT</span><span>TRAIN N</span><span>TEST N</span><span>TRAIN E</span><span>TEST E</span><span>TRAIN WR</span><span>TEST WR</span></div>{holdouts.map(x=><div key={x.split}><b>{x.split}</b><span>{x.trainN}</span><span>{x.testN}</span><span>{signed(x.trainEv)}</span><span className={x.testEv>=0?'good':'bad'}>{signed(x.testEv)}</span><span>{pct(x.trainWr)}</span><span>{pct(x.testWr)}</span></div>)}</div></Panel><Panel title="EXPANDING FORWARD VALIDATION" sub="12-observation initial train window, then 4-observation forward tests · no re-optimization"><ResponsiveContainer width="100%" height={320}><BarChart data={folds}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="fold" tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><Legend wrapperStyle={{fontSize:8}}/><Bar name="Train expectancy" dataKey="trainEv"/><Bar name="Forward-test expectancy" dataKey="testEv"/></BarChart></ResponsiveContainer><div className="svFoldStrip">{folds.map(x=><div key={x.fold}><span>FOLD {x.fold}</span><b className={x.testEv>=0?'good':'bad'}>{signed(x.testEv)}</b><small>{x.testN} forward observations · WR {pct(x.testWr)}</small></div>)}</div><p className="svFoot">This is an expanding sequence test, not full walk-forward optimization, because QNT is not re-fitting a parameterized strategy in each fold yet.</p></Panel></div>}

  {fn==='BOOT'&&<div className="svGrid one"><Panel title="EXPECTANCY RESAMPLING" sub="iid bootstrap compared with 3-trade moving-block bootstrap"><div className="svCards compact"><Card label="IID P(E>0)" value={pct(boot.pPos)}/><Card label="IID 90% CI" value={`${signed(boot.p5)} → ${signed(boot.p95)}`}/><Card label="BLOCK P(E>0)" value={pct(block.pPos)}/><Card label="BLOCK 90% CI" value={`${signed(block.p5)} → ${signed(block.p95)}`}/><Card label="BOOT WR 90%" value={`${pct(boot.wr5)} → ${pct(boot.wr95)}`}/></div><ResponsiveContainer width="100%" height={390}><BarChart data={bootHist}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="x" tick={{fontSize:8}} stroke="#555b64" tickFormatter={v=>fmt(v,1)}/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}} labelFormatter={v=>`${fmt(v,2)}R expectancy`}/><ReferenceLine x={0} stroke="#7b818b"/><Bar dataKey="count"/></BarChart></ResponsiveContainer><div className="svActions"><button onClick={()=>openPython('Use Python to compare iid bootstrap, moving-block bootstrap, and a Bayesian posterior view of my current strategy outcomes. Explain what each method assumes and return a compact comparison table and distribution chart as QNT artifacts.')}><RefreshCw size={12}/> RUN DEEPER IN PYTHON</button></div></Panel></div>}

  {fn==='STABILITY'&&<div className="svGrid one"><Panel title="ROLLING EDGE STABILITY" sub="5-trade and 10-trade rolling windows"><ResponsiveContainer width="100%" height={360}><LineChart data={stability}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="trade" tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><ReferenceLine y={0} stroke="#555b64"/><Line type="monotone" dataKey="e5" name="5-trade expectancy" dot={false}/><Line type="monotone" dataKey="e10" name="10-trade expectancy" dot={false}/></LineChart></ResponsiveContainer><div className="svCards compact"><Card label="LATEST 5" value={signed(roll5.at(-1)?.expectancy)} sub={`WR ${pct(roll5.at(-1)?.winRate)}`}/><Card label="LATEST 10" value={signed(roll10.at(-1)?.expectancy)} sub={`WR ${pct(roll10.at(-1)?.winRate)}`}/><Card label="FULL SAMPLE" value={signed(base.expectancy)}/></div></Panel></div>}

  {fn==='DECAY'&&<div className="svGrid one"><Panel title="EDGE DECAY / DRIFT" sub="cumulative mean and chunk-to-chunk behavior across the observed order"><div className="svCards compact"><Card label="LINEAR DRIFT" value={`${signed(slope,3)} / trade`} sub="slope of raw outcome vs observation index"/><Card label="FIRST CHUNK" value={signed(chunks[0]?.expectancy)} sub={`${chunks[0]?.n??0} observations`}/><Card label="LATEST CHUNK" value={signed(chunks.at(-1)?.expectancy)} sub={`${chunks.at(-1)?.n??0} observations`}/><Card label="LATEST CHUNK WR" value={pct(chunks.at(-1)?.winRate)}/></div><ResponsiveContainer width="100%" height={360}><LineChart data={cum}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="trade" tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><ReferenceLine y={0} stroke="#555b64"/><Line dataKey="cumulativeMean" name="Cumulative mean expectancy" dot={false}/></LineChart></ResponsiveContainer><div className="svTable decay"><div className="head"><span>WINDOW</span><span>N</span><span>EXPECTANCY</span><span>WIN RATE</span></div>{chunks.map(x=><div key={x.label}><b>{x.label}</b><span>{x.n}</span><span className={x.expectancy>=0?'good':'bad'}>{signed(x.expectancy)}</span><span>{pct(x.winRate)}</span></div>)}</div><p className="svFoot">A slope or chunk difference can flag drift, but with only {r.length} observations it is descriptive evidence, not a regime-change test.</p></Panel></div>}

  {fn==='DEPEND'&&<div className="svGrid"><Panel title="SEQUENCE DEPENDENCE" sub="simple diagnostics for clustering and serial behavior"><div className="svCards compact"><Card label="LAG-1 AUTOCORR" value={fmt(autocorr(r,1),3)} sub="raw normalized outcomes"/><Card label="LAG-2 AUTOCORR" value={fmt(autocorr(r,2),3)}/><Card label="AFTER WIN E" value={signed(depend.afterWinEv)} sub={`${depend.nAfterWin} observations`}/><Card label="AFTER LOSS E" value={signed(depend.afterLossEv)} sub={`${depend.nAfterLoss} observations`}/><Card label="AFTER WIN WR" value={pct(depend.afterWinWr)}/><Card label="AFTER LOSS WR" value={pct(depend.afterLossWr)}/></div><p className="svFoot">These are sequence diagnostics. Small samples can make autocorrelation and conditional win rates unstable.</p></Panel><Panel title="RUNS DIAGNOSTIC" sub="win/loss ordering after removing breakevens"><div className="svMiniStats"><div><span>OBSERVED RUNS</span><b>{runs?.runs??'—'}</b></div><div><span>EXPECTED RUNS</span><b>{fmt(runs?.expected,1)}</b></div><div><span>Z SCORE</span><b>{fmt(runs?.z,2)}</b></div><div><span>NON-BE OBS</span><b>{(runs?.n1??0)+(runs?.n0??0)}</b></div></div><p className="svFoot">The runs z-score is an approximate randomness diagnostic. QNT does not label the sequence dependent or independent from this one statistic alone.</p><div className="svActions"><button onClick={()=>openPython('Use Python to test sequence dependence in my ordered trade outcomes. Include lag autocorrelation, a runs test, conditional expectancy after wins versus losses, and moving-block bootstrap sensitivity. Explain small-sample limitations.')}><FlaskConical size={12}/> DEPENDENCE AUDIT</button></div></Panel></div>}

  {fn==='INFLUENCE'&&<div className="svGrid one"><Panel title="LEAVE-ONE-OUT INFLUENCE" sub="recompute mean expectancy after removing each single observation"><div className="svCards compact"><Card label="BASE EXPECTANCY" value={signed(base.expectancy)}/><Card label="MOST INFLUENTIAL" value={`Trade ${influence[0]?.trade??'—'}`} sub={`observed ${signed(influence[0]?.value)}`}/><Card label="LEAVE-OUT EXPECTANCY" value={signed(influence[0]?.leaveOutEv)}/><Card label="CHANGE" value={signed(influence[0]?.delta)} sub="vs baseline"/></div><ResponsiveContainer width="100%" height={390}><BarChart data={influence.slice(0,14)} layout="vertical"><CartesianGrid stroke="#171a20" horizontal={false}/><XAxis type="number" tick={{fontSize:8}} stroke="#555b64"/><YAxis type="category" dataKey="trade" tick={{fontSize:8}} stroke="#555b64" tickFormatter={v=>`T${v}`}/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><ReferenceLine x={0} stroke="#555b64"/><Bar name="Expectancy change when removed" dataKey="delta"/></BarChart></ResponsiveContainer><p className="svFoot">Large absolute bars mean the strategy summary is sensitive to that single outcome. This is a jackknife-style influence diagnostic, not an instruction to exclude that trade.</p></Panel></div>}

  {fn==='TAIL'&&<div className="svGrid"><Panel title="PAYOFF TAIL PROFILE" sub="downside and upside shape in normalized payoff units"><div className="svCards compact"><Card label="10TH PERCENTILE" value={signed(tails.q10)}/><Card label={`WORST ${tails.worstN??'—'} AVG`} value={signed(tails.cvar10)} sub="empirical lower-tail mean"/><Card label="WORST OBS" value={signed(tails.worst)}/><Card label="90TH PERCENTILE" value={signed(tails.q90)}/><Card label="BEST OBS" value={signed(tails.best)}/><Card label="TAIL RATIO" value={fmt(tails.tailRatio)} sub="|P90 / P10|"/></div><p className="svFoot">This is an empirical payoff-tail view, not portfolio VaR. The current sample is small and selectively curated.</p></Panel><Panel title="ASYMMETRY" sub="average positive and negative outcomes"><div className="svMiniStats"><div><span>AVG WIN</span><b>{signed(tails.avgWin)}</b></div><div><span>AVG LOSS</span><b>{signed(tails.avgLoss)}</b></div><div><span>PAYOFF RATIO</span><b>{Number.isFinite(tails.avgWin)&&Number.isFinite(tails.avgLoss)&&tails.avgLoss!==0?fmt(Math.abs(tails.avgWin/tails.avgLoss)):'—'}</b></div><div><span>TOP-TAIL DEPENDENCE</span><b>{stress.find(x=>x.name==='Drop top 5 winners')?.expectancy>=0?'survives':'fails'}</b></div></div></Panel></div>}

  {fn==='PRECISION'&&<div className="svGrid"><Panel title="WIN-RATE PRECISION" sub="Wilson interval today and projected width as sample size grows"><div className="svCards compact"><Card label="CURRENT N" value={personalModel.evalPositionIdeas}/><Card label="OBSERVED WR" value={pct(p*100)}/><Card label="CURRENT 95% CI" value={`${pct(currentWilson[0]*100)} → ${pct(currentWilson[1]*100)}`}/><Card label="CURRENT WIDTH" value={pct((currentWilson[1]-currentWilson[0])*100)}/><Card label="~N FOR ±10PP" value={n10} sub="normal approximation at current WR"/><Card label="~N FOR ±5PP" value={n5} sub="normal approximation at current WR"/></div><div className="svTable precision"><div className="head"><span>N</span><span>LOW 95%</span><span>HIGH 95%</span><span>WIDTH</span></div>{precisionRows.map(x=><div key={x.n}><b>{x.n}</b><span>{pct(x.lo)}</span><span>{pct(x.hi)}</span><span>{pct(x.width)}</span></div>)}</div><p className="svFoot">Projected rows assume the same underlying win proportion and do not correct for selective curation, payoff uncertainty, or dependence.</p></Panel><Panel title="NEXT-EVIDENCE PRIORITY" sub="what would make validation materially stronger"><div className="svChecklist"><div className="ok"><ShieldCheck/><span><b>Freeze the current model version</b><small>score future observations without editing exclusions after the outcome</small></span></div><div className="warn"><AlertTriangle/><span><b>Preserve timestamps and planned stops</b><small>enables true time-based OOS, purged CV and stop-defined R</small></span></div><div className="warn"><AlertTriangle/><span><b>Record strategy configuration IDs</b><small>required before PBO or multiple-testing corrections are meaningful</small></span></div></div></Panel></div>}

  {fn==='STRESS'&&<div className="svGrid one"><Panel title="ROBUSTNESS STRESS MATRIX" sub="tail removal, worse losses and generic research friction" actions={<label className="svFriction"><span>CUSTOM FRICTION</span><input type="number" min="0" max="1" step="0.01" value={friction} onChange={e=>setFriction(Math.max(0,Math.min(1,Number(e.target.value)||0)))}/><b>R / trade</b></label>}><div className="svTable stress"><div className="head"><span>SCENARIO</span><span>N</span><span>EXPECTANCY</span><span>WIN RATE</span><span>PF*</span><span>MAX DD*</span><span>NOTE</span></div>{stress.map(x=><div key={x.name}><b>{x.name}</b><span>{x.n}</span><span className={x.expectancy>=0?'good':'bad'}>{signed(x.expectancy)}</span><span>{pct(x.winRate)}</span><span>{fmt(x.pf)}</span><span>{fmt(x.maxDd)}R</span><small>{x.note}</small></div>)}</div><p className="svFoot">Friction is expressed in normalized payoff units because verified execution-cost and stop-defined-R data are not connected. It should not be read as an actual commission or futures fill estimate.</p></Panel></div>}

  {fn==='OVERFIT'&&<div className="svGrid"><Panel title="OVERFITTING GUARD" sub="professional tests QNT computes only when required inputs exist"><div className="svMethodList"><article className="blocked"><LockKeyhole/><div><b>PBO / CSCV</b><span>Probability of backtest overfitting</span><p>Needs many strategy configurations evaluated across consistent subperiods. Current experiment registry: {experiments.length}; QNT does not yet have a configuration × subperiod performance matrix.</p></div></article><article className="blocked"><LockKeyhole/><div><b>Deflated Sharpe Ratio</b><span>Adjust performance for non-normality and multiple testing</span><p>Needs a defensible Sharpe series and the effective number of trials. QNT will not apply DSR to the current non-annualized trade mean/σ shortcut.</p></div></article><article className="blocked"><LockKeyhole/><div><b>Purged / embargo CV</b><span>Leakage-aware financial cross-validation</span><p>Needs timestamps and event/label horizons so overlapping information can be removed between folds.</p></div></article><article className="warn"><GitBranch/><div><b>Walk-forward optimization</b><span>Train older history, test later history</span><p>Sequence validation is available now. Full WFO requires a parameterized strategy runner that re-fits parameters inside each training window.</p></div></article><article className="warn"><TestTube2/><div><b>Reality model</b><span>fees, fills, slippage, market impact</span><p>Generic friction stress is available. Verified execution modeling needs order/fill data and a documented cost model.</p></div></article></div></Panel><Panel title="RESEARCH PROCESS CHECK" sub="controls that reduce accidental overfitting"><div className="svChecklist"><div className="ok"><ShieldCheck/><span><b>Reproducible resampling</b><small>fixed seeds in deterministic validation tests</small></span></div><div className="warn"><AlertTriangle/><span><b>Selective curation</b><small>current sample intentionally excludes selected losses</small></span></div><div className="warn"><AlertTriangle/><span><b>Future holdout not frozen</b><small>best next evidence is a locked model scored on future outcomes without changing exclusions afterward</small></span></div><div className="blocked"><LockKeyhole/><span><b>Futures context unavailable</b><small>regime-conditioned validation remains blocked</small></span></div></div><button className="svPythonButton" onClick={()=>openPython('Create an overfitting audit for my current QNT research process. Explain PBO/CSCV, Deflated Sharpe, purged cross-validation, walk-forward optimization, parameter sensitivity, and execution reality modeling. For each, state whether my current data can support it, what exact extra inputs are required, and do not fabricate a metric when requirements are missing.')}><BarChart3 size={12}/> OPEN OVERFIT AUDIT IN PYTHON STUDIO</button></Panel></div>}
  </div>;
}
