import React,{useMemo,useState}from'react';
import{AlertTriangle,BarChart3,CheckCircle2,FlaskConical,GitBranch,LockKeyhole,RefreshCw,ShieldCheck,TestTube2}from'lucide-react';
import{Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{personalModel}from'./personalDataset.js';

const FUNCTIONS=['OVERVIEW','HOLDOUT','BOOT','STABILITY','INFLUENCE','STRESS','OVERFIT'];
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
const median=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const quantile=(a,q)=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[Math.min(i+1,x.length-1)]-x[i])*f};
const fmt=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const pct=(n,d=1)=>Number.isFinite(Number(n))?`${Number(n).toFixed(d)}%`:'—';
const signed=(n,d=2)=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(d)}R`:'—';
function rng(seed){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function maxDrawdownR(a=[]){let eq=0,peak=0,dd=0;for(const r of a){eq+=r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return dd}
function longestLossStreak(a=[]){let cur=0,best=0;for(const r of a){if(r<0){cur++;best=Math.max(best,cur)}else cur=0}return best}
function stats(a=[]){const wins=a.filter(x=>x>0),losses=a.filter(x=>x<0),sumWin=wins.reduce((s,v)=>s+v,0),sumLoss=Math.abs(losses.reduce((s,v)=>s+v,0));return{n:a.length,expectancy:mean(a),median:median(a),winRate:a.length?wins.length/a.length*100:null,lossRate:a.length?losses.length/a.length*100:null,pf:sumLoss?sumWin/sumLoss:null,maxDd:maxDrawdownR(a),lossStreak:longestLossStreak(a)}}
function bootstrap(a,reps=5000,seed=1701){const rand=rng(seed),ev=[],wr=[];for(let b=0;b<reps;b++){let sum=0,wins=0;for(let i=0;i<a.length;i++){const v=a[Math.floor(rand()*a.length)]??0;sum+=v;if(v>0)wins++}ev.push(sum/a.length);wr.push(wins/a.length*100)}return{ev,wr,p5:quantile(ev,.05),p50:quantile(ev,.5),p95:quantile(ev,.95),pPos:ev.filter(x=>x>0).length/reps*100,wr5:quantile(wr,.05),wr95:quantile(wr,.95)}}
function blockBootstrap(a,block=3,reps=3000,seed=991){const rand=rng(seed),ev=[];for(let b=0;b<reps;b++){const sample=[];while(sample.length<a.length){const start=Math.floor(rand()*a.length);for(let j=0;j<block&&sample.length<a.length;j++)sample.push(a[(start+j)%a.length])}ev.push(mean(sample))}return{ev,p5:quantile(ev,.05),p50:quantile(ev,.5),p95:quantile(ev,.95),pPos:ev.filter(x=>x>0).length/reps*100}}
function hist(values,bins=24){if(!values.length)return[];const lo=Math.min(...values),hi=Math.max(...values),w=(hi-lo||1)/bins,out=Array.from({length:bins},(_,i)=>({x:lo+w*(i+.5),count:0}));for(const v of values){const i=Math.min(bins-1,Math.max(0,Math.floor((v-lo)/(w||1))));out[i].count++}return out}
function rolling(a,n){const out=[];for(let i=n-1;i<a.length;i++){const s=a.slice(i-n+1,i+1),m=stats(s);out.push({trade:i+1,expectancy:m.expectancy,winRate:m.winRate})}return out}
function walkForward(a,train=12,test=4){const folds=[];let end=train;while(end<a.length){const trainSlice=a.slice(0,end),testSlice=a.slice(end,Math.min(a.length,end+test));if(!testSlice.length)break;folds.push({fold:folds.length+1,trainN:trainSlice.length,testN:testSlice.length,trainEv:mean(trainSlice),testEv:mean(testSlice),trainWr:stats(trainSlice).winRate,testWr:stats(testSlice).winRate});end+=test}return folds}
function stressRows(a,friction){const dropTop=(k)=>{const indexed=a.map((v,i)=>({v,i})),remove=new Set(indexed.filter(x=>x.v>0).sort((x,y)=>y.v-x.v).slice(0,k).map(x=>x.i));return a.filter((_,i)=>!remove.has(i))};const lossWorse=a.map(v=>v<0?v*1.25:v);const withFriction=x=>a.map(v=>v-x);return[
  ['Baseline',a,'Current curated sequence'],
  ['Drop top winner',dropTop(1),'Tail-dependence test'],
  ['Drop top 3 winners',dropTop(3),'Tail-dependence test'],
  ['Drop top 5 winners',dropTop(5),'Extreme tail-dependence test'],
  ['Losses +25%',lossWorse,'Loss-magnitude stress'],
  [`Friction ${friction.toFixed(2)}R`,withFriction(friction),'Generic per-trade friction in normalized units'],
  ['Friction 0.10R',withFriction(.10),'Generic per-trade friction in normalized units'],
  ['Friction 0.20R',withFriction(.20),'Generic per-trade friction in normalized units'],
].map(([name,series,note])=>({name,note,...stats(series)}))}
function Card({label,value,sub,tone=''}){return <div className="svCard"><span>{label}</span><b className={tone}>{value}</b><small>{sub||''}</small></div>}
function Panel({title,sub,children,actions}){return <section className="svPanel"><header><div><b>{title}</b><span>{sub}</span></div>{actions}</header>{children}</section>}

export default function StrategyValidationLab(){
  const[fn,setFn]=useState('OVERVIEW'),[friction,setFriction]=useState(.05);
  const r=personalModel.evalR||[],base=useMemo(()=>stats(r),[r]),boot=useMemo(()=>bootstrap(r),[r]),block=useMemo(()=>blockBootstrap(r),[r]),bootHist=useMemo(()=>hist(boot.ev),[boot]);
  const holdouts=useMemo(()=>[.5,.6,.7,.8].map(split=>{const cut=Math.max(1,Math.min(r.length-1,Math.round(r.length*split))),train=r.slice(0,cut),test=r.slice(cut);return{split:`${Math.round(split*100)}/${100-Math.round(split*100)}`,trainN:train.length,testN:test.length,trainEv:mean(train),testEv:mean(test),trainWr:stats(train).winRate,testWr:stats(test).winRate}}),[r]);
  const folds=useMemo(()=>walkForward(r),[r]),roll5=useMemo(()=>rolling(r,5),[r]),roll10=useMemo(()=>rolling(r,10),[r]);
  const influence=useMemo(()=>r.map((value,i)=>{const next=r.filter((_,j)=>j!==i),ev=mean(next);return{trade:i+1,value,leaveOutEv:ev,delta:ev-base.expectancy}}).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)),[r,base.expectancy]);
  const stress=useMemo(()=>stressRows(r,friction),[r,friction]);
  const experiments=useMemo(()=>{try{return JSON.parse(localStorage.getItem('qnt.experiments')||'[]')}catch{return[]}},[]);
  const openPython=(prompt)=>{window.dispatchEvent(new CustomEvent('qnt:navigate',{detail:{type:'research',tab:'Workspace'}}));window.setTimeout(()=>window.dispatchEvent(new CustomEvent('qnt:copilot-prompt',{detail:{prompt}})),40)};
  const stability=[...new Set([...roll5.map(x=>x.trade),...roll10.map(x=>x.trade)])].sort((a,b)=>a-b).map(trade=>({trade,e5:roll5.find(x=>x.trade===trade)?.expectancy,w5:roll5.find(x=>x.trade===trade)?.winRate,e10:roll10.find(x=>x.trade===trade)?.expectancy,w10:roll10.find(x=>x.trade===trade)?.winRate}));

  return <div className="svPage"><div className="svTitle"><div><span>STRATEGY TESTING</span><h1>Validation Lab</h1><p>Out-of-sample discipline, resampling, stability, influence and robustness tests for the current research model.</p></div><button onClick={()=>openPython('Use Python to run a full robustness audit of my current curated strategy model. Include bootstrap uncertainty, tail stress, sequence stability, leave-one-out influence and a clear list of tests that cannot be validly computed yet. Return charts or tables as QNT artifacts where useful.')}><FlaskConical size={13}/> PYTHON AUDIT</button></div>
  <nav className="svNav">{FUNCTIONS.map(x=><button key={x} className={fn===x?'active':''} onClick={()=>setFn(x)}><kbd>{x}</kbd></button>)}</nav>
  <div className="svNotice"><AlertTriangle size={13}/><span>The model is selectively curated and uses normalized payoff units rather than true stop-defined R. These tests measure robustness of the current sample; they do not turn it into an unbiased forecast.</span></div>

  {fn==='OVERVIEW'&&<><div className="svCards"><Card label="EVAL IDEAS" value={base.n}/><Card label="RAW MEAN" value={signed(base.expectancy)} sub="ordered eval sample" tone={base.expectancy>0?'good':''}/><Card label="MEDIAN" value={signed(base.median)}/><Card label="WIN RATE" value={pct(base.winRate)} sub={`${personalModel.evalWins}W / ${personalModel.evalLosses}L / ${personalModel.evalBreakevens}BE`}/><Card label="PROFIT FACTOR*" value={fmt(base.pf)} sub="raw normalized payoff"/><Card label="MAX DD*" value={`${fmt(base.maxDd)}R`} sub="sequence drawdown"/><Card label="LONGEST LOSS STREAK" value={base.lossStreak}/><Card label="BOOT 90% CI" value={`${signed(boot.p5)} → ${signed(boot.p95)}`} sub="iid resampling"/></div><div className="svGrid"><Panel title="ROBUSTNESS MAP" sub="what is already testable with the current sample"><div className="svReadiness"><div className="ok"><CheckCircle2/><b>Sequence holdouts</b><span>available</span></div><div className="ok"><CheckCircle2/><b>Bootstrap / block bootstrap</b><span>available</span></div><div className="ok"><CheckCircle2/><b>Influence / tail stress</b><span>available</span></div><div className="warn"><AlertTriangle/><b>True OOS by date</b><span>timestamps not in public model payload</span></div><div className="blocked"><LockKeyhole/><b>Purged CV / CPCV</b><span>needs event timestamps + label horizons</span></div><div className="blocked"><LockKeyhole/><b>PBO / Deflated Sharpe</b><span>needs structured multi-trial backtest matrix</span></div></div></Panel><Panel title="BOOTSTRAP SNAPSHOT" sub="5,000 iid resamples of the observed eval outcomes"><div className="svMiniStats"><div><span>P(E &gt; 0)</span><b>{pct(boot.pPos)}</b></div><div><span>P5</span><b>{signed(boot.p5)}</b></div><div><span>MEDIAN</span><b>{signed(boot.p50)}</b></div><div><span>P95</span><b>{signed(boot.p95)}</b></div></div><p className="svFoot">Resampling repeats the observed outcomes and therefore inherits the sample-selection problem. It is uncertainty analysis, not proof of edge.</p></Panel></div></>}

  {fn==='HOLDOUT'&&<div className="svGrid one"><Panel title="SEQUENCE HOLDOUTS" sub="earlier observations as train, later observations as test · no parameter tuning"><div className="svTable hold"><div className="head"><span>SPLIT</span><span>TRAIN N</span><span>TEST N</span><span>TRAIN E</span><span>TEST E</span><span>TRAIN WR</span><span>TEST WR</span></div>{holdouts.map(x=><div key={x.split}><b>{x.split}</b><span>{x.trainN}</span><span>{x.testN}</span><span>{signed(x.trainEv)}</span><span className={x.testEv>=0?'good':'bad'}>{signed(x.testEv)}</span><span>{pct(x.trainWr)}</span><span>{pct(x.testWr)}</span></div>)}</div></Panel><Panel title="EXPANDING WALK-FORWARD VALIDATION" sub="12-observation initial train window, then 4-observation forward tests · no re-optimization"><ResponsiveContainer width="100%" height={320}><BarChart data={folds}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="fold" tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><Legend wrapperStyle={{fontSize:8}}/><Bar name="Train expectancy" dataKey="trainEv"/><Bar name="Forward-test expectancy" dataKey="testEv"/></BarChart></ResponsiveContainer><div className="svFoldStrip">{folds.map(x=><div key={x.fold}><span>FOLD {x.fold}</span><b className={x.testEv>=0?'good':'bad'}>{signed(x.testEv)}</b><small>{x.testN} forward observations · WR {pct(x.testWr)}</small></div>)}</div><p className="svFoot">This is an expanding sequence test, not full walk-forward optimization, because QNT is not re-fitting a parameterized strategy in each fold yet.</p></Panel></div>}

  {fn==='BOOT'&&<div className="svGrid one"><Panel title="EXPECTANCY RESAMPLING" sub="iid bootstrap compared with 3-trade moving-block bootstrap"><div className="svCards compact"><Card label="IID P(E>0)" value={pct(boot.pPos)}/><Card label="IID 90% CI" value={`${signed(boot.p5)} → ${signed(boot.p95)}`}/><Card label="BLOCK P(E>0)" value={pct(block.pPos)}/><Card label="BLOCK 90% CI" value={`${signed(block.p5)} → ${signed(block.p95)}`}/><Card label="BOOT WR 90%" value={`${pct(boot.wr5)} → ${pct(boot.wr95)}`}/></div><ResponsiveContainer width="100%" height={390}><BarChart data={bootHist}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="x" tick={{fontSize:8}} stroke="#555b64" tickFormatter={v=>fmt(v,1)}/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}} labelFormatter={v=>`${fmt(v,2)}R expectancy`}/><ReferenceLine x={0} stroke="#7b818b"/><Bar dataKey="count"/></BarChart></ResponsiveContainer><div className="svActions"><button onClick={()=>openPython('Use Python to compare iid bootstrap, moving-block bootstrap, and a Bayesian posterior view of my current strategy outcomes. Explain what each method assumes and return a compact comparison table and distribution chart as QNT artifacts.')}><RefreshCw size={12}/> RUN DEEPER IN PYTHON</button></div></Panel></div>}

  {fn==='STABILITY'&&<div className="svGrid one"><Panel title="ROLLING EXPECTANCY" sub="5-trade and 10-trade windows across the ordered eval sequence"><ResponsiveContainer width="100%" height={360}><LineChart data={stability}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="trade" tick={{fontSize:8}} stroke="#555b64"/><YAxis tick={{fontSize:8}} stroke="#555b64"/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><ReferenceLine y={0} stroke="#555b64"/><Legend wrapperStyle={{fontSize:8}}/><Line name="5-trade expectancy" dataKey="e5" dot={false} strokeWidth={1.4}/><Line name="10-trade expectancy" dataKey="e10" dot={false} strokeWidth={1.4}/></LineChart></ResponsiveContainer></Panel><Panel title="ROLLING WIN RATE" sub="use alongside expectancy so a few large winners do not hide outcome instability"><ResponsiveContainer width="100%" height={320}><LineChart data={stability}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="trade" tick={{fontSize:8}} stroke="#555b64"/><YAxis domain={[0,100]} tick={{fontSize:8}} stroke="#555b64" tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><Legend wrapperStyle={{fontSize:8}}/><Line name="5-trade WR" dataKey="w5" dot={false} strokeWidth={1.4}/><Line name="10-trade WR" dataKey="w10" dot={false} strokeWidth={1.4}/></LineChart></ResponsiveContainer></Panel></div>}

  {fn==='INFLUENCE'&&<div className="svGrid one"><Panel title="LEAVE-ONE-OUT INFLUENCE" sub="recompute mean expectancy after removing each single observation"><div className="svCards compact"><Card label="BASE EXPECTANCY" value={signed(base.expectancy)}/><Card label="MOST INFLUENTIAL" value={`Trade ${influence[0]?.trade??'—'}`} sub={`observed ${signed(influence[0]?.value)}`}/><Card label="LEAVE-OUT EXPECTANCY" value={signed(influence[0]?.leaveOutEv)}/><Card label="CHANGE" value={signed(influence[0]?.delta)} sub="vs baseline"/></div><ResponsiveContainer width="100%" height={390}><BarChart data={influence.slice(0,14)} layout="vertical"><CartesianGrid stroke="#171a20" horizontal={false}/><XAxis type="number" tick={{fontSize:8}} stroke="#555b64"/><YAxis type="category" dataKey="trade" tick={{fontSize:8}} stroke="#555b64" tickFormatter={v=>`T${v}`}/><Tooltip contentStyle={{background:'#07090b',border:'1px solid #2d333b',fontSize:9}}/><ReferenceLine x={0} stroke="#555b64"/><Bar name="Expectancy change when removed" dataKey="delta"/></BarChart></ResponsiveContainer><p className="svFoot">Large absolute bars mean the strategy summary is sensitive to that single outcome. This is a jackknife-style influence diagnostic, not an instruction to exclude that trade.</p></Panel></div>}

  {fn==='STRESS'&&<div className="svGrid one"><Panel title="ROBUSTNESS STRESS MATRIX" sub="tail removal, worse losses and generic research friction" actions={<label className="svFriction"><span>CUSTOM FRICTION</span><input type="number" min="0" max="1" step="0.01" value={friction} onChange={e=>setFriction(Math.max(0,Math.min(1,Number(e.target.value)||0)))}/><b>R / trade</b></label>}><div className="svTable stress"><div className="head"><span>SCENARIO</span><span>N</span><span>EXPECTANCY</span><span>WIN RATE</span><span>PF*</span><span>MAX DD*</span><span>NOTE</span></div>{stress.map(x=><div key={x.name}><b>{x.name}</b><span>{x.n}</span><span className={x.expectancy>=0?'good':'bad'}>{signed(x.expectancy)}</span><span>{pct(x.winRate)}</span><span>{fmt(x.pf)}</span><span>{fmt(x.maxDd)}R</span><small>{x.note}</small></div>)}</div><p className="svFoot">Friction is expressed in the model's normalized payoff units because verified execution-cost and stop-defined-R data are not connected. It should not be read as an actual commission or futures fill estimate.</p></Panel></div>}

  {fn==='OVERFIT'&&<div className="svGrid"><Panel title="OVERFITTING GUARD" sub="professional tests QNT should compute only when their required inputs exist"><div className="svMethodList"><article className="blocked"><LockKeyhole/><div><b>PBO / CSCV</b><span>Probability of backtest overfitting</span><p>Needs many strategy configurations evaluated across consistent subperiods. Current experiment registry: {experiments.length}; QNT does not yet have a configuration × subperiod performance matrix.</p></div></article><article className="blocked"><LockKeyhole/><div><b>Deflated Sharpe Ratio</b><span>Adjust performance for non-normality and multiple testing</span><p>Needs a defensible Sharpe series and the effective number of trials. QNT will not apply DSR to the current non-annualized trade mean/σ shortcut.</p></div></article><article className="blocked"><LockKeyhole/><div><b>Purged / embargo CV</b><span>Leakage-aware financial cross-validation</span><p>Needs timestamps and event/label horizons so overlapping information can be removed between folds.</p></div></article><article className="warn"><GitBranch/><div><b>Walk-forward optimization</b><span>Train older history, test later history</span><p>Sequence validation is available now. Full WFO requires a parameterized strategy runner that re-fits parameters inside each training window.</p></div></article><article className="warn"><TestTube2/><div><b>Reality model</b><span>fees, fills, slippage, market impact</span><p>Generic friction stress is available. Verified execution modeling needs order/fill data and a documented cost model.</p></div></article></div></Panel><Panel title="RESEARCH PROCESS CHECK" sub="controls that reduce accidental overfitting"><div className="svChecklist"><div className="ok"><ShieldCheck/><span><b>Reproducible resampling</b><small>fixed seeds in deterministic validation tests</small></span></div><div className="warn"><AlertTriangle/><span><b>Selective curation</b><small>current sample intentionally excludes selected losses</small></span></div><div className="warn"><AlertTriangle/><span><b>Future holdout not frozen</b><small>best next evidence is a locked model scored on future outcomes without editing exclusions afterward</small></span></div><div className="blocked"><LockKeyhole/><span><b>Futures context unavailable</b><small>regime-conditioned validation remains blocked</small></span></div></div><button className="svPythonButton" onClick={()=>openPython('Create an overfitting audit for my current QNT research process. Explain PBO/CSCV, Deflated Sharpe, purged cross-validation, walk-forward optimization, and reality modeling. For each, state whether my current data can support it, what exact extra inputs are required, and do not fabricate a metric when requirements are missing.')}><BarChart3 size={12}/> OPEN OVERFIT AUDIT IN PYTHON STUDIO</button></Panel></div>}
  </div>;
}
