import React,{useEffect,useMemo,useState} from 'react';
import {Database,RefreshCw,Save,Search,ShieldAlert} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis,ZAxis} from 'recharts';
import {personalModel} from './personalDataset.js';

const WATCH=['QQQ','SPY','AAPL','NVDA','MSFT'];
const FUNCTIONS=['TOP','HMAP','DIST','ROLL','BETA','VOLC','VCA','QQL','SCEN','EXP'];
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
const median=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const quantile=(a,q)=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[Math.min(i+1,x.length-1)]-x[i])*f};
const pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`:'—';
const num=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const money=n=>Number.isFinite(Number(n))?`$${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—';
const date=t=>new Date(Number(t)*1000).toLocaleDateString(undefined,{month:'short',day:'numeric'});
function dailyReturns(c=[]){const out=[];for(let i=1;i<c.length;i++){const a=c[i-1]?.close,b=c[i]?.close;if(a>0&&Number.isFinite(b))out.push({time:c[i].time,r:b/a-1})}return out}
function rvFromReturns(r=[]){if(r.length<3)return null;const m=mean(r),sd=Math.sqrt(mean(r.map(x=>(x-m)**2)));return sd*Math.sqrt(252)*100}
function realizedVol(c=[],n=20){return rvFromReturns(dailyReturns(c).slice(-n).map(x=>x.r))}
function rollingVol(c=[],n=20){const r=dailyReturns(c),out=[];for(let i=n-1;i<r.length;i++){const slice=r.slice(i-n+1,i+1).map(x=>x.r),v=rvFromReturns(slice);if(Number.isFinite(v))out.push({time:r[i].time,value:v})}return out}
function periodReturn(c=[],n=20){if(c.length<2)return null;const end=c.at(-1)?.close,start=c[Math.max(0,c.length-1-n)]?.close;return start>0&&Number.isFinite(end)?(end/start-1)*100:null}
function maxDrawdown(c=[]){let p=-Infinity,d=0;for(const x of c){if(!Number.isFinite(x.close))continue;p=Math.max(p,x.close);if(p>0)d=Math.max(d,(p-x.close)/p)}return d*100}
function pearson(a,b){if(a.length!==b.length||a.length<3)return null;const ma=mean(a),mb=mean(b);let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}const den=Math.sqrt(da*db);return den?n/den:null}
function alignedReturns(a=[],b=[]){const bm=new Map(dailyReturns(b).map(x=>[x.time,x.r]));return dailyReturns(a).filter(x=>bm.has(x.time)).map(x=>({time:x.time,a:x.r,b:bm.get(x.time)}))}
function correlation(a=[],b=[],lookback=60){const p=alignedReturns(a,b).slice(-lookback);return pearson(p.map(x=>x.a),p.map(x=>x.b))}
function regression(a=[],b=[],lookback=120){const p=alignedReturns(a,b).slice(-lookback);if(p.length<10)return null;const x=p.map(v=>v.b),y=p.map(v=>v.a),mx=mean(x),my=mean(y),vx=mean(x.map(v=>(v-mx)**2)),cov=mean(x.map((v,i)=>(v-mx)*(y[i]-my)));if(!vx)return null;const beta=cov/vx,alpha=my-beta*mx,corr=pearson(y,x);return{beta,alphaAnnual:alpha*252*100,r2:Number.isFinite(corr)?corr*corr:null,points:p.map(v=>({x:v.b*100,y:v.a*100}))}}
function rollingCorrelation(a=[],b=[],n=60){const p=alignedReturns(a,b),out=[];for(let i=n-1;i<p.length;i++){const s=p.slice(i-n+1,i+1),v=pearson(s.map(x=>x.a),s.map(x=>x.b));if(Number.isFinite(v))out.push({time:p[i].time,label:date(p[i].time),corr:v})}return out}
function nearest(rows,target,side){return rows.filter(c=>(!side||c.side===side)&&Number.isFinite(c.strike)).sort((a,b)=>Math.abs(a.strike-target)-Math.abs(b.strike-target))[0]||null}
function optionMetrics(payload){const c=payload?.contracts||[],spot=payload?.underlyingPrice||0;const calc=dte=>{const b=c.filter(x=>x.dte===dte),call=nearest(b,spot,'call'),put=nearest(b,spot,'put'),ivs=[call?.iv,put?.iv].filter(Number.isFinite),putWing=nearest(b,spot*.9,'put'),callWing=nearest(b,spot*1.1,'call');return{iv:ivs.length?mean(ivs)*100:null,skew:Number.isFinite(putWing?.iv)&&Number.isFinite(callWing?.iv)?(putWing.iv-callWing.iv)*100:null}};const dtes=[...new Set(c.map(x=>x.dte).filter(Number.isFinite))].sort((a,b)=>a-b),near30=[...dtes].sort((a,b)=>Math.abs(a-30)-Math.abs(b-30))[0],near90=[...dtes].sort((a,b)=>Math.abs(a-90)-Math.abs(b-90))[0],m30=Number.isFinite(near30)?calc(near30):{},m90=Number.isFinite(near90)?calc(near90):{};return{dte30:near30,atmIv:m30.iv,skew:m30.skew,termSlope:Number.isFinite(m30.iv)&&Number.isFinite(m90.iv)?m90.iv-m30.iv:null}}
function metricsFor(symbol,h){const c=h[symbol]||[];return{symbol,last:c.at(-1)?.close,r1:periodReturn(c,1),r5:periodReturn(c,5),r20:periodReturn(c,20),r60:periodReturn(c,60),rv20:realizedVol(c,20),rv60:realizedVol(c,60),dd:maxDrawdown(c),corrSpy:symbol==='SPY'?1:correlation(c,h.SPY||[],60)}}
function histogram(c=[]){const r=dailyReturns(c).map(x=>x.r*100);if(!r.length)return[];const lo=Math.min(...r),hi=Math.max(...r),bins=18,w=(hi-lo||1)/bins,out=Array.from({length:bins},(_,i)=>({x:lo+w*(i+.5),count:0}));for(const v of r){const i=Math.min(bins-1,Math.max(0,Math.floor((v-lo)/(w||1))));out[i].count++}return out}
function volCone(c=[]){return[10,20,60].map(n=>{const s=rollingVol(c,n).map(x=>x.value);return{lookback:`${n}D`,current:s.at(-1),p25:quantile(s,.25),median:median(s),p75:quantile(s,.75),p90:quantile(s,.9)}})}
function rng(seed){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function simulateScenario({wrShift,winScale,lossScale,streakiness,paths=1500,trades=100,seed=7331}){const rand=rng(seed),baseW=Math.max(.05,Math.min(.9,personalModel.winProbability+wrShift/100)),baseL=personalModel.lossProbability,baseB=personalModel.breakevenProbability,total=baseW+baseL+baseB,w=baseW/total,l=baseL/total;const wins=personalModel.winR.map(r=>1.1*Math.log1p(Math.max(0,r))*winScale),losses=personalModel.lossR.map(r=>r*lossScale),terminal=[],drawdowns=[],sample=[];for(let p=0;p<paths;p++){let eq=0,peak=0,maxDd=0,lastLoss=false;const path=[];for(let t=0;t<trades;t++){let lp=l;if(lastLoss)lp=Math.min(.92,lp+streakiness*(1-lp));let wp=w*(1-lp)/(1-l);wp=Math.max(0,Math.min(1-lp,wp));const u=rand();let r=0;if(u<lp){r=losses[Math.floor(rand()*losses.length)]??0;lastLoss=true}else if(u<lp+wp){r=wins[Math.floor(rand()*wins.length)]??0;lastLoss=false}else lastLoss=false;eq+=r;peak=Math.max(peak,eq);maxDd=Math.max(maxDd,peak-eq);if(p<30&&t%2===0)path.push({trade:t+1,equity:eq})}terminal.push(eq);drawdowns.push(maxDd);if(p<30)sample.push(path)}return{terminal,drawdowns,sample,median:median(terminal),p10:quantile(terminal,.1),p90:quantile(terminal,.9),pLoss:terminal.filter(x=>x<0).length/terminal.length*100,medianDd:median(drawdowns),winProbability:w*100,lossProbability:l*100}}
function Panel({title,sub,children,actions}){return <section className="twPanel"><div className="twPanelHead"><div><b>{title}</b><span>{sub}</span></div>{actions}</div>{children}</section>}

export default function TerminalWorkbench(){
  const saved=(()=>{try{return localStorage.getItem('qnt.active.symbol')||'QQQ'}catch{return'QQQ'}})();
  const [fn,setFn]=useState('TOP'),[quotes,setQuotes]=useState([]),[histories,setHistories]=useState({}),[health,setHealth]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[volRows,setVolRows]=useState([]),[volLoading,setVolLoading]=useState(false);
  const [symbol,setSymbol]=useState(saved),[pairA,setPairA]=useState('QQQ'),[pairB,setPairB]=useState('SPY'),[corrWindow,setCorrWindow]=useState(60);
  const [qql,setQql]=useState('SHOW WATCH METRICS RETURN20 RV20 MAXDD CORRSPY SORT RV20 DESC');
  const [wrShift,setWrShift]=useState(-5),[winScale,setWinScale]=useState(.85),[lossScale,setLossScale]=useState(1.15),[streakiness,setStreakiness]=useState(.15),[seed,setSeed]=useState(7331);
  const [experiments,setExperiments]=useState(()=>{try{return JSON.parse(localStorage.getItem('qnt.experiments')||'[]')}catch{return[]}});
  const loadBase=async()=>{setLoading(true);setError('');try{const [qRes,hRes,...cs]=await Promise.all([fetch(`/api/market/quotes?symbols=${WATCH.join(',')}`),fetch('/api/status'),...WATCH.map(s=>fetch(`/api/market/candles?symbol=${s}&resolution=D&countback=365`))]);const q=await qRes.json(),h=await hRes.json();if(qRes.ok)setQuotes(q.quotes||[]);setHealth(h);const next={};for(let i=0;i<cs.length;i++){const d=await cs[i].json();if(cs[i].ok)next[WATCH[i]]=d.candles||[]}setHistories(next);if(!qRes.ok)setError(q.error||'Quote request failed')}catch(e){setError(e.message)}finally{setLoading(false)}};
  const loadVca=async()=>{setVolLoading(true);const out=[];for(const s of WATCH){try{const r=await fetch(`/api/options-chain?symbol=${s}&dtes=30,60,90&strikeLimit=8`),d=await r.json(),m=metricsFor(s,histories);if(r.ok){const o=optionMetrics(d);out.push({...m,...o,ivRv:Number.isFinite(o.atmIv)&&Number.isFinite(m.rv20)?o.atmIv-m.rv20:null,status:'OK'})}else out.push({...m,status:'NO OPTIONS'})}catch{out.push({...metricsFor(s,histories),status:'NO OPTIONS'})}}setVolRows(out);setVolLoading(false)};
  useEffect(()=>{loadBase();let pending=null;try{pending=JSON.parse(sessionStorage.getItem('qnt.workbench.command')||'null');if(pending)sessionStorage.removeItem('qnt.workbench.command')}catch{}if(pending?.fn)setFn(pending.fn);const h=e=>{if(e.detail?.fn)setFn(e.detail.fn)};window.addEventListener('qnt:workbench-command',h);return()=>window.removeEventListener('qnt:workbench-command',h)},[]);
  useEffect(()=>{if(fn==='VCA'&&!volRows.length&&Object.keys(histories).length)loadVca()},[fn,histories]);
  useEffect(()=>{try{localStorage.setItem('qnt.experiments',JSON.stringify(experiments.slice(0,30)));localStorage.setItem('qnt.active.symbol',symbol)}catch{}},[experiments,symbol]);
  const rows=useMemo(()=>WATCH.map(s=>{const m=metricsFor(s,histories),q=quotes.find(x=>x.symbol===s);return{...m,last:q?.last??m.last,changePct:Number.isFinite(q?.changePct)?q.changePct:m.r1}}),[histories,quotes]);
  const hist=histories[symbol]||[],rets=dailyReturns(hist),dist=useMemo(()=>histogram(hist),[hist]),cone=useMemo(()=>volCone(hist),[hist]);
  const distStats=useMemo(()=>{const x=rets.map(v=>v.r*100);return{mean:mean(x),sd:x.length?Math.sqrt(mean(x.map(v=>(v-mean(x))**2))):null,up:x.length?x.filter(v=>v>0).length/x.length*100:null,best:x.length?Math.max(...x):null,worst:x.length?Math.min(...x):null}},[hist]);
  const roll=useMemo(()=>rollingCorrelation(histories[pairA]||[],histories[pairB]||[],corrWindow),[histories,pairA,pairB,corrWindow]);
  const beta=useMemo(()=>regression(histories[symbol]||[],histories.SPY||[],120),[histories,symbol]);
  const scenario=useMemo(()=>simulateScenario({wrShift,winScale,lossScale,streakiness,seed}),[wrShift,winScale,lossScale,streakiness,seed]);
  const scenarioChart=useMemo(()=>{const p=scenario.sample.slice(0,12),map=new Map();p.forEach((path,i)=>path.forEach(x=>{const row=map.get(x.trade)||{trade:x.trade};row[`p${i+1}`]=x.equity;map.set(x.trade,row)}));return[...map.values()].sort((a,b)=>a.trade-b.trade)},[scenario]);
  const parseQql=()=>{const t=qql.trim().toUpperCase().split(/\s+/),metricMap={RETURN1:'r1',RETURN5:'r5',RETURN20:'r20',RETURN60:'r60',RV20:'rv20',RV60:'rv60',MAXDD:'dd',CORRSPY:'corrSpy',LAST:'last'},mIndex=t.indexOf('METRICS');let symbols=t[1]==='WATCH'?WATCH:t.slice(1,mIndex>0?mIndex:1).filter(x=>WATCH.includes(x));if(!symbols.length)symbols=WATCH;let metricTokens=mIndex>=0?t.slice(mIndex+1):['RETURN20','RV20','MAXDD'];const sortI=metricTokens.indexOf('SORT');if(sortI>=0)metricTokens=metricTokens.slice(0,sortI);const metrics=metricTokens.filter(x=>metricMap[x]),sI=t.indexOf('SORT'),sortMetric=sI>=0?metricMap[t[sI+1]]:null,desc=t[sI+2]!=='ASC';let out=symbols.map(s=>{const m=metricsFor(s,histories),q=quotes.find(x=>x.symbol===s),base={...m,last:q?.last??m.last};return{symbol:s,...Object.fromEntries(metrics.map(k=>[k,base[metricMap[k]]]))}});if(sortMetric){const token=Object.keys(metricMap).find(k=>metricMap[k]===sortMetric);if(token)out.sort((a,b)=>((a[token]??-Infinity)-(b[token]??-Infinity))*(desc?-1:1))}return{metrics,rows:out}};
  const qqlResult=useMemo(parseQql,[qql,histories,quotes]);
  const saveExperiment=()=>{const item={id:`EXP-${Date.now().toString(36).toUpperCase()}`,createdAt:new Date().toISOString(),model:personalModel.label,config:{wrShift,winScale,lossScale,streakiness,seed},results:{median:scenario.median,p10:scenario.p10,p90:scenario.p90,pLoss:scenario.pLoss,medianDd:scenario.medianDd}};setExperiments(x=>[item,...x].slice(0,30));setFn('EXP')};
  const route=(section,detail={})=>window.dispatchEvent(new CustomEvent('qnt:route',{detail:{section,...detail}}));
  const selector=<div className="twSelectors"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{WATCH.map(s=><option key={s}>{s}</option>)}</select></div>;
  return <div className="twTerminal"><header className="twHeader"><div><span>QNT / ADVANCED TERMINAL FUNCTIONS</span><h1>{fn} <small>Bloomberg-inspired research workflow · QNT implementation</small></h1></div><button onClick={loadBase}><RefreshCw size={11}/>{loading?'SYNCING':'SYNC DATA'}</button></header><nav className="twFunctions">{FUNCTIONS.map(x=><button key={x} className={fn===x?'active':''} onClick={()=>setFn(x)}><kbd>{x}</kbd></button>)}</nav>{error&&<div className="twError"><ShieldAlert size={12}/>{error}</div>}

  {fn==='TOP'&&<div className="twGrid"><Panel title="TOP / MARKET MONITOR" sub="provider-backed watchlist analytics"><div className="twMarketTable"><div className="head"><span>SECURITY</span><span>LAST</span><span>1D</span><span>20D</span><span>RV20</span><span>MAX DD</span><span>CORR SPY</span></div>{rows.map(r=><button key={r.symbol} onClick={()=>route('Desk',{fn:'DES',symbol:r.symbol})}><span><b>{r.symbol}</b></span><span>{money(r.last)}</span><span className={(r.changePct??0)>=0?'up':'down'}>{pct(r.changePct)}</span><span>{pct(r.r20)}</span><span>{pct(r.rv20)}</span><span>{pct(-r.dd)}</span><span>{num(r.corrSpy,2)}</span></button>)}</div></Panel><Panel title="FUNCTION MAP" sub="jump directly into connected QNT tools"><div className="twLauncher">{[['DES','Desk','DES'],['CHART','Desk','CHART'],['CORR','Desk','CORR'],['OMON','Desk','OMON'],['SURF','Analytics','SURF'],['RVIV','Analytics','RVIV'],['MC','Research','Risk & Monte Carlo'],['PROP','Research','Prop Firm']].map(([label,section,target])=><button key={label} onClick={()=>section==='Research'?route('Research',{tab:target}):route(section,{fn:target,symbol})}><kbd>{label}</kbd><span>OPEN</span></button>)}</div></Panel><Panel title="SYSTEM PULSE" sub="data provenance and API state"><div className="twPulse"><div><span>SERVER</span><b>{health?.server?.ok?'ONLINE':'—'}</b></div><div><span>MARKETDATA</span><b>{health?.marketData?.configured?'CONNECTED':'OFFLINE'}</b></div><div><span>OPENAI</span><b>{health?.openai?.configured?'CONNECTED':'OFFLINE'}</b></div><div><span>CACHE</span><b>{health?.server?.cacheEntries??0}</b></div></div></Panel></div>}

  {fn==='HMAP'&&<Panel title="HMAP / CROSS-ASSET HEATMAP" sub="returns, volatility, drawdown and correlation across the watchlist"><div className="twHeat"><span/><b>1D</b><b>20D</b><b>60D</b><b>RV20</b><b>RV60</b><b>DD</b>{rows.flatMap(r=>[<button key={`${r.symbol}-h`} onClick={()=>{setSymbol(r.symbol);route('Desk',{fn:'DES',symbol:r.symbol})}}>{r.symbol}</button>,...[r.r1,r.r20,r.r60,r.rv20,r.rv60,-r.dd].map((v,i)=><span key={`${r.symbol}-${i}`} data-tone={!Number.isFinite(v)?'none':i<3?(v>5?'hot':v>0?'pos':v<-5?'cold':'neg'):(i===5?(v<-20?'cold':v<-10?'neg':'flat'):(v>40?'hot':v>25?'pos':'flat'))}>{i<3||i===5?pct(v):pct(v)}</span>)])}</div><p className="twFoot">Heat colors are descriptive buckets only, not trade signals.</p></Panel>}

  {fn==='DIST'&&<Panel title={`DIST / ${symbol} RETURN DISTRIBUTION`} sub="one-year daily close-to-close return histogram" actions={selector}><div className="twStatRow"><div><span>MEAN DAY</span><b>{pct(distStats.mean)}</b></div><div><span>DAILY SD</span><b>{pct(distStats.sd)}</b></div><div><span>UP DAYS</span><b>{pct(distStats.up)}</b></div><div><span>BEST DAY</span><b>{pct(distStats.best)}</b></div><div><span>WORST DAY</span><b>{pct(distStats.worst)}</b></div></div><ResponsiveContainer width="100%" height={430}><BarChart data={dist}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="x" tick={{fontSize:8}} tickFormatter={v=>`${v.toFixed(1)}%`} stroke="#515761"/><YAxis tick={{fontSize:8}} stroke="#515761"/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}} formatter={(v)=>[v,'days']} labelFormatter={v=>`${Number(v).toFixed(2)}% return bin`}/><Bar dataKey="count"/></BarChart></ResponsiveContainer></Panel>}

  {fn==='ROLL'&&<Panel title={`ROLL / ${pairA} × ${pairB}`} sub={`${corrWindow}-session rolling return correlation`} actions={<div className="twSelectors"><select value={pairA} onChange={e=>setPairA(e.target.value)}>{WATCH.map(s=><option key={s}>{s}</option>)}</select><select value={pairB} onChange={e=>setPairB(e.target.value)}>{WATCH.map(s=><option key={s}>{s}</option>)}</select><select value={corrWindow} onChange={e=>setCorrWindow(Number(e.target.value))}>{[20,60,120].map(n=><option key={n} value={n}>{n}D</option>)}</select></div>}><div className="twStatRow"><div><span>CURRENT CORR</span><b>{num(roll.at(-1)?.corr,3)}</b></div><div><span>MEDIAN</span><b>{num(median(roll.map(x=>x.corr)),3)}</b></div><div><span>LOW</span><b>{num(roll.length?Math.min(...roll.map(x=>x.corr)):null,3)}</b></div><div><span>HIGH</span><b>{num(roll.length?Math.max(...roll.map(x=>x.corr)):null,3)}</b></div></div><ResponsiveContainer width="100%" height={430}><LineChart data={roll}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="label" minTickGap={45} tick={{fontSize:8}} stroke="#515761"/><YAxis domain={[-1,1]} tick={{fontSize:8}} stroke="#515761"/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Line dataKey="corr" dot={false} strokeWidth={1.4}/></LineChart></ResponsiveContainer></Panel>}

  {fn==='BETA'&&<Panel title={`BETA / ${symbol} VS SPY`} sub="120-session daily-return regression" actions={selector}>{beta?<><div className="twStatRow"><div><span>BETA</span><b>{num(beta.beta,3)}</b></div><div><span>ANNUALIZED ALPHA*</span><b>{pct(beta.alphaAnnual)}</b></div><div><span>R²</span><b>{num(beta.r2,3)}</b></div><div><span>OBSERVATIONS</span><b>{beta.points.length}</b></div></div><ResponsiveContainer width="100%" height={430}><ScatterChart><CartesianGrid stroke="#171a20"/><XAxis type="number" dataKey="x" name="SPY" unit="%" tick={{fontSize:8}} stroke="#515761"/><YAxis type="number" dataKey="y" name={symbol} unit="%" tick={{fontSize:8}} stroke="#515761"/><ZAxis range={[16,16]}/><Tooltip cursor={{strokeDasharray:'3 3'}} contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Scatter data={beta.points}/></ScatterChart></ResponsiveContainer><p className="twFoot">*Alpha is a simple daily OLS intercept annualized by ×252; it is descriptive and not a forecast.</p></>:<div className="twEmpty"><b>Not enough aligned data</b></div>}</Panel>}

  {fn==='VOLC'&&<Panel title={`VOLC / ${symbol} VOLATILITY CONE`} sub="historical rolling realized-volatility percentiles" actions={selector}><div className="twCone"><div className="head"><span>WINDOW</span><span>CURRENT</span><span>25TH</span><span>MEDIAN</span><span>75TH</span><span>90TH</span></div>{cone.map(r=><div key={r.lookback}><span><b>{r.lookback}</b></span><span>{pct(r.current)}</span><span>{pct(r.p25)}</span><span>{pct(r.median)}</span><span>{pct(r.p75)}</span><span>{pct(r.p90)}</span></div>)}</div><ResponsiveContainer width="100%" height={330}><BarChart data={cone}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="lookback" tick={{fontSize:8}} stroke="#515761"/><YAxis tick={{fontSize:8}} stroke="#515761" tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/><Bar dataKey="current"/><Bar dataKey="median"/></BarChart></ResponsiveContainer></Panel>}

  {fn==='VCA'&&<Panel title="VCA / VOLATILITY & CORRELATION ANALYSIS" sub="cross-sectional IV, RV, skew, term structure and correlation" actions={<button className="twSmall" onClick={loadVca}><RefreshCw size={10}/>{volLoading?'LOADING':'REFRESH VCA'}</button>}><div className="twVca"><div className="head"><span>SECURITY</span><span>ATM IV</span><span>RV20</span><span>IV−RV</span><span>10% SKEW</span><span>TERM 90−30</span><span>CORR SPY</span><span>STATUS</span></div>{volRows.map(r=><button key={r.symbol} onClick={()=>route('Analytics',{fn:'RVIV',symbol:r.symbol,dte:r.dte30})}><span><b>{r.symbol}</b></span><span>{pct(r.atmIv)}</span><span>{pct(r.rv20)}</span><span>{Number.isFinite(r.ivRv)?`${r.ivRv>=0?'+':''}${r.ivRv.toFixed(1)}v`:'—'}</span><span>{Number.isFinite(r.skew)?`${r.skew.toFixed(1)}v`:'—'}</span><span>{Number.isFinite(r.termSlope)?`${r.termSlope>=0?'+':''}${r.termSlope.toFixed(1)}v`:'—'}</span><span>{num(r.corrSpy,2)}</span><span>{r.status}</span></button>)}</div><p className="twFoot">VCA only loads when opened. Option values come from returned provider chains; realized volatility and correlation are calculated from provider daily candles.</p></Panel>}

  {fn==='QQL'&&<Panel title="QQL / QNT QUERY LANGUAGE" sub="deterministic query layer over loaded market data"><div className="twQql"><div className="twQqlInput"><Search size={12}/><input value={qql} onChange={e=>setQql(e.target.value)} spellCheck="false"/></div><div className="twPresets">{['SHOW WATCH METRICS RETURN20 RV20 MAXDD CORRSPY SORT RV20 DESC','SHOW QQQ SPY NVDA METRICS RETURN5 RETURN20 RV20 RV60','SHOW WATCH METRICS LAST RETURN1 RETURN60 SORT RETURN60 DESC'].map(x=><button key={x} onClick={()=>setQql(x)}>{x}</button>)}</div><div className="twQueryTable"><div className="head"><span>SECURITY</span>{qqlResult.metrics.map(m=><span key={m}>{m}</span>)}</div>{qqlResult.rows.map(r=><button key={r.symbol} onClick={()=>route('Desk',{fn:'DES',symbol:r.symbol})}><span><b>{r.symbol}</b></span>{qqlResult.metrics.map(m=><span key={m}>{m==='LAST'?money(r[m]):m==='CORRSPY'?num(r[m],2):pct(m==='MAXDD'?-r[m]:r[m])}</span>)}</button>)}</div></div><p className="twFoot">Supported metrics: LAST, RETURN1, RETURN5, RETURN20, RETURN60, RV20, RV60, MAXDD, CORRSPY. QQL is parsed locally; it does not execute arbitrary code.</p></Panel>}

  {fn==='SCEN'&&<Panel title="SCEN / MODEL STRESS LAB" sub="stress the curated research model in normalized R units" actions={<button className="twSmall" onClick={saveExperiment}><Save size={10}/>SAVE EXP</button>}><div className="twControls"><label><span>WIN RATE SHIFT</span><b>{wrShift>=0?'+':''}{wrShift} pts</b><input type="range" min="-15" max="10" step="1" value={wrShift} onChange={e=>setWrShift(Number(e.target.value))}/></label><label><span>WINNER SCALE</span><b>{winScale.toFixed(2)}×</b><input type="range" min="0.5" max="1.2" step="0.05" value={winScale} onChange={e=>setWinScale(Number(e.target.value))}/></label><label><span>LOSS SCALE</span><b>{lossScale.toFixed(2)}×</b><input type="range" min="0.8" max="1.8" step="0.05" value={lossScale} onChange={e=>setLossScale(Number(e.target.value))}/></label><label><span>LOSS CLUSTERING</span><b>{streakiness.toFixed(2)}</b><input type="range" min="0" max="0.7" step="0.05" value={streakiness} onChange={e=>setStreakiness(Number(e.target.value))}/></label><label><span>SEED</span><b>{seed}</b><input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value)||1)}/></label></div><div className="twScenarioStats"><div><span>MODELED W</span><b>{scenario.winProbability.toFixed(1)}%</b></div><div><span>MODELED L</span><b>{scenario.lossProbability.toFixed(1)}%</b></div><div><span>MEDIAN 100T</span><b>{num(scenario.median,1)}R</b></div><div><span>10TH PCTL</span><b>{num(scenario.p10,1)}R</b></div><div><span>P(NEGATIVE)</span><b>{scenario.pLoss.toFixed(1)}%</b></div><div><span>MEDIAN MAX DD</span><b>{num(scenario.medianDd,1)}R</b></div></div><ResponsiveContainer width="100%" height={360}><LineChart data={scenarioChart}><CartesianGrid stroke="#171a20" vertical={false}/><XAxis dataKey="trade" tick={{fontSize:8}} stroke="#515761"/><YAxis tick={{fontSize:8}} stroke="#515761"/><Tooltip contentStyle={{background:'#07080b',border:'1px solid #34303f',fontSize:9}}/>{scenario.sample.slice(0,12).map((_,i)=><Line key={i} dataKey={`p${i+1}`} dot={false} strokeWidth={.8}/>)}</LineChart></ResponsiveContainer><p className="twFoot">Research stress test only. Winner magnitudes use QNT's conservative log transform; the sample is selectively curated and normalized R is not stop-defined true R.</p></Panel>}

  {fn==='EXP'&&<Panel title="EXP / EXPERIMENT REGISTRY" sub="saved scenario lineage and reproducible settings"><div className="twExperiments">{experiments.map(x=><article key={x.id}><div><b>{x.id}</b><span>{new Date(x.createdAt).toLocaleString()}</span></div><div className="twExpMetrics"><span>WR SHIFT <b>{x.config.wrShift} pts</b></span><span>WIN <b>{x.config.winScale}×</b></span><span>LOSS <b>{x.config.lossScale}×</b></span><span>CLUSTER <b>{x.config.streakiness}</b></span><span>MEDIAN <b>{num(x.results.median,1)}R</b></span><span>P(NEG) <b>{num(x.results.pLoss,1)}%</b></span><span>DD <b>{num(x.results.medianDd,1)}R</b></span><span>SEED <b>{x.config.seed}</b></span></div></article>)}{!experiments.length&&<div className="twEmpty"><Database size={22}/><b>No saved experiments yet</b><span>Open SCEN, stress the model, then SAVE EXP.</span></div>}</div></Panel>}
  </div>;
}
