import React, { useEffect, useMemo, useState } from 'react';
import './volatility.css';
import { Activity, Braces, Database, FileCode2, Folder, Play, RefreshCw, Search, Sparkles, Waves } from 'lucide-react';
import InteractiveSurface3D from './InteractiveSurface3D.jsx';

const DTE_BUCKETS=[7,30,60,90];
const MONEYNESS_LEVELS=[-.20,-.15,-.10,-.05,0,.05,.10,.15,.20];
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';

function demoPayload(symbol='AAPL'){
  const underlyingPrice=225,contracts=[];DTE_BUCKETS.forEach((dte,di)=>MONEYNESS_LEVELS.forEach((m,mi)=>{const strike=Math.round((underlyingPrice*(1+m))/2.5)*2.5,smile=.205+Math.abs(m)*.43+Math.max(-m,0)*.17,term=di*.012,wave=Math.sin((mi+1)*.9+di*.7)*.008;['call','put'].forEach(side=>{const iv=Math.max(.12,smile+term+wave+(side==='put'?Math.max(-m,0)*.03:0));contracts.push({symbol,side,strike,dte,expiration:Date.now()/1000+dte*86400,iv,delta:side==='call'?Math.max(.05,.5-m*2.4):Math.min(-.05,-.5-m*2.4),gamma:.01+Math.max(0,.03-Math.abs(m)*.08),theta:-.02-dte/5000,vega:.08+dte/800,volume:Math.round(50+Math.abs(Math.sin(mi+di))*900),openInterest:Math.round(400+Math.abs(Math.cos(mi*.7+di))*5500),bid:Math.max(.1,underlyingPrice*Math.max(0,.02-Math.abs(m)*.03)),ask:Math.max(.12,underlyingPrice*Math.max(0,.022-Math.abs(m)*.028))})}))}));return{symbol,underlyingPrice,source:'Demo surface',delayed:true,updated:new Date().toISOString(),contracts,demo:true};
}

function nearestContract(contracts,targetStrike,side){const filtered=contracts.filter(c=>(side==='blend'||c.side===side)&&Number.isFinite(c.iv));if(!filtered.length)return null;if(side==='blend'){const calls=filtered.filter(c=>c.side==='call').sort((a,b)=>Math.abs(a.strike-targetStrike)-Math.abs(b.strike-targetStrike)),puts=filtered.filter(c=>c.side==='put').sort((a,b)=>Math.abs(a.strike-targetStrike)-Math.abs(b.strike-targetStrike)),call=calls[0],put=puts[0];if(call&&put)return{...call,iv:(call.iv+put.iv)/2,volume:(call.volume||0)+(put.volume||0),openInterest:(call.openInterest||0)+(put.openInterest||0)};return call||put||null}return filtered.sort((a,b)=>Math.abs(a.strike-targetStrike)-Math.abs(b.strike-targetStrike))[0]}
function buildSurface(payload,side){const contracts=(payload.contracts||[]).filter(c=>c.iv>.02&&c.iv<5&&c.dte>=0),spot=payload.underlyingPrice||1,dtes=[...new Set(contracts.map(c=>c.dte))].sort((a,b)=>a-b).slice(0,8),chosen=dtes.length?dtes:DTE_BUCKETS,rows=chosen.map(dte=>{const bucket=contracts.filter(c=>c.dte===dte);return MONEYNESS_LEVELS.map(m=>{const target=spot*(1+m),c=nearestContract(bucket,target,side);return{dte,moneyness:m,strike:c?.strike??target,iv:c?.iv??0,volume:c?.volume||0,openInterest:c?.openInterest||0}})});return{rows,dtes:chosen,spot}}
function metricSummary(surface,payload){if(!surface.rows.length)return{atm:0,skew:0,term:0,min:0,max:0,oi:0,volume:0};const atmIndex=MONEYNESS_LEVELS.indexOf(0),atmValues=surface.rows.map(r=>r[atmIndex]?.iv||0).filter(Boolean),first=surface.rows[0],putWing=first?.[2]?.iv||0,callWing=first?.[6]?.iv||0,values=surface.rows.flat().map(p=>p.iv).filter(Boolean),oi=(payload.contracts||[]).reduce((s,c)=>s+(c.openInterest||0),0),volume=(payload.contracts||[]).reduce((s,c)=>s+(c.volume||0),0);return{atm:atmValues[0]||0,skew:putWing-callWing,term:(atmValues.at(-1)||0)-(atmValues[0]||0),min:Math.min(...values),max:Math.max(...values),oi,volume}}

function MiniLine({points,label,format=v=>v}){const vals=points.map(p=>p.y).filter(Number.isFinite);if(vals.length<2)return <div className="volMiniEmpty">not enough data</div>;const lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1,pts=points.map((p,i)=>`${8+i*(284/Math.max(1,points.length-1))},${76-(p.y-lo)/span*60}`).join(' ');return <svg className="volMiniSvg" viewBox="0 0 300 84" preserveAspectRatio="none"><line x1="8" y1="76" x2="292" y2="76" stroke="#242733"/><polyline points={pts} fill="none" stroke="#b07cff" strokeWidth="1.6"/><text x="8" y="10" fill="#666d76" fontSize="7">{label}</text><text x="292" y="10" textAnchor="end" fill="#a892d8" fontSize="7">{format(points.at(-1)?.y)}</text></svg>}

export default function VolatilityLab(){
  const [symbol,setSymbol]=useState('AAPL'),[query,setQuery]=useState('AAPL'),[side,setSide]=useState('blend'),[payload,setPayload]=useState(()=>demoPayload('AAPL')),[loading,setLoading]=useState(false),[message,setMessage]=useState('Demo surface loaded. Connect the delayed-data token to replace it.'),[selectedDte,setSelectedDte]=useState(30),[ai,setAi]=useState(''),[aiLoading,setAiLoading]=useState(false);
  const load=async(requested=query)=>{const clean=String(requested||'AAPL').trim().toUpperCase();setLoading(true);setMessage('Loading delayed option-chain snapshots…');try{const res=await fetch(`/api/options-chain?symbol=${encodeURIComponent(clean)}&dtes=${DTE_BUCKETS.join(',')}&strikeLimit=14`),data=await res.json();if(!res.ok||!Array.isArray(data.contracts)||!data.contracts.length)throw new Error(data.error||'No option data returned');setPayload(data);setQuery(clean);setSymbol(clean);setSelectedDte(data.dteBuckets?.[1]??data.dteBuckets?.[0]??30);setMessage(`${data.source||'Options API'} • ${data.delayed?'delayed/provider-entitled data':'provider data'}`);try{const key=`qnt.iv.archive.${clean}`,prior=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([...prior,{updated:data.updated,underlyingPrice:data.underlyingPrice,contracts:data.contracts}].slice(-30)))}catch{}}catch(error){setPayload(demoPayload(clean));setQuery(clean);setSymbol(clean);setMessage(`${error.message}. Showing clearly labeled demo data instead.`)}finally{setLoading(false)}};
  useEffect(()=>{load('AAPL')},[]);
  const surface=useMemo(()=>buildSurface(payload,side),[payload,side]),metrics=useMemo(()=>metricSummary(surface,payload),[surface,payload]),updated=payload.updated?new Date(payload.updated).toLocaleString():'—';
  const bucket=useMemo(()=>payload.contracts.filter(c=>c.dte===selectedDte),[payload,selectedDte]);
  const smile=useMemo(()=>MONEYNESS_LEVELS.map(m=>{const c=nearestContract(bucket,(payload.underlyingPrice||1)*(1+m),side);return{x:m,y:c?.iv||0}}).filter(p=>p.y>0),[bucket,payload,side]);
  const term=useMemo(()=>surface.rows.map((r,i)=>({x:surface.dtes[i],y:r[MONEYNESS_LEVELS.indexOf(0)]?.iv||0})).filter(p=>p.y>0),[surface]);
  const chainRows=useMemo(()=>[...bucket].sort((a,b)=>Math.abs(a.strike-payload.underlyingPrice)-Math.abs(b.strike-payload.underlyingPrice)).slice(0,16),[bucket,payload]);
  const askAi=async()=>{setAiLoading(true);setAi('');try{const screenContext={module:'Volatility',symbol,source:payload.demo?'demo':'MarketData.app',delayed:payload.delayed,updated,side,selectedDte,spot:payload.underlyingPrice,metrics:{atmIV:metrics.atm,putCallSkew:metrics.skew,termSlope:metrics.term,surfaceMin:metrics.min,surfaceMax:metrics.max,totalOpenInterest:metrics.oi,totalVolume:metrics.volume}};const res=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Explain the currently displayed volatility surface, skew, term structure, liquidity and the main limitations of this dataset. Do not give a trade recommendation.',activeFile:`${symbol.toLowerCase()}_iv_surface.qnt`,code:'',researchContext:'Use only the supplied volatility screen context.',screenContext})}),data=await res.json();if(!res.ok)throw new Error(data.error||'Copilot failed');setAi(data.text)}catch(e){setAi(`Copilot error: ${e.message}`)}finally{setAiLoading(false)}};
  return <div className="volTerminal"><header className="volTerminalHead"><div><span>VOLATILITY WORKSTATION</span><h1>{symbol} volatility surface</h1><p>{message}</p></div><div className="volTerminalStatus"><span className={payload.demo?'demo':'live'}/>{payload.demo?'DEMO FALLBACK':'PROVIDER DATA'}<small>{updated}</small></div></header><div className="volTerminalToolbar"><div className="volTicker"><Search size={12}/><input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} onKeyDown={e=>e.key==='Enter'&&load(query)}/><button onClick={()=>load(query)} disabled={loading}><RefreshCw size={12}/>{loading?'LOADING':'GO'}</button></div>{['blend','call','put'].map(v=><button key={v} className={side===v?'active':''} onClick={()=>setSide(v)}>{v==='blend'?'CALL+PUT':v.toUpperCase()}</button>)}<select value={selectedDte} onChange={e=>setSelectedDte(Number(e.target.value))}>{surface.dtes.map(d=><option key={d} value={d}>{d} DTE</option>)}</select></div>
    <div className="volTerminalMetrics"><div><span>SPOT</span><b>${fmt(payload.underlyingPrice)}</b></div><div><span>ATM IV</span><b>{(metrics.atm*100).toFixed(2)}%</b></div><div><span>DOWNSIDE SKEW</span><b>{metrics.skew>=0?'+':''}{(metrics.skew*100).toFixed(2)} vol</b></div><div><span>TERM SLOPE</span><b>{metrics.term>=0?'+':''}{(metrics.term*100).toFixed(2)} vol</b></div><div><span>OPEN INTEREST</span><b>{metrics.oi.toLocaleString()}</b></div><div><span>DAY VOLUME</span><b>{metrics.volume.toLocaleString()}</b></div></div>
    <div className="volTerminalGrid"><section className="volSurface panel"><div className="volPanelHead"><div><Waves size={13}/><b>3D IMPLIED VOLATILITY SURFACE</b></div><span>DTE × moneyness × IV · interactive mesh</span></div><InteractiveSurface3D surface={surface} moneynessLevels={MONEYNESS_LEVELS}/></section><aside className="volSideStack"><section className="panel"><div className="volPanelHead"><b>SMILE · {selectedDte} DTE</b><span>moneyness → IV</span></div><MiniLine points={smile} label="IV smile" format={v=>`${(v*100).toFixed(1)}%`}/></section><section className="panel"><div className="volPanelHead"><b>ATM TERM STRUCTURE</b><span>DTE → IV</span></div><MiniLine points={term} label="ATM IV" format={v=>`${(v*100).toFixed(1)}%`}/></section><section className="panel volLiquidity"><div className="volPanelHead"><b>LIQUIDITY SNAPSHOT</b><span>{selectedDte} DTE</span></div><div><span>TOTAL OI</span><b>{bucket.reduce((s,c)=>s+(c.openInterest||0),0).toLocaleString()}</b></div><div><span>DAY VOLUME</span><b>{bucket.reduce((s,c)=>s+(c.volume||0),0).toLocaleString()}</b></div><div><span>CONTRACTS</span><b>{bucket.length}</b></div><div><span>SURFACE RANGE</span><b>{(metrics.min*100).toFixed(0)}–{(metrics.max*100).toFixed(0)}%</b></div></section></aside>
      <section className="panel volChain"><div className="volPanelHead"><div><Database size={13}/><b>OPTION CHAIN · NEAR SPOT</b></div><span>{selectedDte} DTE · {payload.demo?'demo':'provider'} data</span></div><div className="volChainHead"><span>SIDE</span><span>STRIKE</span><span>IV</span><span>DELTA</span><span>GAMMA</span><span>THETA</span><span>VEGA</span><span>BID</span><span>ASK</span><span>VOL</span><span>OI</span></div><div className="volChainBody">{chainRows.map((c,i)=><div key={`${c.optionSymbol||i}-${c.side}`}><span className={c.side==='call'?'call':'put'}>{c.side?.toUpperCase()}</span><span>{fmt(c.strike)}</span><span>{(c.iv*100).toFixed(1)}%</span><span>{fmt(c.delta)}</span><span>{fmt(c.gamma)}</span><span>{fmt(c.theta)}</span><span>{fmt(c.vega)}</span><span>{fmt(c.bid)}</span><span>{fmt(c.ask)}</span><span>{(c.volume||0).toLocaleString()}</span><span>{(c.openInterest||0).toLocaleString()}</span></div>)}</div></section>
      <section className="panel volCopilotPanel"><div className="volPanelHead"><div><Sparkles size={13}/><b>QNT COPILOT · SURFACE CONTEXT</b></div><button onClick={askAi} disabled={aiLoading}><Activity size={12}/>{aiLoading?'ANALYZING':'EXPLAIN SURFACE'}</button></div><p>{ai||'Ask Copilot to interpret the exact surface, skew, term structure and liquidity currently on screen. The screen context is sent with the request.'}</p></section>
    </div><div className="volTerminalFoot"><Braces size={11}/> provider values are shown only when returned by the API · demo fallback is labeled · hover the 3D mesh for exact IV points</div></div>;
}
